<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reaffecter</name>
   <tag></tag>
   <elementGuidId>4419f18b-e9c7-4693-b966-1426eb044a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='teleProcedureForm:listeTeleProcedureATraiter:0:j_id159']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Réaffecter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9602dab8-86ce-4330-9b00-ea3f2320ce83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id159</value>
      <webElementGuid>2b3d242a-b62e-40ea-ae3b-f782a6e5eba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id159</value>
      <webElementGuid>2b9f76a9-c44a-46ad-985c-54746a826483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id159','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id159':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id159'} } );return false;</value>
      <webElementGuid>5b4f7693-ea5c-4604-bc7a-3b6c04bc2387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Réaffecter</value>
      <webElementGuid>3da70b07-ebd9-4b91-94ec-4d39366d3eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ba65ef78-fc3e-490e-b69b-be467fe90c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/deposer.gif</value>
      <webElementGuid>dc4c8600-0ef1-4357-8bdf-721de1b6c52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id159&quot;)</value>
      <webElementGuid>f526c49a-9d33-4e3e-aa03-f6369197d10b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='teleProcedureForm:listeTeleProcedureATraiter:0:j_id159']</value>
      <webElementGuid>dda08b63-6285-4352-8f3f-7bd8b3f54c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='teleProcedureForm:listeTeleProcedureATraiter:0:j_id150']/span/div/input[4]</value>
      <webElementGuid>482747cb-8690-47c3-ba78-ff9329df751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>46397b65-1aa7-4d9b-92f2-2efe0fbe6bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id159' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id159' and @alt = 'Réaffecter' and @type = 'image' and @src = '/interfaceCreation/images/commun/deposer.gif']</value>
      <webElementGuid>5293a7a4-4715-460c-9c72-09733d3119d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
