<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recherche avance_teleProcedureFormrec_626dcc</name>
   <tag></tag>
   <elementGuidId>868b4ec8-5632-4a9d-b2f0-35cfa4d2e2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='teleProcedureForm:rechercherTeleProcedure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Lancer la recherche&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>872924e4-db80-4c17-bba5-120900ed4ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:rechercherTeleProcedure</value>
      <webElementGuid>79f7eb3e-edb8-4b91-b17e-dcfc0a06946d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19703de2-2b51-4991-ba3c-0108c3564f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:rechercherTeleProcedure</value>
      <webElementGuid>14a0d708-56aa-42dc-9279-93b38ba515c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lancer la recherche</value>
      <webElementGuid>21c6901a-3b92-4501-9a6f-37d9d09fe2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lancer la recherche</value>
      <webElementGuid>b141d181-2721-42b7-8272-d5626a0778e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-action1 btn-block</value>
      <webElementGuid>764774d1-1c1e-4599-8a47-20e7686d54fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>061a0469-a4ac-445f-bd66-c74929c19f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm:rechercherTeleProcedure&quot;)</value>
      <webElementGuid>9c6a0886-06d0-40a8-98f9-83f2f50f2404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='teleProcedureForm:rechercherTeleProcedure']</value>
      <webElementGuid>cea55080-32de-4424-b39b-db1595efd18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='teleProcedureForm:j_id72_body']/div[2]/div/input</value>
      <webElementGuid>f012ddb0-4940-4b2d-96b7-51a129e30e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7c9a52ef-26a6-4add-8d19-fa1c7360eb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:rechercherTeleProcedure' and @type = 'submit' and @name = 'teleProcedureForm:rechercherTeleProcedure' and @alt = 'Lancer la recherche']</value>
      <webElementGuid>ab657834-16b6-460d-9dcb-8d62a416e7ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
