<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suivi_des_evenement</name>
   <tag></tag>
   <elementGuidId>096e9a64-b83c-4a25-9536-c4b1031774ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='teleProcedureForm:listeTeleProcedureATraiter:0:j_id158']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Editer Evenements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05855279-782f-40d2-a017-599175d4510e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id158</value>
      <webElementGuid>a8273639-cc60-41a7-95e5-5a2c1699ae73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id158</value>
      <webElementGuid>ae4db324-09d1-4bf4-b457-cf05203fe9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id158','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id158':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id158'} } );return false;</value>
      <webElementGuid>32971fc4-c032-4b2d-8798-c4b02b25e1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Editer Evenements</value>
      <webElementGuid>5471f266-6cbf-401e-87a7-ebd3fd3e3b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ff16c490-4094-431e-b207-e07c83d9e866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/suiviDesEvenements.gif</value>
      <webElementGuid>c1df2842-ad2c-45c7-8acc-8d77d25b005f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id158&quot;)</value>
      <webElementGuid>33d7e880-473d-4664-add9-cd1330d478cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='teleProcedureForm:listeTeleProcedureATraiter:0:j_id158']</value>
      <webElementGuid>bb26a00d-21ff-4680-8cff-2ee6e3e96135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='teleProcedureForm:listeTeleProcedureATraiter:0:j_id150']/span/div/input[3]</value>
      <webElementGuid>0734ab19-6009-47cc-9ba0-cdab4d939e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>16198bbc-4625-4ddf-b6dd-6b55aa732378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id158' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id158' and @alt = 'Editer Evenements' and @type = 'image' and @src = '/interfaceCreation/images/commun/suiviDesEvenements.gif']</value>
      <webElementGuid>e61dbf0b-e89b-4d74-ba29-f232d046cdbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
