<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lien_Contrat_de_bail_Sign</name>
   <tag></tag>
   <elementGuidId>23368673-5094-430b-a363-2ce64e3d4dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18d33589-2a3a-4e3f-8641-3d595f106bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>5fed75a1-4874-4da2-bd91-3e033dfd737c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>6d00635a-580e-45ae-ac8e-7c7ba9c6adf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157'} } );return false;</value>
      <webElementGuid>feb5655f-b32e-48a3-b405-3698ef0e9fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Visualiser</value>
      <webElementGuid>53c0e875-b79e-40df-b3e6-3d0502df6ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>bfa2eaf8-fb33-4196-8f8c-47144d34d802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/visualiser.gif</value>
      <webElementGuid>cd697d69-ccb2-468d-a19b-82925296c33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa050c28-5cd2-4b42-99dd-3e4e400afdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm&quot;)/div[@id=&quot;teleProcedureForm:j_id22&quot;]/div[@id=&quot;teleProcedureForm:j_id22_body&quot;]/div[@id=&quot;teleProcedureForm:j_id110&quot;]/div[@id=&quot;teleProcedureForm:j_id110_body&quot;]/table[@id=&quot;teleProcedureForm:j_id113&quot;]/tbody[1]/tr[2]/td[@id=&quot;teleProcedureForm:j_id114&quot;]/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content  dossier-en-cours&quot;]/table[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter&quot;]/tbody[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:tb&quot;]/tr[@class=&quot;rich-table-row rich-table-firstrow&quot;]/td[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id151&quot;]/span[@class=&quot;dropdown dropdown-actions open&quot;]/div[@class=&quot;dropdown-menu&quot;]/input[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id157&quot;]</value>
      <webElementGuid>2f601b6f-aacf-4de0-ab87-d01baf7f37b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      <webElementGuid>7040028d-89b6-4935-b27b-a88a6d03ba79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
