<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lien_RECAPITULATIF</name>
   <tag></tag>
   <elementGuidId>dbbfd4d9-f354-47f5-82a2-8de09d375b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'teleProcedureForm:listPieceJointG:2:clGet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a5c35e8-c892-4455-aa9d-318ed8fa8f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>b32f01e5-31e3-4fb9-82ea-e5b5e4f0f53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>ba56dfb6-bbbe-4190-9c2a-608f96067c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157'} } );return false;</value>
      <webElementGuid>65e030fa-3804-4fe7-b39a-941d06f532df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Visualiser</value>
      <webElementGuid>f9ca5a10-3024-4190-b2de-e7b251b97734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>8ebcbbe2-d502-4df2-a9fd-541d73cc05b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/visualiser.gif</value>
      <webElementGuid>6a73092d-1e8e-442d-b5f9-4ca4ffac4efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>07d6ff70-b1cb-40cc-8fdb-c7331699b362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm&quot;)/div[@id=&quot;teleProcedureForm:j_id22&quot;]/div[@id=&quot;teleProcedureForm:j_id22_body&quot;]/div[@id=&quot;teleProcedureForm:j_id110&quot;]/div[@id=&quot;teleProcedureForm:j_id110_body&quot;]/table[@id=&quot;teleProcedureForm:j_id113&quot;]/tbody[1]/tr[2]/td[@id=&quot;teleProcedureForm:j_id114&quot;]/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content  dossier-en-cours&quot;]/table[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter&quot;]/tbody[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:tb&quot;]/tr[@class=&quot;rich-table-row rich-table-firstrow&quot;]/td[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id151&quot;]/span[@class=&quot;dropdown dropdown-actions open&quot;]/div[@class=&quot;dropdown-menu&quot;]/input[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id157&quot;]</value>
      <webElementGuid>1c21c30d-fe29-4fd2-b538-d692e7741613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      <webElementGuid>810bc20c-b9eb-479f-8511-f0f43b70e7cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
