<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lien_XMLDOSSIER</name>
   <tag></tag>
   <elementGuidId>a12f361c-d622-4396-8b1f-77d7f1786e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d126f473-c2a0-4689-ae12-6b09f6787436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>4e478c6f-acb7-4c84-bcd8-8ded54567441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>dc4c37d8-26da-4ee9-8e13-3c487c75329a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157'} } );return false;</value>
      <webElementGuid>4561805f-24fd-41df-8bbf-b66a47980461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Visualiser</value>
      <webElementGuid>243387cd-6bd0-44b3-953a-f5e2ab695a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>4bb8f5ed-08be-4628-9f02-a3ec7d760965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/visualiser.gif</value>
      <webElementGuid>9c9e1a13-83a7-4330-9d80-4aa057fd2130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea8b22b7-97f1-4815-adfd-b8cba2e2326d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm&quot;)/div[@id=&quot;teleProcedureForm:j_id22&quot;]/div[@id=&quot;teleProcedureForm:j_id22_body&quot;]/div[@id=&quot;teleProcedureForm:j_id110&quot;]/div[@id=&quot;teleProcedureForm:j_id110_body&quot;]/table[@id=&quot;teleProcedureForm:j_id113&quot;]/tbody[1]/tr[2]/td[@id=&quot;teleProcedureForm:j_id114&quot;]/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content  dossier-en-cours&quot;]/table[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter&quot;]/tbody[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:tb&quot;]/tr[@class=&quot;rich-table-row rich-table-firstrow&quot;]/td[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id151&quot;]/span[@class=&quot;dropdown dropdown-actions open&quot;]/div[@class=&quot;dropdown-menu&quot;]/input[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id157&quot;]</value>
      <webElementGuid>d1c9bc32-7d02-45e8-90c5-4b76bc550e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      <webElementGuid>87b4eacc-b77f-4a63-a576-dd26f1365a36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
