<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lien_CNIE_Commerant</name>
   <tag></tag>
   <elementGuidId>fa09d834-0856-4877-b777-972aedb01f03</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14b99436-01f7-44d1-90b9-3fe52cd519c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>9ea44ab2-215f-48ed-aa46-f2d6af14e7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>74ca9445-61a7-47c3-9edb-bff882fd6cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157'} } );return false;</value>
      <webElementGuid>1012366d-d579-42f0-8f51-86a63840cfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Visualiser</value>
      <webElementGuid>ccae2649-6302-47dd-888d-254adc0bb0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5d981696-9519-484a-9650-54074ccdd788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/visualiser.gif</value>
      <webElementGuid>592a6fd5-44db-4e1b-af22-3d5f2e3cb421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8798fe1e-56e6-4e17-85b1-acc26e850545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm&quot;)/div[@id=&quot;teleProcedureForm:j_id22&quot;]/div[@id=&quot;teleProcedureForm:j_id22_body&quot;]/div[@id=&quot;teleProcedureForm:j_id110&quot;]/div[@id=&quot;teleProcedureForm:j_id110_body&quot;]/table[@id=&quot;teleProcedureForm:j_id113&quot;]/tbody[1]/tr[2]/td[@id=&quot;teleProcedureForm:j_id114&quot;]/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content  dossier-en-cours&quot;]/table[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter&quot;]/tbody[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:tb&quot;]/tr[@class=&quot;rich-table-row rich-table-firstrow&quot;]/td[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id151&quot;]/span[@class=&quot;dropdown dropdown-actions open&quot;]/div[@class=&quot;dropdown-menu&quot;]/input[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id157&quot;]</value>
      <webElementGuid>bfc6edcd-bffb-4df8-a3a3-e00e45174459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      <webElementGuid>bc35bee3-9c16-46bb-be64-63787e2f68c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
