<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lien_XMLTP</name>
   <tag></tag>
   <elementGuidId>e939b0f7-cf3c-4c9c-b4e2-22524266d4d2</elementGuidId>
   <imagePath>../../tpxml.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>../../tpxml.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43da3e5b-9fd8-4d0d-9c83-a37c78cfab07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>547570f9-89dd-4d26-852b-54b93bfb6ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>teleProcedureForm:listeTeleProcedureATraiter:0:j_id157</value>
      <webElementGuid>280ad44e-0c31-4874-9c6b-f4f2adf27474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('teleProcedureForm',event,{'similarityGroupingId':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157','parameters':{'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157':'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157'} } );return false;</value>
      <webElementGuid>2ac7328c-d865-477b-a3ba-4b0fe9552960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Visualiser</value>
      <webElementGuid>ed5a4165-480e-46eb-9be5-51d50f83cd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c5412298-5ab0-43d5-bae0-b1d9648cc4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/interfaceCreation/images/commun/visualiser.gif</value>
      <webElementGuid>eef4599d-a445-4461-a2ad-fe7db93a3324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf1d684a-fc1a-4ea8-ba86-13560b570cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teleProcedureForm&quot;)/div[@id=&quot;teleProcedureForm:j_id22&quot;]/div[@id=&quot;teleProcedureForm:j_id22_body&quot;]/div[@id=&quot;teleProcedureForm:j_id110&quot;]/div[@id=&quot;teleProcedureForm:j_id110_body&quot;]/table[@id=&quot;teleProcedureForm:j_id113&quot;]/tbody[1]/tr[2]/td[@id=&quot;teleProcedureForm:j_id114&quot;]/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content  dossier-en-cours&quot;]/table[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter&quot;]/tbody[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:tb&quot;]/tr[@class=&quot;rich-table-row rich-table-firstrow&quot;]/td[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id151&quot;]/span[@class=&quot;dropdown dropdown-actions open&quot;]/div[@class=&quot;dropdown-menu&quot;]/input[@id=&quot;teleProcedureForm:listeTeleProcedureATraiter:0:j_id157&quot;]</value>
      <webElementGuid>c4b62120-7d56-4457-bbe0-d6cdd2e6c8e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @name = 'teleProcedureForm:listeTeleProcedureATraiter:0:j_id157' and @alt = 'Visualiser' and @type = 'image' and @src = '/interfaceCreation/images/commun/visualiser.gif']</value>
      <webElementGuid>ac3c7ef5-4335-4da7-b65a-2845239977e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
