<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Beat SPAM with the best disposable ema_24596f</name>
   <tag></tag>
   <elementGuidId>fc26865f-a91f-4b05-8936-aa7211125e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='copy_address']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.copy_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4bd31b8b-7fdf-4102-a21d-f4ef36a48b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>copy_icon</value>
      <webElementGuid>40e5d9dd-e3c1-4447-871f-bc4da7386578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copy_address&quot;)/span[@class=&quot;copy_icon&quot;]</value>
      <webElementGuid>cf5cc994-d326-49f4-9060-175afb61baf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='copy_address']/span</value>
      <webElementGuid>552e0052-4c4f-499d-b778-8e9e63eeda94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>3a4e3006-9ccc-4c24-bb84-6d4a9cbe3413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
