<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>9e8f4360-899b-4de6-81db-b47ed4886599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//vli[@id='video-player-contain']/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>339ed698-8d56-44d9-b545-65fa8c2104e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>//assets.vlitag.com/widget/2023/03/24/1679645040.png</value>
      <webElementGuid>8dc1832f-3f29-4732-9656-25909add16c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;video-player-contain&quot;)/video[1]</value>
      <webElementGuid>2f4249bd-9d7c-4819-9e06-9252ad2366ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//vli[@id='video-player-contain']/video</value>
      <webElementGuid>6adc14ef-eaad-43bc-be09-a26aa22abdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::video[1]</value>
      <webElementGuid>4491dd60-12f8-4c1b-8f9a-c77d6c6b7bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valueimpression'])[1]/preceding::video[1]</value>
      <webElementGuid>1dc22d93-8eec-428a-adcd-b4343ad145b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>15d1028a-9276-46dd-bac5-9e38014da50a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
