<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nouveau dossier</name>
   <tag></tag>
   <elementGuidId>ab50b761-5863-47ef-8ec9-90c3215a11ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconbienvenue:ajout_dossier_pm_jsf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>72926b77-9722-45cb-9fce-aafdcfb909f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-item-label</value>
      <webElementGuid>9f6d6de2-2eb6-4713-bbdb-3392ed9d74b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconbienvenue:ajout_dossier_pm_jsf</value>
      <webElementGuid>4fe9c6c3-6942-4879-9f8c-64c8883391d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ddfafe16-5f56-433f-af98-498d266badc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nouveau dossier</value>
      <webElementGuid>2dedbbb8-cbc7-43da-a1c6-eaff0076b234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconbienvenue:ajout_dossier_pm_jsf&quot;)</value>
      <webElementGuid>75a90425-d2ca-49ac-8d69-a23672c0d28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconbienvenue:ajout_dossier_pm_jsf']</value>
      <webElementGuid>372fe059-713a-43b1-8e5c-d2d22cd60abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_bienvenue:ajout_dossier_pm_jsf']/td[2]</value>
      <webElementGuid>5608d377-1eb3-4b31-af24-94d03d9a6243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personne morale'])[1]/following::td[3]</value>
      <webElementGuid>fe579cc9-6c39-4976-b987-9752f340d54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Création d', &quot;'&quot;, 'entreprise')])[2]/following::td[5]</value>
      <webElementGuid>86366f91-47fd-4627-aa76-852427d65b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recherche des dossiers'])[1]/preceding::td[3]</value>
      <webElementGuid>bf41895b-7508-462d-aee8-26a9e1172d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Succursale d', &quot;'&quot;, 'une entreprise Marocaine')])[1]/preceding::td[6]</value>
      <webElementGuid>27a40ea0-6764-43bc-8667-59721147645f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nouveau dossier']/parent::*</value>
      <webElementGuid>8f871d7d-b325-4db8-8882-0fdcd82c1c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>a066ea25-dd62-4b3a-b310-e3695822596b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconbienvenue:ajout_dossier_pm_jsf' and (text() = 'Nouveau dossier' or . = 'Nouveau dossier')]</value>
      <webElementGuid>6678f553-0561-457d-ad63-321c41530fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
