<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Personne morale</name>
   <tag></tag>
   <elementGuidId>f4c57ef1-48e9-4450-a6fd-fed3c1e15192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconbienvenue:dossierPM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dd2ecc91-1729-4f4e-80c0-e5a4d194cac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-group-self-label rich-pmenu-top-group-self-label</value>
      <webElementGuid>b6686331-c951-406a-ba23-4f4c4f6eaff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconbienvenue:dossierPM</value>
      <webElementGuid>3e38c34d-f847-446c-bf8d-a6cfd0429c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9f2c9f02-769a-483f-9d56-a19ae09f6101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personne morale</value>
      <webElementGuid>ea31b65b-5e08-4987-848d-90545c82f734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconbienvenue:dossierPM&quot;)</value>
      <webElementGuid>8a08532b-1a3f-4a8b-8d66-fe390a4b4ff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconbienvenue:dossierPM']</value>
      <webElementGuid>525553da-a526-4038-a73a-bcaa7f59b690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_bienvenue:dossierPM']/td[2]</value>
      <webElementGuid>59e1a649-bdce-4674-8210-da6e4c38fdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Création d', &quot;'&quot;, 'entreprise')])[2]/following::td[2]</value>
      <webElementGuid>eca22e24-b0b1-4623-892f-d7d4b0c924da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Création d', &quot;'&quot;, 'entreprise')])[1]/following::td[2]</value>
      <webElementGuid>08750e1a-c847-4f40-979c-bae0fb753fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[1]/preceding::td[3]</value>
      <webElementGuid>97e48f93-ed38-496a-883b-5ab8fa1dc784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recherche des dossiers'])[1]/preceding::td[6]</value>
      <webElementGuid>fb949444-d5c2-4c4e-b488-abc17e960aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Personne morale']/parent::*</value>
      <webElementGuid>9496b8da-83e2-4416-bb4b-f323e41e9707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>46143a98-e9d9-44c2-9281-14f5807ba214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconbienvenue:dossierPM' and (text() = 'Personne morale' or . = 'Personne morale')]</value>
      <webElementGuid>3149f66a-e34a-480a-8218-a065cf0d60af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
