<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accueil</name>
   <tag></tag>
   <elementGuidId>90bcb710-33d3-4235-8001-a16d029e3b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-connexion.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='error-page']/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fc7723e-20a8-4ab7-b9c5-a893ad71cf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Guichet/login.jsp</value>
      <webElementGuid>1aad9ce2-214a-474c-883f-89c27d0423f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion btn-block</value>
      <webElementGuid>39af79a1-1f5a-4442-8d00-7dbc305a4e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accueil</value>
      <webElementGuid>3aa549b0-13f9-41b5-bb41-9cf6c668d46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-page&quot;)/div[@class=&quot;container form-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/a[@class=&quot;btn btn-connexion btn-block&quot;]</value>
      <webElementGuid>5e0ff2b7-ebaa-49f7-a7d9-f5eb72bcde32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='error-page']/div/div/div[2]/a</value>
      <webElementGuid>9182f878-a50d-4a0a-9426-34e2c5b37d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accueil')]</value>
      <webElementGuid>4152cfa9-57b0-4169-8042-92e4ed9550a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='entreprise'])[1]/following::a[1]</value>
      <webElementGuid>97ec94cf-5f7c-4fd9-ba0b-9a59c8712153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accueil']/parent::*</value>
      <webElementGuid>1a6aa2ff-8305-4f8d-b8be-7d707c9b1b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Guichet/login.jsp')]</value>
      <webElementGuid>a2454ae0-1e2b-4d24-9502-0312969861f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>2136b67a-6794-4526-b3f3-3465decf04b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Guichet/login.jsp' and (text() = 'Accueil' or . = 'Accueil')]</value>
      <webElementGuid>709a6ae6-e19d-4bee-add0-77411170938e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
