<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Personne morale</name>
   <tag></tag>
   <elementGuidId>958e791f-b7a9-4282-a587-17b8131a5054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconbienvenue:dossierPM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>30003857-af87-443f-b7ff-0047c4bcde89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-group-self-label rich-pmenu-top-group-self-label</value>
      <webElementGuid>1df0382f-7fbd-4c67-b0d7-59d3cb200eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconbienvenue:dossierPM</value>
      <webElementGuid>491140aa-ad78-47eb-b779-e55b4be42e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7b8d7d49-9c7b-4e74-bac6-4fd449f061f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personne morale</value>
      <webElementGuid>eb072392-fa6e-434b-a427-16bb9a89c369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconbienvenue:dossierPM&quot;)</value>
      <webElementGuid>e45cefa9-088a-4514-bf77-b6ea82ba67b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconbienvenue:dossierPM']</value>
      <webElementGuid>e6bf46e2-dbb1-4f19-aca9-c4f3d1349ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_bienvenue:dossierPM']/td[2]</value>
      <webElementGuid>5afa8c22-ac68-45b4-91f1-81230aeaf690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Création d', &quot;'&quot;, 'entreprise')])[2]/following::td[2]</value>
      <webElementGuid>fe402234-ee89-4328-a429-124a4c05428f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Création d', &quot;'&quot;, 'entreprise')])[1]/following::td[2]</value>
      <webElementGuid>65e97f76-3162-4b85-8e06-0b90f4d082e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[1]/preceding::td[3]</value>
      <webElementGuid>83ec558e-55d9-4ab5-b910-98f41aa03319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recherche des dossiers'])[1]/preceding::td[6]</value>
      <webElementGuid>16826087-082e-4df1-a411-4ac6eac0d2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Personne morale']/parent::*</value>
      <webElementGuid>d746bb87-bc0d-4fbd-b5a2-4991d42d83f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>12d84600-6cdf-4cf4-a310-1692419f7a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconbienvenue:dossierPM' and (text() = 'Personne morale' or . = 'Personne morale')]</value>
      <webElementGuid>34fe97ad-f5a0-4ad1-92f4-1e001393cc43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
