<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Recherche des dossiers</name>
   <tag></tag>
   <elementGuidId>397b3a89-49dd-4444-b7a6-5631082db785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconbienvenue:liste_dossier_pm_jsf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b861dc2a-fd44-4ce8-9c27-add10677f228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-item-label</value>
      <webElementGuid>eff29afa-4472-4c9c-8bff-821e8d547009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconbienvenue:liste_dossier_pm_jsf</value>
      <webElementGuid>f06c5b92-15bd-478b-99bd-2da1d4e0714b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8d764f95-b09d-4d9a-aff0-2669b38d489d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recherche des dossiers</value>
      <webElementGuid>fe9c92a4-536a-46ed-ac2b-042c1bdce547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconbienvenue:liste_dossier_pm_jsf&quot;)</value>
      <webElementGuid>3899c503-bb6a-4b2c-b08b-990ff6b8df9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconbienvenue:liste_dossier_pm_jsf']</value>
      <webElementGuid>2bdc7d3b-d1c8-452b-a3fd-18709fc5e9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_bienvenue:liste_dossier_pm_jsf']/td[2]</value>
      <webElementGuid>3bc42413-846b-4447-acbb-e1c2270bb266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[1]/following::td[3]</value>
      <webElementGuid>6a4193ff-b3b1-4f22-bf00-f534234fba38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personne morale'])[1]/following::td[6]</value>
      <webElementGuid>2e909e4f-1940-4f86-92d6-52c82cf8e476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Succursale d', &quot;'&quot;, 'une entreprise Marocaine')])[1]/preceding::td[3]</value>
      <webElementGuid>af54cb61-dd03-4387-897e-e3c8c363fa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[2]/preceding::td[9]</value>
      <webElementGuid>e62b1ab0-a85f-42ad-8320-d64f4db816ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recherche des dossiers']/parent::*</value>
      <webElementGuid>89ae7561-ffa7-4607-8c52-adcd33c2d35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>39247689-31e1-469e-9633-5c440a0e97fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconbienvenue:liste_dossier_pm_jsf' and (text() = 'Recherche des dossiers' or . = 'Recherche des dossiers')]</value>
      <webElementGuid>54e26508-b51c-427b-81ba-4c18cdcbe242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
