<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RECAP.pdf_signatureDocumentsFormsigne_21668d</name>
   <tag></tag>
   <elementGuidId>fb45bb1f-ade4-4694-b67a-3a55e5e723ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:signedDocuments:1:consultDocument']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;RECAP.pdf Consulter&quot;i] >> internal:attr=[alt=&quot;Consulter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>323d6ef2-b773-4e1e-b3d8-8bbc4e262dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:signedDocuments:1:consultDocument</value>
      <webElementGuid>cf5d891d-501b-4e15-b365-782354a1b9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>485a4c93-b689-4acd-8378-691c2959010c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/commun/save.gif</value>
      <webElementGuid>4e142266-9610-4a62-894c-0e5690bcf8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:signedDocuments:1:consultDocument</value>
      <webElementGuid>a968d257-60e2-495c-bc3d-9acf1e76f669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Consulter</value>
      <webElementGuid>858dcfae-941c-4366-b872-8e9d69b5a5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:signedDocuments:1:consultDocument&quot;)</value>
      <webElementGuid>d4a67f7a-9951-4ee5-b698-bfd62a534922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:signedDocuments:1:consultDocument']</value>
      <webElementGuid>7261409f-2489-4600-a006-5d77de78cf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='signatureDocumentsForm:signedDocuments:1:j_id139']/input</value>
      <webElementGuid>4e1f65dc-122b-4796-902e-1cf9d86d9267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>bdb32917-8ae7-472f-a872-4d290157ca57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signatureDocumentsForm:signedDocuments:1:consultDocument' and @type = 'image' and @src = '/images/commun/save.gif' and @name = 'signatureDocumentsForm:signedDocuments:1:consultDocument' and @alt = 'Consulter']</value>
      <webElementGuid>b1985c98-779a-4136-b39c-68dcbfc1903e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
