<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Non_signatureDocumentsFormj_id51</name>
   <tag></tag>
   <elementGuidId>4912ca43-dbb9-47c2-86ee-a6b539320b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:j_id51']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Signer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b36f7be0-da3b-43d6-afd1-ac97514d535c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>cd3e4920-a9a4-4e54-b8d6-b69716994e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:j_id51</value>
      <webElementGuid>602f14b8-dfe2-45af-8fdf-c0ddf76f39d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:j_id51</value>
      <webElementGuid>2caacb0d-3f39-4bea-9645-ff024af63e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('signatureDocumentsForm',event,{'similarityGroupingId':'signatureDocumentsForm:j_id51','oncomplete':function(request,event,data){updateSignatureVariables()},'parameters':{'signatureDocumentsForm:j_id51':'signatureDocumentsForm:j_id51'} } );return false;</value>
      <webElementGuid>2abba864-9771-4485-b7d2-44ad37aed989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Signer</value>
      <webElementGuid>98d4b486-805e-4337-8445-c441285c8cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74aac72a-98cc-45c3-8244-3990f7f4d5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>40c6c13a-7b40-42ee-ae02-abe72a7e9b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:j_id51&quot;)</value>
      <webElementGuid>690cfaec-ddb1-48d9-be29-e94bc173cd2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:j_id51']</value>
      <webElementGuid>03c440a7-f078-4a7e-bd00-c650e4d1d725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signatureDocumentsForm:j_id42']/div[3]/div[2]/div/input</value>
      <webElementGuid>225dccfc-0b6b-40bd-83c8-f9158bfa630c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9854f7bb-4410-48c7-b9b9-bc852d873945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signatureDocumentsForm:j_id51' and @name = 'signatureDocumentsForm:j_id51' and @type = 'button']</value>
      <webElementGuid>410fa141-fb7a-49d8-b172-fcfd83fc832a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
