<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CBCPF_29_11_2024.pdf_signatureDocumen_6e4843</name>
   <tag></tag>
   <elementGuidId>7364d1eb-b535-499e-be3c-baabdb672945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:signedDocuments:0:consultDocument']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;CBCPF_29_11_2024.pdf Consulter&quot;i] >> internal:attr=[alt=&quot;Consulter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac0daedb-6129-45d4-94a9-99cf2431e528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:signedDocuments:0:consultDocument</value>
      <webElementGuid>e55ddfdc-22e2-411d-95cd-aca07a7afdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>abc3713f-750f-4a78-9ad3-0c12cdd98ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/commun/save.gif</value>
      <webElementGuid>0c172de5-af81-418b-a257-c493d2d9c475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:signedDocuments:0:consultDocument</value>
      <webElementGuid>dd46b044-5505-4435-b53b-e0e6228b455f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Consulter</value>
      <webElementGuid>e00a06c5-9c36-43cb-8e43-10c071d21056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:signedDocuments:0:consultDocument&quot;)</value>
      <webElementGuid>f3524f59-dab8-40a1-8ddd-063e1502cbdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:signedDocuments:0:consultDocument']</value>
      <webElementGuid>12174353-035a-44ab-a72d-8aef87324e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='signatureDocumentsForm:signedDocuments:0:j_id139']/input</value>
      <webElementGuid>37cfeaef-01c6-4577-abea-b1870ee1e7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>217f4c43-f469-45fe-a107-651a3557bc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signatureDocumentsForm:signedDocuments:0:consultDocument' and @type = 'image' and @src = '/images/commun/save.gif' and @name = 'signatureDocumentsForm:signedDocuments:0:consultDocument' and @alt = 'Consulter']</value>
      <webElementGuid>2bce37bf-40d5-4954-9e32-1eec88fdeade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
