<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MODPP.pdf_signatureDocumentsFormj_id143</name>
   <tag></tag>
   <elementGuidId>09feaffe-ad9c-4baf-bf2d-9ea479be8eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;signatureDocumentsForm:j_id143&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='signatureDocumentsForm:j_id143']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Récépissé de dépôt et reçu de paiement&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ecf31fc-ae41-44e1-835b-57510d1d05b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2363701d-f591-4570-a4fe-062ea7eff52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:j_id143</value>
      <webElementGuid>14d9703d-4f5b-4113-b518-51d3b6709d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Récépissé de dépôt et reçu de paiement</value>
      <webElementGuid>9538a28c-8b72-458a-8e7c-e5f973151874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Récépissé de dépôt et reçu de paiement</value>
      <webElementGuid>42f3e2f0-9726-48aa-9543-d551ee178dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>84b81737-0239-45c5-93f1-1f485f8d4082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:j_id95&quot;)/div[@class=&quot;form-group text-center&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;btn btn-connexion&quot;]</value>
      <webElementGuid>c5b87cee-2839-4572-a08b-af3b16dcf99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='signatureDocumentsForm:j_id143']</value>
      <webElementGuid>98be3cbf-763d-4de5-9065-49666f8c5ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signatureDocumentsForm:j_id95']/div[2]/div[11]/input</value>
      <webElementGuid>f3b0dc74-32f9-4c7b-b9b1-f7860a87018b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>cc735c44-7dc1-47b4-b1f6-7ed8933b2fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'signatureDocumentsForm:j_id143' and @alt = 'Récépissé de dépôt et reçu de paiement']</value>
      <webElementGuid>d23c7f2d-92d7-46f1-bcaf-62cb24dbe97b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
