<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_signatureDocumentsFormselectedSig_0a84ea</name>
   <tag></tag>
   <elementGuidId>bca35957-53ba-4911-8862-c37e2a27b096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:selectedSignatureClasse:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Non&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>069eddfb-1b23-4867-bbe1-73cb855c62d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c09d5757-ddf5-4c9a-ba9f-5b0afc7bef21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:selectedSignatureClasse</value>
      <webElementGuid>bff5b5cc-0949-4a04-b015-fc1b544b9616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:selectedSignatureClasse:1</value>
      <webElementGuid>f52f26a4-1a0b-479d-8be3-132d6e22f78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>class1</value>
      <webElementGuid>2a3efe2f-faf3-4138-8e25-c28c43430caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateSelectedSignatureClasse(this.value);</value>
      <webElementGuid>eb898ce6-98a0-41a6-86f8-f696dd2a6f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>23761adb-4968-47d9-939c-80bbc773d4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:selectedSignatureClasse:1&quot;)</value>
      <webElementGuid>c9c7535a-c510-4363-9a0b-06a43ad24553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:selectedSignatureClasse:1']</value>
      <webElementGuid>413148f1-f362-4bc9-9e75-8ebbb3be93ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='signatureDocumentsForm:selectedSignatureClasse']/tbody/tr/td[2]/input</value>
      <webElementGuid>a44e6626-d78f-4880-a941-cc8686b54659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7b0477dc-7374-416c-b738-bec2a3e3222f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'signatureDocumentsForm:selectedSignatureClasse' and @id = 'signatureDocumentsForm:selectedSignatureClasse:1']</value>
      <webElementGuid>609f98c3-97ee-48ed-aca1-6b8f17d84a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
