<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MODPP.pdf_signatureDocumentsFormsigne_66bfeb</name>
   <tag></tag>
   <elementGuidId>b2c2de74-131a-4c99-916a-65c4a249b44e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:signedDocuments:2:consultDocument']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;MODPP.pdf Consulter&quot;i] >> internal:attr=[alt=&quot;Consulter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6d3a178-2697-421b-98a8-64bc90ae76da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:signedDocuments:2:consultDocument</value>
      <webElementGuid>a75e893f-c6d7-45c0-8488-5fc2566b0d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ddb78a3c-352c-4823-aa3f-d95c992a7dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/commun/save.gif</value>
      <webElementGuid>835a9bdf-72b5-4fe7-ac21-cd2c1745abf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:signedDocuments:2:consultDocument</value>
      <webElementGuid>1f86571c-b0f9-488a-8c79-eebdb23195eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Consulter</value>
      <webElementGuid>1669dc3f-7879-4df9-a194-1c5205cdb859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:signedDocuments:2:consultDocument&quot;)</value>
      <webElementGuid>e224dcad-3cd7-4dbf-b884-f7f3e3284697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:signedDocuments:2:consultDocument']</value>
      <webElementGuid>54dea2b3-612e-454a-90b0-d4d14d679328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='signatureDocumentsForm:signedDocuments:2:j_id139']/input</value>
      <webElementGuid>cd07cf4d-f095-4b79-80f2-446fb3b75887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>ba245808-b284-494c-9dcd-f37c66a944dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signatureDocumentsForm:signedDocuments:2:consultDocument' and @type = 'image' and @src = '/images/commun/save.gif' and @name = 'signatureDocumentsForm:signedDocuments:2:consultDocument' and @alt = 'Consulter']</value>
      <webElementGuid>8f795caa-034c-4b2b-98cf-7984db592253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
