<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>7734818f-5515-473d-b6c6-9600b58c03e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rich-calendar-editor-btn.rich-calendar-editor-tool-over</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;dossierFormm\:dateNaissanceDateEditorLayoutTR&quot;] >> internal:text=&quot;&lt;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b5a95d5-0230-4c34-860a-a22218155c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-editor-btn rich-calendar-editor-tool-over</value>
      <webElementGuid>40f76d5a-0ed0-415c-90cf-1a695a7c3be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.className='rich-calendar-editor-btn rich-calendar-editor-tool-over';</value>
      <webElementGuid>dc2ed0c4-c46a-4e45-ada3-9fc699808192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.className='rich-calendar-editor-btn';</value>
      <webElementGuid>fe5178bd-8a64-4f3f-85ab-6ab6241693e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>this.className='rich-calendar-editor-btn rich-calendar-editor-tool-press';</value>
      <webElementGuid>6b93e966-074a-44c5-a31c-bebc8df67a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>this.className='rich-calendar-editor-btn rich-calendar-editor-tool-over';</value>
      <webElementGuid>876b2f93-0164-4af3-8d09-bc6e19c28983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('dossierFormm:dateNaissance').component.scrollEditorYear(-1);</value>
      <webElementGuid>cb615c14-9d15-4be8-bc4d-bef921b693b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;</value>
      <webElementGuid>857df14f-7b9f-4644-bd9c-fc4f18a71300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierFormm:dateNaissanceDateEditorLayoutTR&quot;)/td[3]/div[@class=&quot;rich-calendar-editor-btn rich-calendar-editor-tool-over&quot;]</value>
      <webElementGuid>682c6df1-0f01-456c-8e51-c21f89f5906a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='']</value>
      <webElementGuid>0213946f-e1f4-404b-9abf-7806867347f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dossierFormm:dateNaissanceDateEditorLayoutTR']/td[3]/div</value>
      <webElementGuid>27f9c49f-2cb6-485c-bdeb-22e32a20a899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='juil.'])[1]/following::div[1]</value>
      <webElementGuid>0b01783e-54fe-4b1b-ae47-5094b26b6e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='janv.'])[1]/following::div[2]</value>
      <webElementGuid>d3fe2ac8-4301-4cbf-a4b3-cccbee7775b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[3]/preceding::div[1]</value>
      <webElementGuid>2944a70e-78b9-4077-a5eb-5ff2ec749801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='févr.'])[1]/preceding::div[2]</value>
      <webElementGuid>49163a50-2e2b-4e15-92f8-12885660c66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[3]/div</value>
      <webElementGuid>c8bab129-c559-4e00-bfdd-9e409d3fe55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '&lt;' or . = '&lt;')]</value>
      <webElementGuid>0055fc32-3d7f-4b58-b444-81546f334916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
