<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OK</name>
   <tag></tag>
   <elementGuidId>c01e73f3-abec-463a-9317-1ada03e054c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dossierForm:dateNaissFondPouvDateEditorButtonOk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;dossierForm\:dateNaissFondPouvDateEditorButtonOk&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>866bdb33-d8a7-4cea-a4cc-84d4fa1b7eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:dateNaissFondPouvDateEditorButtonOk</value>
      <webElementGuid>97bf0517-efdd-4c27-8721-f3d3c9ab70e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-time-btn</value>
      <webElementGuid>23235e92-e7f2-49c3-9f0a-73ba89e0e2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>Element.addClassName(this, 'rich-calendar-time-btn-press');</value>
      <webElementGuid>637aad42-c6fd-413b-ba21-81d5e54b38df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>Element.removeClassName(this, 'rich-calendar-time-btn-press');</value>
      <webElementGuid>5937a51d-faa9-4628-aea6-e34eeab55674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>Element.removeClassName(this, 'rich-calendar-time-btn-press');</value>
      <webElementGuid>09558572-9308-4fe3-aba6-54654c789814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('dossierForm:dateNaissFondPouv').component.hideDateEditor(true);</value>
      <webElementGuid>5a401875-2a78-4895-85c8-d6ea60fb5ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>91964324-d876-424e-aceb-06a1e31521d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:dateNaissFondPouvDateEditorButtonOk&quot;)</value>
      <webElementGuid>3a6dc671-f3f6-46cc-98cb-d506fcaafcdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:dateNaissFondPouvDateEditorButtonOk']</value>
      <webElementGuid>2ed33245-d433-4db4-9865-ff5e572d22e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierForm:dateNaissFondPouvDateEditorLayout']/tbody/tr[7]/td/div</value>
      <webElementGuid>1a405c4c-d99f-4d7c-99a6-eacabe1a2700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='déc.'])[1]/following::div[3]</value>
      <webElementGuid>602fe675-f769-42d3-9e42-1eeb844665f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='juin'])[1]/following::div[4]</value>
      <webElementGuid>8e25e8c2-884d-4874-afba-7fd0c9311922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>53661cd9-cf8e-4d9b-a76a-a6ee434594b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div</value>
      <webElementGuid>04a4153a-ab18-445b-8f63-353624d85f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dossierForm:dateNaissFondPouvDateEditorButtonOk' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>3273a7e7-0767-4e71-bbdd-46983326cf47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
