<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Today</name>
   <tag></tag>
   <elementGuidId>874f7aaa-0d61-49d8-9a77-a1c0d9163e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rich-calendar-tool-btn.rich-calendar-tool-btn-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;Richfaces.getComponent('calendar',this).today();return true;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Today&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fccd61a-6999-4e73-bc5d-ce8dddee186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Richfaces.getComponent('calendar',this).today();return true;</value>
      <webElementGuid>13d8e3c6-dfec-473c-ab0a-e6b3ad523774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-tool-btn rich-calendar-tool-btn-hover</value>
      <webElementGuid>75425a81-99f7-4114-a353-40bbdbfc91fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.className='rich-calendar-tool-btn rich-calendar-tool-btn-hover'</value>
      <webElementGuid>82f21150-1c23-4ac0-9a17-5a25b0b6d658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.className='rich-calendar-tool-btn'</value>
      <webElementGuid>cf24c236-0009-4dec-89b4-c4ee1f7b1865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>this.className='rich-calendar-tool-btn rich-calendar-tool-btn-hover rich-calendar-tool-btn-press'</value>
      <webElementGuid>72595bb8-3beb-4752-a656-61b8b3aa91cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>this.className='rich-calendar-tool-btn rich-calendar-tool-btn-hover'</value>
      <webElementGuid>3a29a882-19cd-49d2-8426-0fa61d2b2587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>784d0468-333e-460b-8dc4-34d31b336e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierFormm:dateValPieceIdFooter&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;rich-calendar-toolfooter&quot;]/div[@class=&quot;rich-calendar-tool-btn rich-calendar-tool-btn-hover&quot;]</value>
      <webElementGuid>3546201b-882d-4c9d-9e34-bd4b5e383e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;Richfaces.getComponent('calendar',this).today();return true;&quot;]</value>
      <webElementGuid>75be934b-b8ef-40b5-bc47-e530c13f18d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierFormm:dateValPieceIdFooter']/table/tbody/tr/td[5]/div</value>
      <webElementGuid>b5161c4c-cb87-4329-8778-761aa8f02b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dim.'])[1]/following::div[1]</value>
      <webElementGuid>e47ef4fc-670a-4390-928c-7d7ea6546c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sam.'])[1]/following::div[1]</value>
      <webElementGuid>aba7b38e-58dc-4ccb-895d-ca77c3517e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lieu de délivrance'])[1]/preceding::div[2]</value>
      <webElementGuid>f431c466-b441-4a53-acb0-39801564856e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>b23daa29-c673-45f9-af46-ed4e01f1f7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/table/tbody/tr/td[5]/div</value>
      <webElementGuid>eda24b2f-079a-4425-b74d-ca8de3c12647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>aafe4e71-cf11-4d13-8bf9-7e5ce6f24f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
