<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1982</name>
   <tag></tag>
   <elementGuidId>2315ee36-8f09-4b03-9fa2-c65f54ce6a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dossierForm:dateNaissFondPouvDateEditorLayoutY2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1982&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96a72125-d1af-440f-bb2b-6b9f32b5b007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:dateNaissFondPouvDateEditorLayoutY2</value>
      <webElementGuid>e0b44054-12ef-4d02-a971-32d2dbba37b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-editor-btn rich-calendar-editor-btn-over</value>
      <webElementGuid>993a0da4-92c7-478e-b7b4-bf0b5fa2d75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>Element.addClassName(this, 'rich-calendar-editor-btn-over');</value>
      <webElementGuid>22dcd3fa-d531-4dbc-8c9a-fa83715dcbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>Element.removeClassName(this,'rich-calendar-editor-btn-over');</value>
      <webElementGuid>3afb9c5e-f62e-4b76-9590-4b397fdb2685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('dossierForm:dateNaissFondPouv').component.dateEditorSelectYear(2);</value>
      <webElementGuid>6bd1ee98-0ba2-4004-baa6-b212fcc4c3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1982</value>
      <webElementGuid>ac635615-f3c3-4df1-8da4-48673ed81a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:dateNaissFondPouvDateEditorLayoutY2&quot;)</value>
      <webElementGuid>4fffc687-aaf7-4a29-a595-91e6a4e719b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:dateNaissFondPouvDateEditorLayoutY2']</value>
      <webElementGuid>e7f0929a-8ad6-48f0-8f23-bcd931355a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierForm:dateNaissFondPouvDateEditorLayout']/tbody/tr[4]/td[3]/div</value>
      <webElementGuid>4a20e1ee-377a-4e2d-ad38-64aa6405f9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oct.'])[1]/following::div[1]</value>
      <webElementGuid>fda17b7e-bde2-494c-8ca4-467fe5e2373b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='avr.'])[1]/following::div[2]</value>
      <webElementGuid>bf35bc3b-dce3-46e1-89f0-b301adf71e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mai'])[1]/preceding::div[2]</value>
      <webElementGuid>e3e8ca28-0611-452b-bf22-d8f960cfaa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nov.'])[1]/preceding::div[3]</value>
      <webElementGuid>4af96bb0-3df0-4c2b-b3a8-a9d3dcbdb889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1982']/parent::*</value>
      <webElementGuid>6fa21b74-3c1c-4559-ae33-cbda3bac52ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div</value>
      <webElementGuid>e4860b9c-cd1d-4403-9011-cdc664103f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dossierForm:dateNaissFondPouvDateEditorLayoutY2' and (text() = '1982' or . = '1982')]</value>
      <webElementGuid>160dfbfe-91dd-4bd4-a650-14530c522738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
