<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dossierFormmdateDebContratInputDate</name>
   <tag></tag>
   <elementGuidId>5d4689b5-0e52-4efd-b69e-a507a0ee8d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierFormm:dateDebContratInputDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;dossierFormm\:dateDebContratInputDate&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d26b98d4-5630-492a-b352-e95b548074d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input</value>
      <webElementGuid>52850a2b-1c0d-40af-bbe7-a1ec49c977fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierFormm:dateDebContratInputDate</value>
      <webElementGuid>3777ccd6-003c-4583-90db-77d361b9d498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierFormm:dateDebContratInputDate</value>
      <webElementGuid>75b3404e-fd08-4767-b59d-6c178021a51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eef18741-c5cb-4427-a84a-3a74ea594876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c81111f8-1739-4204-be96-55b4b36517e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierFormm:dateDebContratInputDate&quot;)</value>
      <webElementGuid>16f55535-2916-4e33-9336-3c95d2a9c43c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierFormm:dateDebContratInputDate']</value>
      <webElementGuid>26725cd9-f357-495e-a7b3-0bedaee3c546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dossierFormm:dateDebContratPopup']/input</value>
      <webElementGuid>20be222f-b9e0-49ef-9e9e-dcc531904e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/span/input</value>
      <webElementGuid>2b433c53-f0f5-41a4-b888-cdfe4ccf2dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierFormm:dateDebContratInputDate' and @name = 'dossierFormm:dateDebContratInputDate' and @type = 'text']</value>
      <webElementGuid>3593c50d-c603-459e-b613-a11eb435199f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
