<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ajouter activit_dossierFormj_id58</name>
   <tag></tag>
   <elementGuidId>90809c8e-b54d-4fde-8aec-bf293440248d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:j_id58']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ajouter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3b35ca7-93e7-41f1-9a42-fedc7fa95cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addActivite</value>
      <webElementGuid>b2f91755-52ef-48bd-86e4-901b46624bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:j_id58</value>
      <webElementGuid>ac66ad2a-f629-485d-b0df-69a5251c7a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:j_id58</value>
      <webElementGuid>ba3c083b-4ff9-49ed-a9d3-22fc1928cc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id58','oncomplete':function(request,event,data){document.getElementById('creerViewActivitePrimaire:panelAjouterActivitePrimaire').component.show()},'parameters':{'dossierForm:j_id58':'dossierForm:j_id58'} } );return false;</value>
      <webElementGuid>6f8c176f-4f5a-42c9-926d-ecc61271f783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ajouter</value>
      <webElementGuid>d0fe57b7-3079-49b5-a90e-a6e5e33ffeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3b37ad1b-f32c-4025-8552-1c6b322c1494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images-new/svg/add.svg</value>
      <webElementGuid>75f66abb-1e03-4f43-98cb-5c1e706ef5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ajouter</value>
      <webElementGuid>03e12e24-873e-4091-b44f-865f2fda0d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>df5bd059-d557-492c-b686-ad1efe93bd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:j_id58&quot;)</value>
      <webElementGuid>29826230-332a-4e13-9254-42ba942829ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:j_id58']</value>
      <webElementGuid>76d5a28e-294d-48f5-aa6e-50ac28eaf407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:panelGridActivitiesP_body']/input</value>
      <webElementGuid>e7f12329-e597-48ed-b7ba-2596feadaadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>3d3e38cc-bdaf-41ed-b90b-9688a31a3caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:j_id58' and @name = 'dossierForm:j_id58' and @type = 'image' and @src = '/images-new/svg/add.svg' and @alt = 'Ajouter']</value>
      <webElementGuid>16fabe4b-9114-4008-bb2a-db834d2a9fbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
