<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dossierFormnombreSalaries</name>
   <tag></tag>
   <elementGuidId>18301555-af8a-4077-84e5-d7773b59fb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:nombreSalaries']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nombre de salariés*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89324bf5-2cec-47dd-9cc7-fee411d47ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:nombreSalaries</value>
      <webElementGuid>ce83a030-760d-4a2d-9b50-3fcf4a985e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>128b92b1-f42f-45d7-82a5-6c2a1e0fbefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:nombreSalaries</value>
      <webElementGuid>da6b0685-36b9-494c-b818-b0f778faec24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>284afee3-bcf3-4238-b7fc-e75cca75c3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4c8a0940-bf2d-4f4c-a45d-c8659d6c229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id54','parameters':{'dossierForm:j_id54':'dossierForm:j_id54'} } )</value>
      <webElementGuid>b7fbc6ce-386d-4630-8e94-c0af57dd694b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKey(event)</value>
      <webElementGuid>c56d54ec-92a0-4428-b476-cb3f6e694818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b3218258-80a1-4eea-ada9-a36f43842a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:nombreSalaries&quot;)</value>
      <webElementGuid>95d2bf1d-cd46-4952-859e-e135000bffb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:nombreSalaries']</value>
      <webElementGuid>e841767f-fa3c-4afa-b709-43e507ccd865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:panelCnss_body']/div/div/input</value>
      <webElementGuid>0f7c11a4-d685-4526-9d95-5928c5d5e430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>eed5b953-7962-43c1-8ad2-e9921dfc3cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:nombreSalaries' and @type = 'text' and @name = 'dossierForm:nombreSalaries']</value>
      <webElementGuid>a4177722-6c21-4d44-8cc1-6f099cd03be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
