<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TRANSPORTS ET ENTREPOSAGE_creerViewAc_dfce60</name>
   <tag></tag>
   <elementGuidId>071ba116-af89-41c8-984c-f24095e666e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Valider&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8edc85c-a1e2-4212-a207-c07ab68feb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>b89bbed2-6f25-4a0f-8573-8a66caaaee43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire</value>
      <webElementGuid>3fa498c1-065b-4a26-a56e-5856e87b52b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire</value>
      <webElementGuid>05d9e6c0-0056-4a54-a80f-33d99cd19a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('creerViewActivitePrimaire:formActivitePrimaire',event,{'similarityGroupingId':'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire','oncomplete':function(request,event,data){{document.getElementById('creerViewActivitePrimaire:panelAjouterActivitePrimaire').component.hide();}},'parameters':{'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire':'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire','ajaxSingle':'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire'} } );return false;</value>
      <webElementGuid>123f0c28-d23e-4976-8683-0e902ffd9fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>8876d74e-bc90-4b66-9e75-c2f9b23bf43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be50b0e8-ec80-4c67-8ad7-7814eca3ee83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire&quot;)</value>
      <webElementGuid>7b42b5b7-a001-447b-a5d6-d80c178131ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire']</value>
      <webElementGuid>a8dadd26-40bb-4f11-9118-0e84f4109f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='creerViewActivitePrimaire:formActivitePrimaire:j_id232']/input</value>
      <webElementGuid>54798256-7de1-48f9-a7d4-d0d00f1287c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/table/tbody/tr[2]/td/span/form/div[2]/span/input</value>
      <webElementGuid>ed9b131d-e618-4aa3-8f5b-284d2ced4618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire' and @name = 'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire' and @type = 'button']</value>
      <webElementGuid>ec93f4f4-774b-4d25-8928-054c4cbc81ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
