<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date de naissance_dossierFormdateNais_f2bf75</name>
   <tag></tag>
   <elementGuidId>fb1c5a6e-7c16-477a-96c1-325612766b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:dateNaissFondPouvInputDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;dossierForm\:dateNaissFondPouvInputDate&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc821536-d20e-46f9-960e-21451a9b0c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input </value>
      <webElementGuid>cc41128b-de12-4568-8960-9e8d181da3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:dateNaissFondPouvInputDate</value>
      <webElementGuid>10eb8409-967a-44f7-9311-abd7e70ea3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:dateNaissFondPouvInputDate</value>
      <webElementGuid>3a3e8149-ac6d-4b73-9fd8-64d438a32c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10a643b7-34f4-4e89-979b-31fc1e74e579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>192dc8a5-b9ff-4d7b-a337-a6aa8a118ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>497bc5d3-9d28-48f0-a143-22cc6344b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:dateNaissFondPouvInputDate&quot;)</value>
      <webElementGuid>33c49a30-006a-4252-afc6-6834e9a7c1e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:dateNaissFondPouvInputDate']</value>
      <webElementGuid>2bbccb2d-84c3-4c24-bbef-320d0231c62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dossierForm:dateNaissFondPouvPopup']/input</value>
      <webElementGuid>24500b9c-aead-4d94-ad2f-324353f18cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>299e1698-21d6-4a5d-a5e9-c4ddf4538bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:dateNaissFondPouvInputDate' and @name = 'dossierForm:dateNaissFondPouvInputDate' and @type = 'text']</value>
      <webElementGuid>6eae89b3-b8af-44c6-a062-1522d1f6ead2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
