<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agadir Ida Ou TananeAl HaouzAl Hocei_033512_1</name>
   <tag></tag>
   <elementGuidId>65a9c6e9-de45-497d-ad4a-faeee1baf05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierForm:refProvincefd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Province/Préfecture&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d33645a0-0bcd-4687-9709-9bd9b27576ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:refProvincefd</value>
      <webElementGuid>e47761e8-6270-413a-81c2-9c739b7faf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:refProvincefd</value>
      <webElementGuid>a05fb90f-d085-4e52-aac7-fe3540b9c600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b90236ed-4c4c-484d-8f10-be58215144e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>964f0c60-a8c8-485b-b0c7-e0b22d6153fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id391','parameters':{'dossierForm:j_id391':'dossierForm:j_id391'} } )</value>
      <webElementGuid>5b073d66-fd8e-49a2-ae23-415682b2f686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agadir Ida Ou TananeAl HaouzAl HoceimaAousserdAssa-ZagAzilalBenslimaneBerkaneBerrechidBoujdourBoulemaneBéni MellalCasablancaChefchaouenChichaouaChtouka- Ait BahaDriouchEl HajebEl JadidaEl Kelâa des  SraghnaEL YoussoufiaErrachidiaEs-SemaraEssaouiraFahs-AnjraFiguigFquih Ben SalahFèsGuelmimGuercifIfraneInezgane Ait MelloulJeradaKhouribgaKhémissetKhénifraKénitraLaayouneLaracheMarrakechMdiq - FnidqMediounaMeknèsMideltMohammadiaMoulay YacoubNadorNouaceurOuarzazateOued-Ed-DahabOuezzaneOujda-AngadRabatRehamnaSafiSaléSefrouSettatSidi BennourSidi IfniSidi KacemSidi SlimaneSkhirate- TémaraTan-TanTanger -AssilahTaounateTaourirtTarfayaTaroudanntTataTazaTinghirTiznitTétouanZagora</value>
      <webElementGuid>64ceb44a-1d8a-4cc5-bbd5-efb5f7d0af19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:refProvincefd&quot;)</value>
      <webElementGuid>c3cba80a-d7b3-410b-94c5-415577bd14f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierForm:refProvincefd']</value>
      <webElementGuid>065340d7-eebd-41c4-9a85-b626b6556e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ville']/div/select</value>
      <webElementGuid>7044eb5b-0bd8-4e9b-8a0c-026ba12ab313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province/Préfecture'])[1]/following::select[1]</value>
      <webElementGuid>183d8369-7980-4e9b-a389-5bfbef9b939e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pays'])[1]/following::select[2]</value>
      <webElementGuid>894e062c-d01b-426e-9aa4-1fe027b0c312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commune'])[1]/preceding::select[1]</value>
      <webElementGuid>53f459c7-0ca6-4f2b-84f7-27187b08d76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avant de commencer'])[1]/preceding::select[2]</value>
      <webElementGuid>85c5fb76-b784-4579-ab24-456738031836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/select</value>
      <webElementGuid>b5163c18-693e-4a49-9beb-cb96b844cd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierForm:refProvincefd' and @name = 'dossierForm:refProvincefd' and (text() = 'Agadir Ida Ou TananeAl HaouzAl HoceimaAousserdAssa-ZagAzilalBenslimaneBerkaneBerrechidBoujdourBoulemaneBéni MellalCasablancaChefchaouenChichaouaChtouka- Ait BahaDriouchEl HajebEl JadidaEl Kelâa des  SraghnaEL YoussoufiaErrachidiaEs-SemaraEssaouiraFahs-AnjraFiguigFquih Ben SalahFèsGuelmimGuercifIfraneInezgane Ait MelloulJeradaKhouribgaKhémissetKhénifraKénitraLaayouneLaracheMarrakechMdiq - FnidqMediounaMeknèsMideltMohammadiaMoulay YacoubNadorNouaceurOuarzazateOued-Ed-DahabOuezzaneOujda-AngadRabatRehamnaSafiSaléSefrouSettatSidi BennourSidi IfniSidi KacemSidi SlimaneSkhirate- TémaraTan-TanTanger -AssilahTaounateTaourirtTarfayaTaroudanntTataTazaTinghirTiznitTétouanZagora' or . = 'Agadir Ida Ou TananeAl HaouzAl HoceimaAousserdAssa-ZagAzilalBenslimaneBerkaneBerrechidBoujdourBoulemaneBéni MellalCasablancaChefchaouenChichaouaChtouka- Ait BahaDriouchEl HajebEl JadidaEl Kelâa des  SraghnaEL YoussoufiaErrachidiaEs-SemaraEssaouiraFahs-AnjraFiguigFquih Ben SalahFèsGuelmimGuercifIfraneInezgane Ait MelloulJeradaKhouribgaKhémissetKhénifraKénitraLaayouneLaracheMarrakechMdiq - FnidqMediounaMeknèsMideltMohammadiaMoulay YacoubNadorNouaceurOuarzazateOued-Ed-DahabOuezzaneOujda-AngadRabatRehamnaSafiSaléSefrouSettatSidi BennourSidi IfniSidi KacemSidi SlimaneSkhirate- TémaraTan-TanTanger -AssilahTaounateTaourirtTarfayaTaroudanntTataTazaTinghirTiznitTétouanZagora')]</value>
      <webElementGuid>85b198be-0505-4186-b39f-bb06b60d4f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
