<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Al-FidaAnfaAssoukhour AssawdaAn-Choc_d721e0_1</name>
   <tag></tag>
   <elementGuidId>49099d78-0bea-4d1b-a694-05608c622bd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierForm:refCommuneFondPouv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Commune&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7e63fbf-b630-48fd-9c37-ca7006503331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:refCommuneFondPouv</value>
      <webElementGuid>153089df-dd04-4061-903d-5ba307341367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:refCommuneFondPouv</value>
      <webElementGuid>84cd31bc-aff9-4bc6-9a2e-ffa7f6d0fb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-8</value>
      <webElementGuid>ea64fcba-26de-4b5a-b6e3-12e697a14c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c90b87f0-82cc-4de0-ac26-5f21905b97ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane</value>
      <webElementGuid>02d80490-8578-4c9f-af08-b5bbdd6f8b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:refCommuneFondPouv&quot;)</value>
      <webElementGuid>4f3ac541-9653-4ae1-a9ed-e26246e29802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierForm:refCommuneFondPouv']</value>
      <webElementGuid>92438437-3498-4286-b49d-bab35fc544db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:marocainCLabel']/div/select</value>
      <webElementGuid>25b00b73-45c2-4a83-92c7-589b0f1c157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commune'])[1]/following::select[1]</value>
      <webElementGuid>321b84ea-81d9-4638-b39c-1fba305d4f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province/Préfecture'])[1]/following::select[2]</value>
      <webElementGuid>10315428-9743-488a-acd3-c09e82d15001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avant de commencer'])[1]/preceding::select[1]</value>
      <webElementGuid>2a4cab9f-6a98-4892-93e4-e1c5c3d0765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fondé de pouvoir (le cas échéant)'])[2]/preceding::select[1]</value>
      <webElementGuid>c5484888-570f-4a64-9880-ca4fb14943c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>2cff5bf2-4812-44e6-a604-e9323d30b430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierForm:refCommuneFondPouv' and @name = 'dossierForm:refCommuneFondPouv' and (text() = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane' or . = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane')]</value>
      <webElementGuid>26ec67fe-af0f-4955-a85d-3fafc84dd5ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
