<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agdal RiyadHassanSouissiTouargaYacou_2c619b</name>
   <tag></tag>
   <elementGuidId>63b727e3-2771-4d2b-9260-dd5918883b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierFormm:refCommune']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Commune*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a059986-ced9-4026-bf11-15ed863c50fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
      <webElementGuid>36024c66-c52b-40bc-b3c9-0603ce17dbec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierFormm:refCommune</value>
      <webElementGuid>6182bf37-d7fd-472f-b345-eadc76bd65ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierFormm:refCommune</value>
      <webElementGuid>4b964321-28e3-41e1-8026-064840475cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c17c659d-95bb-4273-a2fb-717d327ebbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>94e2b9d9-9a06-4735-9303-646d4504d9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierFormm',event,{'similarityGroupingId':'dossierFormm:j_id239','parameters':{'dossierFormm:j_id239':'dossierFormm:j_id239'} } )</value>
      <webElementGuid>85ad3c5b-fe57-43d3-b57f-2abfb55b0c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agdal RiyadHassanSouissiTouargaYacoub El Mansour</value>
      <webElementGuid>760966b4-d9e9-4b8d-9055-97b0f0f99d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierFormm:refCommune&quot;)</value>
      <webElementGuid>fdac210b-62de-4151-8be7-d77c7e78c2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierFormm:refCommune']</value>
      <webElementGuid>9aa5f5fc-57e5-4834-bd18-4b02f001e7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierFormm:j_id216_body']/div[4]/div/select</value>
      <webElementGuid>98600b19-5e90-4b6b-b137-8abf7d0d9c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::select[1]</value>
      <webElementGuid>95983de2-477c-4eed-8437-07c575824205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tribunal'])[1]/preceding::select[1]</value>
      <webElementGuid>eec383b4-e11e-4647-b45d-1128018a7f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code postal'])[1]/preceding::select[1]</value>
      <webElementGuid>b544a566-cb5d-40e2-9131-a4bf5f44f6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>83674fac-2f5a-4ff1-bc16-7359acae0fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierFormm:refCommune' and @name = 'dossierFormm:refCommune' and (text() = 'Agdal RiyadHassanSouissiTouargaYacoub El Mansour' or . = 'Agdal RiyadHassanSouissiTouargaYacoub El Mansour')]</value>
      <webElementGuid>63c83b7f-6b39-400d-b86b-9b17de4340ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
