<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Al-FidaAnfaAssoukhour AssawdaAn-Choc_d721e0</name>
   <tag></tag>
   <elementGuidId>dcedc932-afcf-42c7-8e81-ae72b4acfb82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierFormm:refCommunePoste']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Commune *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e12ed64-7a20-4c96-b089-9434411698bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierFormm:refCommunePoste</value>
      <webElementGuid>3e7861ca-3793-49ac-9b3c-ff74648c728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierFormm:refCommunePoste</value>
      <webElementGuid>02e1efed-dcdb-4402-9cbb-dd13bab9b3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-8</value>
      <webElementGuid>ecf917f3-63f7-44bd-9e61-7c262d52b9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2916cafc-bd24-4f01-9699-0fb177c69673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane</value>
      <webElementGuid>49292f6f-76f3-449a-84f9-4fee151a7af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierFormm:refCommunePoste&quot;)</value>
      <webElementGuid>f82e5648-987e-47a9-82ca-d3972fafc758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierFormm:refCommunePoste']</value>
      <webElementGuid>9020b6f4-321c-46cb-8ed4-37a84d1e2eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierFormm:refCommuneEtablissementPanel']/tbody/tr/td/select</value>
      <webElementGuid>1c43d170-cb08-49d6-afc1-971ce8782520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>e6ff5684-e3dd-4f3f-994b-adbb3d251a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/preceding::select[1]</value>
      <webElementGuid>40cb4b8d-9e9d-4569-a05d-71098083a187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/select</value>
      <webElementGuid>103a6df3-4b52-4398-873d-04ec01907e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierFormm:refCommunePoste' and @name = 'dossierFormm:refCommunePoste' and (text() = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane' or . = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane')]</value>
      <webElementGuid>b7af97ae-6b46-472f-b0bb-25a7fbd9bd4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
