<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Confirmer l, , acceptation des_3f0939</name>
   <tag></tag>
   <elementGuidId>cccfc53a-74c7-4c6a-b633-4befca350154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ml</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ml']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0f37220-02e2-4478-a1eb-47354952cdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e36973e-f57e-4ec8-9ec8-a7a3e99b8302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>choix1cmiconfirm_cgu</value>
      <webElementGuid>d5dabef1-250d-4ef1-94c2-22bb929d7c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ml</value>
      <webElementGuid>fa263fb7-2c0e-4ea3-9ab5-f8b37d34615b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ml&quot;)</value>
      <webElementGuid>aca8a6b9-6334-4e33-be5b-13847a28959a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ml']</value>
      <webElementGuid>f0d0b696-f7d9-4773-a693-7da38b495856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mtcw']/div/div/div[3]/div/div/div[2]/div[7]/input</value>
      <webElementGuid>25b97034-862e-4329-a022-ce43c80e4821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>ca8a0b41-f40f-410d-9d65-98acfba33744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'choix1cmiconfirm_cgu' and @id = 'ml']</value>
      <webElementGuid>a6c48233-49a7-405f-b6f4-bf9e2d56ce41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
