<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numro de carte de paiement_pan</name>
   <tag></tag>
   <elementGuidId>97857d10-86aa-4ed8-8edc-dc9c4d3a409d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89c68ceb-ea4e-4c43-8482-df54260bdeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>de1eb948-6f25-4738-9c88-037b65fd65f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9\-]{13,19}</value>
      <webElementGuid>abf47d65-ab75-4bcb-9708-05ca0ca20f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e129e10-e013-4ce8-9ed8-f252e36eef78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>getInstalmentTableIfParamNotSent('onJs5TvlEyrFWVplJ/7KKmXtuTdJEiOHsViO+kcJMUqbMSyOqT1U60rQnsESvq0tr0/6MXRPWRyib9v7EgmYjA==')</value>
      <webElementGuid>52cdc06a-8e53-49d2-ac41-f35008559e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d22ac4af-9f2d-4710-bf30-2c1bc536ae6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pan</value>
      <webElementGuid>6cc1de4f-1835-4867-8e26-b7396a9d95bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>b7a18604-e555-4277-984f-80a19c686db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pan</value>
      <webElementGuid>a7d6b30a-8d80-45ba-bdfa-c2e840907ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Numéro de carte de paiement</value>
      <webElementGuid>22cccd85-b290-4e1e-8a6c-e4d870fbde8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pan&quot;)</value>
      <webElementGuid>51d65d08-7644-482c-99a5-00e11e3f7931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pan']</value>
      <webElementGuid>cbe76745-f0db-4a78-866a-c75cfb1630c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mtcw']/div/div/div[3]/div/div/div[2]/div[4]/input</value>
      <webElementGuid>4f33f125-cb77-4018-abef-76544cd9c453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>65ad3247-5f5e-42d0-8a0a-f1ded5677fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'pan' and @id = 'pan' and @placeholder = 'Numéro de carte de paiement']</value>
      <webElementGuid>9fb27018-f756-4c7f-9c7d-05a74ff48df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
