<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code de vrification_cv2</name>
   <tag></tag>
   <elementGuidId>e1d82d59-30ae-4052-97be-5e92131155fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#code-verification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='code-verification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9898d186-84bb-4199-99ba-9c6b33274467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>code-verification</value>
      <webElementGuid>6d41bb91-716f-4e75-a0e3-8413f58c2277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9\-]{3,}</value>
      <webElementGuid>c8bcb553-9524-4133-9b2e-5c19d977312a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cv2</value>
      <webElementGuid>aff99c04-96af-49dc-bf13-e3f62f5ffd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8230a881-122e-426e-80e4-4c9bee57c373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>47536b7b-9127-4d0a-af03-64b89e53bb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ffb38073-56a5-4f0d-92da-eb710698890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b8e464d9-7852-4551-9c38-a6883f85b3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code-verification&quot;)</value>
      <webElementGuid>8b3471d6-5cb4-4af7-8bfc-583ded5ea4ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='code-verification']</value>
      <webElementGuid>f36edcf2-fdce-4ab8-99de-fa6f453f6652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zonecvv']/table/tbody/tr/td/input</value>
      <webElementGuid>1c9f363a-661c-4be2-952e-01858d2de48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>ff9d6b90-94d2-4bc7-965a-40d300a23477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'code-verification' and @name = 'cv2' and @type = 'tel']</value>
      <webElementGuid>bb991fa9-7378-43cc-a005-b868226490b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
