<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nom du porteur de la carte_cardHolderName</name>
   <tag></tag>
   <elementGuidId>74189e80-f860-41b5-86e3-137133356680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardHolderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardHolderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49e545ca-a18e-4e45-a1b2-fdc018e93e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4539e7f6-3e42-4967-a9aa-0522d992c208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^a-zA-Z ]/g, '')</value>
      <webElementGuid>1b74e524-25ef-4347-ab98-0d4e71eb9a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>63e487e4-c426-4e93-b3d9-3bd711c5ed00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardHolderName</value>
      <webElementGuid>6908954c-4605-4e93-a647-ba1cfdd01cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>47f09d62-fd47-409d-b144-2dc0f3261c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardHolderName</value>
      <webElementGuid>a0043cf9-c690-4eb9-8693-12049ef67cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nom du porteur de la carte</value>
      <webElementGuid>b91f5cf4-c975-4ae7-98ee-f58adc15200e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardHolderName&quot;)</value>
      <webElementGuid>bd2c292a-0864-4e4c-b8d1-ae845afc69f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardHolderName']</value>
      <webElementGuid>cffda9d6-c8a8-4433-b4b4-a6f7a4ee1b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zoncardHolderName']/input</value>
      <webElementGuid>82808c98-8142-489c-8cc9-119852ecfd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>33f352f5-edf3-4a86-9344-e8f60d5d543b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cardHolderName' and @id = 'cardHolderName' and @placeholder = 'Nom du porteur de la carte']</value>
      <webElementGuid>ff0b9a46-6dee-468d-9fb8-18b0cb0616e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
