<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_01                                  _280cf8</name>
   <tag></tag>
   <elementGuidId>99c5166c-cf18-4d2d-b399-1b8002cd406d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date-validite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date-validite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b6c0891e-af6b-4e0b-a780-b7785de7ca61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date-validite</value>
      <webElementGuid>431bedc1-4e4c-4277-b94a-9bef1983fb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f6e76cc-4830-4a2a-8d2b-c9e5f4de51e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ecom_Payment_Card_ExpDate_Month</value>
      <webElementGuid>364a78f1-1353-4b85-8343-e7fb3d6a248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            01
                                            02
                                            03
                                            04
                                            05
                                            06
                                            07
                                            08
                                            09
                                            10
                                            11
                                            12
                                        </value>
      <webElementGuid>e10c3236-5935-45f7-80cb-70387361dadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date-validite&quot;)</value>
      <webElementGuid>eec22d39-e4f8-4ded-a125-6f538ede0f79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date-validite']</value>
      <webElementGuid>bd54492c-d5fa-46e9-891e-74f849f580fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zonCard_ExpDate']/table/tbody/tr/td/select</value>
      <webElementGuid>a7361097-e7bb-43c6-8f34-dae048d2fe13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date d', &quot;'&quot;, 'expiration')])[1]/following::select[1]</value>
      <webElementGuid>903f3b53-9d67-4244-9339-42e5fcd58f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro de carte de paiement'])[1]/following::select[1]</value>
      <webElementGuid>6f42d6a7-78a1-43b1-8bdc-189bc1229c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code de vérification'])[1]/preceding::select[2]</value>
      <webElementGuid>148d11bc-2b57-4fe0-a4f0-5789acd44d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>64784ea7-0f01-4785-8fcf-7fe3f7637c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'date-validite' and @name = 'Ecom_Payment_Card_ExpDate_Month' and (text() = '
                                            01
                                            02
                                            03
                                            04
                                            05
                                            06
                                            07
                                            08
                                            09
                                            10
                                            11
                                            12
                                        ' or . = '
                                            01
                                            02
                                            03
                                            04
                                            05
                                            06
                                            07
                                            08
                                            09
                                            10
                                            11
                                            12
                                        ')]</value>
      <webElementGuid>ff218b50-2827-4f04-be07-74302cd65ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
