<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Compte activ_googleAuthj_id47</name>
   <tag></tag>
   <elementGuidId>2d0938a9-347e-4d27-a600-c114e6469df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;googleAuth:j_id47&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='googleAuth:j_id47']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e0a91b9-3241-4bde-bbff-8778198408ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b23d0e05-469d-40a9-b389-19ac31207ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>googleAuth:j_id47</value>
      <webElementGuid>42858926-5ffe-4511-8cb1-97e35e4b32fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Se connecter</value>
      <webElementGuid>ba297338-51f1-4803-89c1-b19288202d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion btn-block</value>
      <webElementGuid>9d4383e7-24b8-4fed-9afd-bf9724743305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>88723494-5266-484c-bbdd-c5dc226e6603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;googleAuth&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12 form-content&quot;]/div[@class=&quot;col-md-6 div-center&quot;]/input[@class=&quot;btn btn-connexion btn-block&quot;]</value>
      <webElementGuid>8fe2bf73-0b01-45b1-be71-ba675b90823a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='googleAuth:j_id47']</value>
      <webElementGuid>c3255a7e-1b1f-4b72-afd0-471ccc0b5c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='googleAuth']/div/div/div/input</value>
      <webElementGuid>5e087453-c221-42c3-8c36-8c90b350d378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>26f39631-7dba-4552-9923-1326db6ef8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'googleAuth:j_id47']</value>
      <webElementGuid>1f6e1bcc-4e3c-4ebe-a8d1-dddf34baa455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
