<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code secret_validationCodeGoogleAuthF_5f6fed</name>
   <tag></tag>
   <elementGuidId>34461c8f-f472-4e4a-81e8-b2d55e037c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='validationCodeGoogleAuthForm:j_id30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Valider&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78b94e2c-dcec-4e5d-b2e3-b594027b17ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-action1</value>
      <webElementGuid>a7f1141a-a61e-4484-837c-3bf21e607d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id30</value>
      <webElementGuid>f0059135-aad2-4b57-96c0-c9c7eec17e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id30</value>
      <webElementGuid>dd1691e0-85fa-4c59-a031-5cad7089e380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('validationCodeGoogleAuthForm',event,{'similarityGroupingId':'validationCodeGoogleAuthForm:j_id30','parameters':{'validationCodeGoogleAuthForm:j_id30':'validationCodeGoogleAuthForm:j_id30'} } );return false;</value>
      <webElementGuid>7a2f761c-dd4d-43b6-8dc6-9045316f85e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>e7272abf-bb3d-47e4-9629-f5fb6eb2e481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>caf4293b-ec50-45cd-a2ff-dfee3186afa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCodeGoogleAuthForm:j_id30&quot;)</value>
      <webElementGuid>2a12c691-11f8-4bf9-bc80-c42fa471450d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validationCodeGoogleAuthForm:j_id30']</value>
      <webElementGuid>96da8b26-e1bc-4916-9ca9-059987a5cf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationCodeGoogleAuthForm']/div/div[2]/input</value>
      <webElementGuid>40f269df-0e1b-4f6a-8d43-f4a74a417c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>76b1d624-95a9-4f12-b094-111616204a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'validationCodeGoogleAuthForm:j_id30' and @name = 'validationCodeGoogleAuthForm:j_id30' and @type = 'button']</value>
      <webElementGuid>35f38644-58cb-43db-9a6d-0e3450808f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
