<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code secret_validationCodeGoogleAuthFormcode</name>
   <tag></tag>
   <elementGuidId>e45c1a3c-85e9-4550-92f7-94985625831f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='validationCodeGoogleAuthForm:code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee453e43-084e-489c-b016-3b6fab85d108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:code</value>
      <webElementGuid>f555ab2c-127f-42db-a8c9-bd0af78306be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c89da84f-4bd3-4767-be3b-d8ea4286b2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:code</value>
      <webElementGuid>6fa4a7f6-e63a-45cc-8d2b-3f0f56370c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control code</value>
      <webElementGuid>08307f55-03eb-4a6a-985e-48e69f59282a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>47cb9197-49a5-4fee-a3d6-d8d32da54943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8cbe0ef2-d9ca-4369-9125-09990f395d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f80add02-4132-478d-846b-4eb140a6a3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCodeGoogleAuthForm:code&quot;)</value>
      <webElementGuid>b6cc8edf-8844-4cb7-939b-6b1e875cee10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validationCodeGoogleAuthForm:code']</value>
      <webElementGuid>c7b0a4d3-362d-446a-8785-c076698c0845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationCodeGoogleAuthForm']/div/div/input</value>
      <webElementGuid>b164c3ed-05ab-4682-8fdc-ac6d31a9c361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>82968a01-8fa2-4b57-991b-2fe02b55e5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'validationCodeGoogleAuthForm:code' and @type = 'text' and @name = 'validationCodeGoogleAuthForm:code']</value>
      <webElementGuid>7bc7bc69-9bad-4df9-bef8-c67108a39798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
