<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signature et dpt_dossierModifFormj_id782</name>
   <tag></tag>
   <elementGuidId>f4dd5769-fb22-4519-a502-32f0cf658a3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dossierModifForm:j_id782&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dossierModifForm:j_id782']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59791ac8-8198-4493-b897-aef297f0308c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>24681f98-2d41-4ca3-9f94-d69f6364c549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierModifForm:j_id782</value>
      <webElementGuid>6b99e9bb-50c3-42b6-a7e8-e1ebdd4553b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>2ed7b5f4-f2a8-4b8a-a9cf-05d87f0e14f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion next</value>
      <webElementGuid>815e8bef-161e-480e-9c96-4202ead2d650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1cfbb6f4-8507-48b7-a778-b990934ba46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierModifForm:capitalSocilNbrPart&quot;)/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content&quot;]/input[@class=&quot;btn btn-connexion next&quot;]</value>
      <webElementGuid>edc797b6-edec-4907-9153-2b2b5d91aa5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dossierModifForm:j_id782']</value>
      <webElementGuid>bb73f4cb-f5d6-484f-bf40-33bbef5d3268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierModifForm:capitalSocilNbrPart']/table/tbody/tr/td/input[2]</value>
      <webElementGuid>05bac487-2778-4d71-a991-42a5167401fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[2]</value>
      <webElementGuid>f9532ee3-2b1c-4524-bf65-a79ed5cc152b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'dossierModifForm:j_id782']</value>
      <webElementGuid>34cb21d3-f1d6-493a-85bf-ca84f065509d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
