<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Slectionner</name>
   <tag></tag>
   <elementGuidId>4546845f-b86d-42ab-b0a8-c2b05ce1f2a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upLE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='upLE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>611f5b3f-5321-4666-9de4-b56e9d26ca7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upLE</value>
      <webElementGuid>bcd7a9e9-a268-4d61-a1d3-a0b4df1b6c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resumable-browse</value>
      <webElementGuid>da98743c-0ee0-4a9b-966b-10466dd2d689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>updateParams('LE', 'alt.j3-2vx8dc0@yopmail.com')</value>
      <webElementGuid>09429fad-1189-4723-82dd-9f18a64c49ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c04eea7a-ad99-4b7e-98c5-61e600e77a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner</value>
      <webElementGuid>203f1928-7f4a-4c80-884b-36c366041bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upLE&quot;)</value>
      <webElementGuid>99144d89-e771-4970-b063-fd5bbad4e67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='upLE']</value>
      <webElementGuid>864f0881-04e4-45a6-941e-4cbe02c94000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='validationCodeGoogleAuthForm:panelLE_body']/div/div/a</value>
      <webElementGuid>73536dca-f891-4385-8bd1-188948c424b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::a[1]</value>
      <webElementGuid>9176200b-86bb-4fd1-80a6-dd85eac62de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous vous avons envoyé un code SMS de validation de compte . Veuillez le saisir ci-dessus'])[1]/preceding::a[5]</value>
      <webElementGuid>b6726d9c-5345-435b-a3ec-13627513e5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>e3356fc5-e343-4978-9738-2340caac3643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'upLE' and (text() = 'Sélectionner' or . = 'Sélectionner')]</value>
      <webElementGuid>e6fadb38-0f30-4583-bcc9-6fdf58f8f3d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
