<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IframeCaptcha</name>
   <tag></tag>
   <elementGuidId>2547eb2e-c105-4f06-bbf0-5482cb054577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;demandeAdhesionAnonymeForm:cinTab&quot;]/table/tbody/tr/td/div[3]/div/div/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
