<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Confirmation</description>
   <name>IframeConfirm</name>
   <tag></tag>
   <elementGuidId>329df843-c523-48b1-8deb-b656ca1dbb6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ifmail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
