<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code secret_validationCodeGoogleAuthFormcode</name>
   <tag></tag>
   <elementGuidId>d0d2118f-2525-4079-8fa8-3e61fcf2d063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@id, &quot;validationCodeGoogleAuthForm:code&quot;) and @type=&quot;text&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1036b2b-db2c-4f5d-bdf9-cc39d2505029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:code</value>
      <webElementGuid>811519a3-e3b6-4a76-8407-c08e83a8b260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71a86439-5b3e-4f69-ae7c-7bccc0ae61da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:code</value>
      <webElementGuid>9e856f46-8916-4c5b-94df-fcf78379aeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control code</value>
      <webElementGuid>9ca40b9e-e5e4-4aa5-be1e-6c81d3cfeaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>970116fb-f01d-4a22-9c22-2fa8553c18a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>10033f74-3d9b-40f0-aa3f-f9dbec950bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e8118bc3-c151-4fc3-864f-903d1b031c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCodeGoogleAuthForm:code&quot;)</value>
      <webElementGuid>5b0e649a-b41f-46cd-b797-0cc5a8d89f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validationCodeGoogleAuthForm:code']</value>
      <webElementGuid>169a3fc4-c9ed-4d0f-a380-fa938b7999c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationCodeGoogleAuthForm']/div/div/input</value>
      <webElementGuid>d91b347b-2175-4fa4-a3ae-4a80c2cff817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>33820a05-ad33-4cc4-946d-fb1b77c53fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'validationCodeGoogleAuthForm:code' and @type = 'text' and @name = 'validationCodeGoogleAuthForm:code']</value>
      <webElementGuid>4be8524b-4db1-4e72-82e0-40fa3dae484a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
