<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Liste de tous les comptes</name>
   <tag></tag>
   <elementGuidId>1b194e48-ef79-4089-b4f2-3b51dc354757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconbienvenue:liste_des_utilisateurs_jsf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9deef711-43ec-42be-b17f-97a3d33616cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-item-label rich-pmenu-top-item-label</value>
      <webElementGuid>ebb20d02-cb94-4aff-8844-bcf1638b1dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconbienvenue:liste_des_utilisateurs_jsf</value>
      <webElementGuid>11d76304-e7ca-48cf-bf2c-74d4b60b9eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b5d11805-45f6-4530-af46-ed90b9bd93b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liste de tous les comptes</value>
      <webElementGuid>7e2aab29-e811-4e63-bbdf-26941069cac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconbienvenue:liste_des_utilisateurs_jsf&quot;)</value>
      <webElementGuid>b60e4798-97f1-497b-a2ea-1f741a6a5b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconbienvenue:liste_des_utilisateurs_jsf']</value>
      <webElementGuid>456d3524-4d34-43ed-b010-2c90b5ba9fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_bienvenue:liste_des_utilisateurs_jsf']/td[2]</value>
      <webElementGuid>01b01f11-d892-468f-b2b0-c68c6d234555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des comptes'])[2]/following::td[2]</value>
      <webElementGuid>afc936f2-25a7-4359-9cec-c4b246bd27ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des comptes'])[1]/following::td[2]</value>
      <webElementGuid>e6288ac2-dd87-481d-a2a6-dcd99ebd1116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liste des comptes en possession'])[1]/preceding::td[3]</value>
      <webElementGuid>80ab12fb-66e0-4916-a071-28bc4a0a176d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestion des dossiers'])[1]/preceding::td[5]</value>
      <webElementGuid>58aabcdf-0a2c-49c0-b226-a1efeb225b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liste de tous les comptes']/parent::*</value>
      <webElementGuid>f9c2a51a-7db6-434d-9c90-74c0114ac3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>dbcdefe1-1dff-461e-bf46-899e1533a83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconbienvenue:liste_des_utilisateurs_jsf' and (text() = 'Liste de tous les comptes' or . = 'Liste de tous les comptes')]</value>
      <webElementGuid>0f6dabc2-826b-4470-84e0-6fb2064e2467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
