<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Slectionner</name>
   <tag></tag>
   <elementGuidId>dff8f660-68d9-41c4-a46d-05446b832fd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upLE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='upLE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87c3f707-2793-4181-87ec-6cebc3798399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upLE</value>
      <webElementGuid>181d4d7d-44cd-49a6-94b9-88bb8b9309a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>resumable-browse</value>
      <webElementGuid>3325a0f2-5beb-4b55-9182-ba8097fea3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>updateParams('LE', 'alt.em-8q862k@yopmail.com')</value>
      <webElementGuid>847571a8-8e68-4b89-919d-5abe261f0919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0f3fd014-4334-43de-b2e5-f70ecb0010dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner</value>
      <webElementGuid>fd826f26-b6be-4e2a-8542-df5dd238eaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upLE&quot;)</value>
      <webElementGuid>96e802ce-2c92-478a-a258-0898f72c3de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='upLE']</value>
      <webElementGuid>7dcc7f37-4b5e-430a-8064-60dc4a313453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='validationCodeGoogleAuthForm:panelLE_body']/div/div/a</value>
      <webElementGuid>bc068318-a60c-4af0-a8db-a368ac3c22c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::a[1]</value>
      <webElementGuid>0944e49f-e9be-4751-a32f-42b9d4f5d20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous vous avons envoyé un code SMS de validation de compte . Veuillez le saisir ci-dessus'])[1]/preceding::a[5]</value>
      <webElementGuid>54cf391c-61be-410b-bf26-acd1d59fc2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>a81439c5-ce64-4e8f-be8d-cf4d75f8e5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'upLE' and (text() = 'Sélectionner' or . = 'Sélectionner')]</value>
      <webElementGuid>1f75c5a4-a6ff-49d6-93be-0f2679fbf415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
