<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_Slectionner</name>
   <tag></tag>
   <elementGuidId>96b64fc3-8587-4b7d-b707-98c0b243d4da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='upLE']/u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>74bd10e2-6ae5-4998-90e1-5d5403a44519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a54af624-4042-4449-806b-063dfac9cbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner</value>
      <webElementGuid>ec6ea9c7-1bc4-47f9-9547-37d01bb5aafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upLE&quot;)/u[1]</value>
      <webElementGuid>5d1b4b24-9959-4ab1-87d5-cf29b82d7bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='upLE']/u</value>
      <webElementGuid>7245d697-63bb-4302-8a61-ed61d58b44c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::u[1]</value>
      <webElementGuid>499ae692-55d5-4ddc-a892-98f270bf9ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous vous avons envoyé un code SMS de validation de compte . Veuillez le saisir ci-dessus'])[1]/preceding::u[1]</value>
      <webElementGuid>6b31a6f9-ec49-4208-b54e-afb063e8a88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entreprise.ma'])[1]/preceding::u[1]</value>
      <webElementGuid>757ab444-b813-4654-bf0a-f6b6f9ded6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sélectionner']/parent::*</value>
      <webElementGuid>394ccf71-3890-4707-8ba2-fbf39e28013e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>ff03b8ca-dd3b-4799-a3ec-9161d5fbad2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Sélectionner' or . = 'Sélectionner')]</value>
      <webElementGuid>5b5caa88-d855-4a74-8369-89244f1277a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
