<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mot de passe_j_id41j_id57</name>
   <tag></tag>
   <elementGuidId>1f206991-bb13-441f-81f3-0b8be66a2952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;j_id41:j_id57&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='j_id41:j_id57']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acab6a11-f726-475d-b1e3-faeaa87eb3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ac72caa7-c684-45ec-bf48-601b7a3af3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_id41:j_id57</value>
      <webElementGuid>def7dcc2-a4bb-4100-9de6-11ea48a0a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>49e78141-37d2-4246-a9fc-7b2e85429796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>0cb611df-4aa7-4162-9d0c-433dc7f05616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c2cb68ed-a2e6-4302-b644-f6abbd9b4e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id41&quot;)/div[@class=&quot;col left&quot;]/div[3]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>2971b780-81a8-4d73-a775-3980b7b78766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='j_id41:j_id57']</value>
      <webElementGuid>ac0f01a6-e128-41c2-9796-b99c0b2362e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_id41']/div/div[3]/input[3]</value>
      <webElementGuid>39d09add-962c-4398-a19d-8918a3d52a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[3]</value>
      <webElementGuid>a5030ed6-b7a4-4432-b29a-07948f1b4d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'j_id41:j_id57']</value>
      <webElementGuid>bfb0a917-803e-484d-a5dc-4acd4e4ffc03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
