<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Recherche des dossiers</name>
   <tag></tag>
   <elementGuidId>eca5e2a6-7690-4705-ad45-3456647c97fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconpaiementForm:liste_dossier_pp_jsf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Recherche des dossiers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>37687bd6-b38d-42fd-824e-42522572d49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-item-label</value>
      <webElementGuid>88712970-4fab-4c8e-aa8f-e843749ff146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconpaiementForm:liste_dossier_pp_jsf</value>
      <webElementGuid>6711bf74-95b9-4555-8241-91cabb4abebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3e3abd9e-44f7-45c9-bbd4-123dc6758100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recherche des dossiers</value>
      <webElementGuid>66f9fdd2-1f78-4bf7-be9f-bfd8a645e76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconpaiementForm:liste_dossier_pp_jsf&quot;)</value>
      <webElementGuid>befaa5d1-422c-463f-95dd-f92995895366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconpaiementForm:liste_dossier_pp_jsf']</value>
      <webElementGuid>08371d29-e2bf-4917-ba96-fbbf69d2ce60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_paiementForm:liste_dossier_pp_jsf']/td[2]</value>
      <webElementGuid>9882d782-40a1-471e-b13b-c913bfe32f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[6]/following::td[3]</value>
      <webElementGuid>70573537-d9a0-400a-9cd7-75c288db85bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personne physique'])[1]/following::td[6]</value>
      <webElementGuid>58d717b1-7b20-4b7a-a8f7-92b40a35e02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gérance libre'])[1]/preceding::td[3]</value>
      <webElementGuid>0e2e77f6-f8bc-4c74-aa8b-1c1322ff1020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[7]/preceding::td[6]</value>
      <webElementGuid>8d483d0f-9df9-452c-b8d7-546e91db94ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>834d036d-3690-48f7-b440-19ef4dcf7707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconpaiementForm:liste_dossier_pp_jsf' and (text() = 'Recherche des dossiers' or . = 'Recherche des dossiers')]</value>
      <webElementGuid>8e995773-004f-4021-97a4-a91ae1dfb9b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
