<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(J, , accepte et j, , approuve)_222aa8</name>
   <tag></tag>
   <elementGuidId>68f9b52b-f9e8-4c9c-9ad6-1eab609e7850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:modifierDossie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ab963c7-0efb-45c3-b38a-1056094f2d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>a6e46aca-4cef-42e0-8fa4-264c040e02c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:modifierDossie</value>
      <webElementGuid>f33e281c-d5aa-4ef5-b947-f8fc10b10b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:modifierDossie</value>
      <webElementGuid>bfd8a9e2-98f6-4c53-918a-9330b21aaf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:modifierDossie','parameters':{'dossierForm:modifierDossie':'dossierForm:modifierDossie'} } );return false;</value>
      <webElementGuid>65b66a0f-af7c-4191-9b26-0737fb9aee33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>3fa4c961-bce1-41e1-bb3a-1d42156100f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9b07a42-43f3-4710-aea2-ef21bd5b59c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9943aaec-7016-4f97-841e-e064c76b6dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:modifierDossie&quot;)</value>
      <webElementGuid>c096629a-f838-4705-b4e8-db02f0516f09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:modifierDossie']</value>
      <webElementGuid>33658f49-5c39-4da6-8643-96c79f5c2626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id44_body']/div[5]/input[2]</value>
      <webElementGuid>fb395b7d-84bd-4222-868e-fa684a01d550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>8cd204fb-c7d8-428f-acfe-7d6df30e6eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:modifierDossie' and @name = 'dossierForm:modifierDossie' and @type = 'button']</value>
      <webElementGuid>6a0c6f5a-c7c9-49d4-acc4-6051bc536214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
