<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(J, , accepte et j, , approuve)_b0e04d</name>
   <tag></tag>
   <elementGuidId>69df3cc8-961d-49f2-9ff8-53f657b4e76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:checkValide']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ead69f99-7eb1-425a-a32a-2d4b8c8886b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:checkValide</value>
      <webElementGuid>64db577b-6fae-4b4f-9bfe-e09dbc922ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a6d99689-d29f-4d83-90a8-27af8d3983a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:checkValide</value>
      <webElementGuid>8bfe7bfb-f7b9-48e9-937a-c790e4702b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>J'accepte et j'approuve les conditions générales d'utilisation du service.</value>
      <webElementGuid>27bde462-bcbd-4c90-9f75-5cf6f48fb21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e2a7d1b2-2ff2-48b5-a5b5-189605cfd167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:checkValide&quot;)</value>
      <webElementGuid>dc818a45-066e-45c8-9453-5878b1d78adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:checkValide']</value>
      <webElementGuid>beec1b78-46d6-428e-8d6a-d83e6eb2f0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id766_body']/div/label/input</value>
      <webElementGuid>cbfe2b30-a674-411d-9290-ec6d23d7fe96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>e3d07ddc-3943-411d-942c-46f96798a67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:checkValide' and @type = 'checkbox' and @name = 'dossierForm:checkValide' and @title = concat(&quot;J&quot; , &quot;'&quot; , &quot;accepte et j&quot; , &quot;'&quot; , &quot;approuve les conditions générales d&quot; , &quot;'&quot; , &quot;utilisation du service.&quot;)]</value>
      <webElementGuid>76c076cc-639f-46d4-a4d2-cba776f99e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
