<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_01022017</name>
   <tag></tag>
   <elementGuidId>c0385759-bbec-499a-9427-0036ea8eadc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='dossierForm:dateDelivCn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cb46de10-38f4-4f40-b856-176efa24fc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:dateDelivCn</value>
      <webElementGuid>934c5bb9-83e7-459d-8f60-10318a31cc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b69bcbe3-e9bc-45ab-a405-5d001cc071d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4bac49ff-cac8-42ef-a3b2-4dc12297c8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
01/02/2017</value>
      <webElementGuid>b6ce4858-c2bf-450d-a6e3-b488a42f72b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:dateDelivCn&quot;)</value>
      <webElementGuid>4dc98d84-b6bb-4580-ac8d-d0bbe4d906c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='dossierForm:dateDelivCn']</value>
      <webElementGuid>f3b6630b-c51d-4c05-9bac-3adcb497d44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:panelCertif_body']/div[3]/div[4]/label[2]</value>
      <webElementGuid>2dcc4969-4801-43d9-911f-125d2bf4d6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date de délivrance du certificat négatif'])[1]/following::label[1]</value>
      <webElementGuid>92dbd40f-806c-469e-b78e-c6c98758d481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numéro du certificat négatif'])[1]/following::label[3]</value>
      <webElementGuid>22a1b224-3f63-400c-bed8-ece9617391b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresse du siège social'])[1]/preceding::label[1]</value>
      <webElementGuid>1bd7bbd8-2c29-4d5b-a9fa-5288f747f4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresse'])[1]/preceding::label[1]</value>
      <webElementGuid>857b12a9-c2cb-4444-bf87-97161fbddd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01/02/2017']/parent::*</value>
      <webElementGuid>d4eee099-227e-4c7f-a2e3-f00ea04de872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label[2]</value>
      <webElementGuid>b0d0ae30-ae61-40e7-b8ae-de0043a0bace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'dossierForm:dateDelivCn' and (text() = '
01/02/2017' or . = '
01/02/2017')]</value>
      <webElementGuid>2227e9a8-bf7f-4a05-98e0-96be5e6ec95e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
