<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code secret_validationCodeGoogleAuthF_9c6b20</name>
   <tag></tag>
   <elementGuidId>5835bd2b-9d01-497b-9216-a2008101c015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='validationCodeGoogleAuthForm:j_id52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df4fa99b-6c00-437d-8919-640bc03534d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>aeac30ab-c6e3-4c62-a1e9-04c6b55d2030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id52</value>
      <webElementGuid>136c74f0-9f48-4390-a900-37edfc79ffeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id52</value>
      <webElementGuid>6faa5401-e74a-4a3a-884e-1eed81d3db39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('validationCodeGoogleAuthForm',event,{'similarityGroupingId':'validationCodeGoogleAuthForm:j_id52','parameters':{'validationCodeGoogleAuthForm:j_id52':'validationCodeGoogleAuthForm:j_id52'} } );return false;</value>
      <webElementGuid>b744f161-71dd-452a-8466-ef192db25f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>fac82d1c-f4dc-41dc-afc9-3686fe004171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d8a12bfd-5b94-48ec-ba55-efb7150f9a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>663f0971-2ef6-4c1f-affd-10df762bea71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCodeGoogleAuthForm:j_id52&quot;)</value>
      <webElementGuid>09e28fac-ed00-4745-a819-2ed0813f0c2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validationCodeGoogleAuthForm:j_id52']</value>
      <webElementGuid>52a44e8d-2fb4-495d-a2ed-fac1b9638e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationCodeGoogleAuthForm']/div/div[2]/input</value>
      <webElementGuid>92160689-602c-4647-be9f-b5ea5970b81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>42fb25d1-9dda-4fa6-929f-93b27ceca0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'validationCodeGoogleAuthForm:j_id52' and @name = 'validationCodeGoogleAuthForm:j_id52' and @type = 'submit']</value>
      <webElementGuid>67e6020d-6592-45c7-973e-132e3bc5474b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
