<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pices jointes_dossierFormpiecesASigner</name>
   <tag></tag>
   <elementGuidId>f6068a94-4dab-41a8-bb57-c5140a4dcd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:piecesASigner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Signer les documents&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b1740a4-5226-45b0-89bb-06baa61ac30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>8e4680cf-cf04-409f-a0b1-4ab3fbd59b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:piecesASigner</value>
      <webElementGuid>bf292291-72a4-4a82-abda-43015c6c3378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:piecesASigner</value>
      <webElementGuid>9a932e6c-868f-438f-ba08-35f3e3ad457b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setTimeout('document.getElementById(\'' + this.id + '\').disabled=true;', 50);;A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:piecesASigner','parameters':{'dossierForm:piecesASigner':'dossierForm:piecesASigner'} } );return false;</value>
      <webElementGuid>22694d72-dbdb-4800-8898-b4ec0b69cb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Signer les documents</value>
      <webElementGuid>956fb7f1-ccc3-41db-872b-216745959fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fe70333-387f-4d4a-b7a6-21c790b854b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4242e705-e3f2-4dce-a92f-054ff1b776d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:piecesASigner&quot;)</value>
      <webElementGuid>d33ea79d-5f08-4123-841d-7861ad32341b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:piecesASigner']</value>
      <webElementGuid>633eb4c5-b548-4efc-b00b-982e63e7a968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:buttonrichpanel_body']/div/input[2]</value>
      <webElementGuid>f1016e47-164a-456d-a03f-2dfa8127d3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>5aa59227-a845-40c0-8a4b-057adbbf4b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:piecesASigner' and @name = 'dossierForm:piecesASigner' and @type = 'button']</value>
      <webElementGuid>f2bc3679-50e3-4801-ab33-af64329272aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
