<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(J, , accepte et j, , approuve)_b0e04d</name>
   <tag></tag>
   <elementGuidId>2b4f6a0d-18f3-4e3e-953c-7ef1682d6f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:checkValide']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;J'accepte et j'approuve\n\t\t\t\t\t\t\t\t\t   \t\tles conditions générales d'utilisation du service.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>954c39ad-0352-4448-9e02-c98de8f8b6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:checkValide</value>
      <webElementGuid>660bf031-eec1-4e4b-a6d4-078d5b85d6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e1cf9a2d-1f58-4229-b6f7-723b58d3dfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:checkValide</value>
      <webElementGuid>da35e1a4-96e7-4a42-b22d-f67e6bdc4054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>J'accepte et j'approuve les conditions générales d'utilisation du service.</value>
      <webElementGuid>c92c7c61-0cb9-4cf0-bdad-0dbcc9a4fb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bb66b29e-08ba-48fe-be79-810c40227892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:checkValide&quot;)</value>
      <webElementGuid>43eef9ce-28cb-4699-9b3b-195559392c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:checkValide']</value>
      <webElementGuid>e4000102-cb76-42cc-814b-12b17c9f7db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id481_body']/div/label/input</value>
      <webElementGuid>bc145f98-0f9b-4909-9083-083e88bd7528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>ad45aa75-bf4b-46ed-8d39-23a7ffb6d318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:checkValide' and @type = 'checkbox' and @name = 'dossierForm:checkValide' and @title = concat(&quot;J&quot; , &quot;'&quot; , &quot;accepte et j&quot; , &quot;'&quot; , &quot;approuve les conditions générales d&quot; , &quot;'&quot; , &quot;utilisation du service.&quot;)]</value>
      <webElementGuid>61d18d0d-0c6d-44aa-9188-90a884c9f7b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
