<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Decline</name>
   <tag></tag>
   <elementGuidId>84135bdd-099e-4c60-a938-d57cb7d79337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cookie_action_close_header_reject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cookie_action_close_header_reject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9714e71c-d2f4-4531-ac0e-c5720ce0f364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>979b8ac0-b728-495c-95b8-db0823e65522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bdb3c9fc-2615-4448-bbae-c26552433c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookie_action_close_header_reject</value>
      <webElementGuid>91c1771e-db7b-49fd-9595-9470b0c3773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium cli-plugin-button cli-plugin-main-button cookie_action_close_header_reject cli_action_button</value>
      <webElementGuid>b99cf439-7cc6-4311-ba57-681d6314a15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cli_action</name>
      <type>Main</type>
      <value>reject</value>
      <webElementGuid>ee8ef0d4-b990-427f-998c-80c58a21d33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Decline</value>
      <webElementGuid>9be83bce-e9a2-4f16-a603-a0cda64dc0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookie_action_close_header_reject&quot;)</value>
      <webElementGuid>e6392486-d713-4fe3-99b9-5b1c3145e107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cookie_action_close_header_reject']</value>
      <webElementGuid>b06b0926-114e-4952-aec5-d75ed1cbf861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-law-info-bar']/span/div/div[2]/a[2]</value>
      <webElementGuid>b7066270-6855-4c71-8b23-fe03f1260784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Decline')]</value>
      <webElementGuid>fd495129-26c1-4e72-8840-0aacf2378912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie settings'])[1]/following::a[1]</value>
      <webElementGuid>f38ba2f9-d88a-4822-b1dc-c1eeebf426c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do not sell my personal information'])[1]/following::a[2]</value>
      <webElementGuid>34f442f7-c61c-4f10-b806-4a2ddffd4255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow &amp; Close'])[1]/preceding::a[1]</value>
      <webElementGuid>82bd24ad-8b82-45c6-90ac-c31e73b8e285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage consent'])[1]/preceding::a[2]</value>
      <webElementGuid>73e1a710-9d56-4c3d-9bbe-e6ad686e47fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Decline']/parent::*</value>
      <webElementGuid>3faf9153-a7fe-424b-92af-9cbfb7795b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>58875c3d-0354-4a28-9dd1-98f738b41a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cookie_action_close_header_reject' and (text() = 'Decline' or . = 'Decline')]</value>
      <webElementGuid>65ef8d0e-20ca-4529-a312-475951aa613a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
