<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supprimer tout_demandeAdhesionAnonyme_1e55dd</name>
   <tag></tag>
   <elementGuidId>1055c02e-b490-4831-8d2a-7ffce4350fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:checkValide']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;J'accepte et j'approuve les conditions générales d'utilisation du service.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62b5c66a-bb26-43a2-9bae-ef33ead9c390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:checkValide</value>
      <webElementGuid>140fa238-e9d5-44e5-aecc-9d03440b00e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>953ccdf4-79d0-4ab7-a0d2-6866ef4a1223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:checkValide</value>
      <webElementGuid>26f55ddc-2b91-4ecf-bb2a-9187f267c7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>J'accepte et j'approuve les conditions générales d'utilisation du service.</value>
      <webElementGuid>17269cb9-db31-4609-81b0-b7dc4dbe2d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a58e44f5-d26a-454e-8be5-ff6a5445bb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:checkValide&quot;)</value>
      <webElementGuid>bc248d41-7a14-4a14-b543-780c8618afe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:checkValide']</value>
      <webElementGuid>3ab887ef-efc7-43ce-9b15-bc701a463827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:j_id193_body']/div/label/input</value>
      <webElementGuid>14d94ac3-06d9-4f2a-847f-48276c2d850e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>f1bbbff0-54df-48f1-87e4-e7ba772a858a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'demandeAdhesionAnonymeForm:checkValide' and @type = 'checkbox' and @name = 'demandeAdhesionAnonymeForm:checkValide' and @title = concat(&quot;J&quot; , &quot;'&quot; , &quot;accepte et j&quot; , &quot;'&quot; , &quot;approuve les conditions générales d&quot; , &quot;'&quot; , &quot;utilisation du service.&quot;)]</value>
      <webElementGuid>cdd2b272-54fc-43bd-a3c9-95b1e3fd589b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
