<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supprimer tout_demandeAdhesionAnonyme_fbe7b2</name>
   <tag></tag>
   <elementGuidId>fbaba3fe-9184-429d-8b35-5f65d8acefff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:validTermes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Valider&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f660d7c3-5f70-4e30-afa8-eb25f4a1df23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-suivant col-md-6</value>
      <webElementGuid>3783d16e-4f0d-4fba-8b05-5b552f34f349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:validTermes</value>
      <webElementGuid>c167dee0-13bc-43a3-b52a-d1613be0007d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:validTermes</value>
      <webElementGuid>5ebd6afd-39a3-460c-a78b-0bbd7068b7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setNumberFunction();setTimeout('document.getElementById(\'demandeAdhesionAnonymeForm:validTermes\').disabled=true;', 50);;A4J.AJAX.Submit('demandeAdhesionAnonymeForm',event,{'similarityGroupingId':'demandeAdhesionAnonymeForm:validTermes','oncomplete':function(request,event,data){if('false'=='true'){                     document.getElementById('confirmAdhesion:panelConfirmTermes').component.show();};setTimeout('document.getElementById(\'demandeAdhesionAnonymeForm:validTermes\').disabled=false;', 50);},'parameters':{'demandeAdhesionAnonymeForm:validTermes':'demandeAdhesionAnonymeForm:validTermes'} } );return false;</value>
      <webElementGuid>ef55592f-4345-49e6-b81b-81c77333c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>d9fc2bf5-41c9-4a3a-a796-5cba37869c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad13e2a3-76da-4690-aa8e-e568ce0ef8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ee40a904-bc4e-4283-9b90-4180ead4540d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:validTermes&quot;)</value>
      <webElementGuid>b789360c-3afa-4ebc-957a-7f12baf23f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:validTermes']</value>
      <webElementGuid>1fa4eefd-d45c-4b8d-8c8a-d36f09de42f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:j_id44_body']/div/div[2]/input[2]</value>
      <webElementGuid>82229ed3-bae4-404f-a4f3-28a11fad968c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>dd575d94-63c1-4eae-b5b8-e25d552627b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'demandeAdhesionAnonymeForm:validTermes' and @name = 'demandeAdhesionAnonymeForm:validTermes' and @type = 'button']</value>
      <webElementGuid>8f714e2c-84dc-42ed-96ce-aa2d2ae9e53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
