<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Pice dIdentit</name>
   <tag></tag>
   <elementGuidId>0aa1150e-7368-4a8a-9458-651a1e2a2298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='demandeAdhesionAnonymeForm:cinTab_lbl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;demandeAdhesionAnonymeForm\:cinTab_lbl&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b8460fe0-93c3-4dee-b3e8-77ffa322169e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:cinTab_lbl</value>
      <webElementGuid>0ed01b60-8745-4277-9705-500ba0fbe9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>RichFaces.overTab(this);</value>
      <webElementGuid>b1bdf49d-c9ee-4c69-89cd-d7d82ae0851c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>RichFaces.outTab(this);</value>
      <webElementGuid>b0b0907d-1544-4e79-8e39-6dc403789885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-tab-header rich-tab-inactive rich-tbpnl-tb-sel</value>
      <webElementGuid>68e6c001-57a8-4d69-9ca5-2385650c3f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>98a80b98-a0ed-4675-b9eb-33b826292b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pièce d'Identité</value>
      <webElementGuid>6d467a52-00a9-4b59-9c57-a1691c8f3ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:cinTab_lbl&quot;)</value>
      <webElementGuid>3645ae90-9e52-4e16-8f59-ab90f531effc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='demandeAdhesionAnonymeForm:cinTab_lbl']</value>
      <webElementGuid>41afc2b8-c468-45f3-ae0c-c57e0370065c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:cinTab_shifted']/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>fea97d5f-5a96-4791-81fb-02f2d3fabf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations du compte'])[1]/following::td[6]</value>
      <webElementGuid>9db9a346-ef23-4cf5-a869-824ed3b56134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Création De Compte'])[2]/following::td[12]</value>
      <webElementGuid>33cf4b64-47b0-46dc-90ff-7971999b1f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::td[3]</value>
      <webElementGuid>fb19da56-73f3-4e18-958a-efd2ae677c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>8ff75c8c-9dbb-48df-9658-6f4877c76979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'demandeAdhesionAnonymeForm:cinTab_lbl' and (text() = concat(&quot;Pièce d&quot; , &quot;'&quot; , &quot;Identité&quot;) or . = concat(&quot;Pièce d&quot; , &quot;'&quot; , &quot;Identité&quot;))]</value>
      <webElementGuid>bcc30f74-1bab-4035-b387-945cd2058dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
