<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Lettre d, , engagement)_utilis_0021e2</name>
   <tag></tag>
   <elementGuidId>a4102a58-2647-48f6-a9b9-b65b94ae12ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='utilisateurProfForm:prendrePossession']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c90ed6ae-4f3a-4b27-a75f-9fe1b8ef64dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>7bf48936-300d-44d4-baf3-bf5914972253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>utilisateurProfForm:prendrePossession</value>
      <webElementGuid>773c45ce-85d6-421f-803e-8e626413be59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utilisateurProfForm:prendrePossession</value>
      <webElementGuid>ba6782f2-aaec-4470-88b8-da0ec81e4dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('utilisateurProfForm',event,{'similarityGroupingId':'utilisateurProfForm:prendrePossession','parameters':{'utilisateurProfForm:prendrePossession':'utilisateurProfForm:prendrePossession'} } );return false;</value>
      <webElementGuid>e3bd2fce-ee56-4f0e-be49-033541193313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Prendre en possession</value>
      <webElementGuid>74bc12d7-36eb-430e-9d42-feb8d886540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51ad357f-b5cb-4a33-b6ee-5b9525c39c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cfcd2ce6-3d69-4eb2-b236-0c08491b56f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;utilisateurProfForm:prendrePossession&quot;)</value>
      <webElementGuid>dd799726-1a8c-403e-9c91-51263af9da9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='utilisateurProfForm:prendrePossession']</value>
      <webElementGuid>f5c44b7e-f49d-43ae-9896-2de33ed5ceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='utilisateurProfForm:richpanelButton']/input</value>
      <webElementGuid>c0f47632-6174-48e0-9576-38d052ad33b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>a901249b-556e-4742-9dcf-4bee44f0da55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'utilisateurProfForm:prendrePossession' and @name = 'utilisateurProfForm:prendrePossession' and @type = 'button']</value>
      <webElementGuid>739da292-1916-43c5-930f-cc004fde2305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
