<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mot de passe_j_id41j_id57</name>
   <tag></tag>
   <elementGuidId>5325b975-82f4-4365-b621-83db6829da53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;j_id41:j_id57&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='j_id41:j_id57']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d9e1494-b04a-40cf-9cbd-a4df515d83cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>85b4776e-2495-4c78-ab56-c9ab0b34e758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_id41:j_id57</value>
      <webElementGuid>6a187424-2629-4e05-b014-0c51e96a994b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>684b0702-e1a8-4ea7-abdd-4e0cf18068b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>d4a52d59-9e75-46dc-90cc-65d299c7b5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>56f63679-e4d9-463f-97ed-1bdcc2a5ccb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id41&quot;)/div[@class=&quot;col left&quot;]/div[3]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>ed199c96-53b2-424f-9c71-e8f5dc472ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='j_id41:j_id57']</value>
      <webElementGuid>cc9a9a5a-5356-4d35-bd12-17c8b0b66231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_id41']/div/div[3]/input[3]</value>
      <webElementGuid>25664a1a-472b-4afe-acb8-aaa665147bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[3]</value>
      <webElementGuid>b6d24501-6b12-454c-90e8-03063f439707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'j_id41:j_id57']</value>
      <webElementGuid>734eda23-6072-4b97-8866-1676afd70026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
