<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visualiser le dossier_dossierFormlist_1ba20f</name>
   <tag></tag>
   <elementGuidId>7d02f4d2-587d-4a98-9571-9ca2214893a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbmodifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d28d6579-0826-4db0-864b-31bc362cf8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbmodifier</value>
      <webElementGuid>8b4001ad-a347-467c-bdc1-1f5d0cec532d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>dd9914dc-76c1-4ffd-9aba-7550620d4dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images/commun/icone-edit.gif</value>
      <webElementGuid>bb727673-dff8-438d-acb1-cc3049920916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbmodifier</value>
      <webElementGuid>aaae50d0-287a-48f1-afa1-7cd0f88f7abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e6b1d03b-a703-43d9-890f-e7428d4db84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeDossierEnPreparation:0:cbmodifier&quot;)</value>
      <webElementGuid>0d781672-c286-4cd0-be56-b24226e533bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbmodifier']</value>
      <webElementGuid>977a148f-33d1-495a-a3ce-c79c6da43825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeDossierEnPreparation:0:j_id125']/span/ul/input[2]</value>
      <webElementGuid>9d3c2518-9eb2-4363-829f-acdf8d4a6fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/input[2]</value>
      <webElementGuid>6996b4d0-488a-4862-8234-ee1f6c20a335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:listeDossierEnPreparation:0:cbmodifier' and @type = 'image' and @src = '/Guichet/images/commun/icone-edit.gif' and @name = 'dossierForm:listeDossierEnPreparation:0:cbmodifier']</value>
      <webElementGuid>199d0d5d-9a75-4ded-91b5-dea15ecac3f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
