<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Visualiser le dossier_dossierFormlist_a8df78</name>
   <tag></tag>
   <elementGuidId>2c6621fc-df30-42d4-88e4-7927ad0c930f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b87aaf98-ca27-4c4a-8a94-c789b9995f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbevenement</value>
      <webElementGuid>2c483a98-0a90-41e7-8741-45bc91853a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>7f45cf70-bb2b-4b51-a225-15e549b66b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images/dossier/suiviDesEvenements.gif</value>
      <webElementGuid>22a847f3-55c7-47c5-98cf-d8483a2e530a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbevenement</value>
      <webElementGuid>25a295fa-04d5-4738-92ee-19cf34e76f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d26848f5-c7d5-40b5-8d1e-0728d2e6d85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeDossierEnPreparation:0:cbevenement&quot;)</value>
      <webElementGuid>4e0399d2-6417-4b94-8665-6ea5c3047c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbevenement']</value>
      <webElementGuid>a425d70b-f6bb-44de-90f4-f22ebc7fdb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeDossierEnPreparation:0:j_id125']/span/ul/input[2]</value>
      <webElementGuid>e4719041-a312-48b4-a988-18dfb226b36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/input[2]</value>
      <webElementGuid>3f1f4a68-8748-448c-906c-5bb1dc18f95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:listeDossierEnPreparation:0:cbevenement' and @type = 'image' and @src = '/Guichet/images/dossier/suiviDesEvenements.gif' and @name = 'dossierForm:listeDossierEnPreparation:0:cbevenement']</value>
      <webElementGuid>44ae3714-d953-4d04-802c-e196b0edccaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
