<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prt pour signature_dossierFormlisteDo_df86db</name>
   <tag></tag>
   <elementGuidId>c68ea5a0-3745-4ac0-bee9-40385b50a598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e65b53b-a71b-4691-bce8-4a1cb08a3703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbvisualiser</value>
      <webElementGuid>187bdfae-cd5d-4b51-bd1c-00abbe378645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>62fe6830-0888-4bbd-a50c-5d7f25b9402a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images/commun/icone-view.gif</value>
      <webElementGuid>baf13953-3c7f-428f-a0c8-a98744033de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbvisualiser</value>
      <webElementGuid>7402d511-d2bf-4fed-8845-9a3a15b3d917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>61782a25-b650-496f-971d-23e59782f277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeDossierEnPreparation:0:cbvisualiser&quot;)</value>
      <webElementGuid>3ba969bd-0a35-4359-90c4-8d3941694eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      <webElementGuid>3005c367-2509-429a-8a71-41d0f73418f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeDossierEnPreparation:0:j_id125']/span/ul/input</value>
      <webElementGuid>b0d67e52-b725-49a5-8251-85ec77e86037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/input</value>
      <webElementGuid>91db0ecd-29da-41dd-91b4-ddb67b30a2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:listeDossierEnPreparation:0:cbvisualiser' and @type = 'image' and @src = '/Guichet/images/commun/icone-view.gif' and @name = 'dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      <webElementGuid>080e23d3-9245-4af4-b3d2-efab75ac8d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
