<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sign</name>
   <tag></tag>
   <elementGuidId>1eb42bcd-063b-422a-9f20-abaffd6b2595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='dossierForm:listeDossierEnPreparation:0:workflowState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>38b59460-ecb8-44dd-bf99-7aa055e4a0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:workflowState</value>
      <webElementGuid>4be7e290-2953-42a7-b6a5-a61d4501bf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c6e16e04-53f2-439f-8d8e-bf04206c530e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Signé</value>
      <webElementGuid>6b5545b0-a175-48f9-b8a2-e5b1b0c4898b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeDossierEnPreparation:0:workflowState&quot;)</value>
      <webElementGuid>9ce1c0a1-48f2-4c5c-ad6d-fce68f83af67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='dossierForm:listeDossierEnPreparation:0:workflowState']</value>
      <webElementGuid>a4b2b578-e521-400d-8a3b-bf49a4cb8b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeDossierEnPreparation:0:j_id122']/label</value>
      <webElementGuid>7498c5a3-6bff-4be5-91bf-eb7456e21cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Société à responsabilité limitée'])[2]/following::label[1]</value>
      <webElementGuid>f02293ff-56bb-4495-a257-39146bf7b3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visualiser le dossier.'])[1]/preceding::label[1]</value>
      <webElementGuid>65b6e86e-44fd-49cd-abd1-15552b0952b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Déposer le dossier.'])[1]/preceding::label[1]</value>
      <webElementGuid>86b67172-9b23-4726-a495-1c012edcecf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Signé']/parent::*</value>
      <webElementGuid>5bea3307-901a-4188-8a9a-8b4c22e3d243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/label</value>
      <webElementGuid>f1fe193b-1174-4326-a821-6138a287fc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'dossierForm:listeDossierEnPreparation:0:workflowState' and (text() = '
Signé' or . = '
Signé')]</value>
      <webElementGuid>fe9341eb-37bd-44ec-bdb8-4c2931c66d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
