<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Mes Dossiers Archivs</name>
   <tag></tag>
   <elementGuidId>09260460-331a-4828-945d-329816ef8ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dossierForm:j_id149_lbl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1767f337-79ae-41aa-9ad0-7e4bd76485e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:j_id149_lbl</value>
      <webElementGuid>516ba1fb-2337-4376-831c-a07c8b4bb046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>RichFaces.overTab(this);</value>
      <webElementGuid>ab4b8679-1c4d-4010-b87d-85e4ca4d6622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>RichFaces.outTab(this);</value>
      <webElementGuid>e8de8393-bd4e-4c1c-b577-0c1ee1750420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-tab-header rich-tab-inactive    dossier-archives rich-tbpnl-tb-sel</value>
      <webElementGuid>249e0145-a6a6-443e-88ee-1c1f1649e187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>16c36c7e-dbd5-4cf8-8cca-aa8e2776c734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mes Dossiers Archivés</value>
      <webElementGuid>c8ef9c5a-8af8-4081-a3eb-a116a395368a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:j_id149_lbl&quot;)</value>
      <webElementGuid>e7d5915b-b7b0-42e4-9b91-84491ef795b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:j_id149_lbl']</value>
      <webElementGuid>9d0f4d91-1938-4c21-b558-5d78d621def0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierForm:j_id149_shifted']/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>01266c30-77f2-48f4-b970-30f9dd29c689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mes dossiers en cours'])[1]/following::td[6]</value>
      <webElementGuid>5fb52ef8-d26f-4a96-bac7-ac13e3be8ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Résultat de la recherche Dossier'])[2]/following::td[12]</value>
      <webElementGuid>8c6b773f-b7ea-4ce7-8ccd-e3e5ac79b62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activité principale'])[1]/preceding::td[3]</value>
      <webElementGuid>c5fd5f07-d24a-4b42-9fad-066badbee4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresse de la Société'])[1]/preceding::td[3]</value>
      <webElementGuid>001a4d15-93be-40f7-bb5c-483b59d3ffdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mes Dossiers Archivés']/parent::*</value>
      <webElementGuid>9b8b8b9c-8e1b-45dc-ad06-779137a67a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>449d04e4-1a0a-49ff-b0d5-aa0025dccddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'dossierForm:j_id149_lbl' and (text() = 'Mes Dossiers Archivés' or . = 'Mes Dossiers Archivés')]</value>
      <webElementGuid>7519579e-38a0-410b-84db-22e00350d12d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
