<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Mes dossiers en cours</name>
   <tag></tag>
   <elementGuidId>2bfbb8f3-9546-4e91-a48a-88db7dfcb12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dossierForm:j_id86_lbl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2cb6a68a-dada-4af6-a781-b2011e22327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:j_id86_lbl</value>
      <webElementGuid>d4acd9ff-66ed-48c8-9014-bae246d72a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>RichFaces.overTab(this);</value>
      <webElementGuid>8a240ee9-6d10-4f14-814f-8ab24af2c640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>RichFaces.outTab(this);</value>
      <webElementGuid>ef5bf22a-2eaa-406e-8c7d-a9069d1e4ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-tab-header rich-tab-inactive    dossier-en-cours rich-tbpnl-tb-sel</value>
      <webElementGuid>b587d6ff-1ba8-4f4b-a074-e0fd1b76a05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>af83fcdb-d7f8-4846-8e20-b1a08ff729f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mes dossiers en cours</value>
      <webElementGuid>0e920b23-a202-47e7-9c09-dcf9e54c03b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:j_id86_lbl&quot;)</value>
      <webElementGuid>1701c702-1e67-4f76-9ab8-87fd054d9e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:j_id86_lbl']</value>
      <webElementGuid>d518e9b9-8615-49a6-b889-9b101382d950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierForm:j_id86_shifted']/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>52cedff1-9dc6-458b-b078-48d8b3ac0253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Résultat de la recherche Dossier'])[2]/following::td[6]</value>
      <webElementGuid>e8eba21f-2b70-4756-b787-5381cdc601ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dim.'])[4]/following::td[55]</value>
      <webElementGuid>d4577d02-b88a-4b8a-8aee-f06290d41efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mes Dossiers Archivés'])[1]/preceding::td[4]</value>
      <webElementGuid>fbcc130e-db5c-4f1e-9293-24fb4c52e4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activité principale'])[1]/preceding::td[9]</value>
      <webElementGuid>ee649b7c-2888-45ea-a8a3-6460d2106cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mes dossiers en cours']/parent::*</value>
      <webElementGuid>a17208c3-be3f-4fa4-ad16-97a484448956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>32d7803d-c9ec-48bb-bc4d-d2fad9c0bbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'dossierForm:j_id86_lbl' and (text() = 'Mes dossiers en cours' or . = 'Mes dossiers en cours')]</value>
      <webElementGuid>b31fe0a3-ec68-4be8-8dc6-375fb5428ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
