<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code secret_validationCodeGoogleAuthF_9c6b20</name>
   <tag></tag>
   <elementGuidId>3e6e8f85-c3cf-4195-8846-47aeaaed1499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='validationCodeGoogleAuthForm:j_id52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Valider&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17336477-f0e7-40ca-862e-7d085fbc041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>f695133a-120d-4cdb-83c3-3420b0fb334b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id52</value>
      <webElementGuid>b2886b96-a94b-4550-ace1-9d7cf95a3310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id52</value>
      <webElementGuid>e445a74d-b318-4b30-9ec3-6bbe276eefc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('validationCodeGoogleAuthForm',event,{'similarityGroupingId':'validationCodeGoogleAuthForm:j_id52','parameters':{'validationCodeGoogleAuthForm:j_id52':'validationCodeGoogleAuthForm:j_id52'} } );return false;</value>
      <webElementGuid>76093790-681d-4562-b2b5-2dd19115642e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>ba551242-189b-40f6-bca5-8ace81942115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>94366a03-3f02-4c98-836b-6e3dee83e54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0754217f-3335-43a1-9a35-6cf5cc2ff034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCodeGoogleAuthForm:j_id52&quot;)</value>
      <webElementGuid>d26527a4-2f92-4c90-b1e5-aefd17c93f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validationCodeGoogleAuthForm:j_id52']</value>
      <webElementGuid>c73e823b-9091-410d-a47e-8eb1182f34bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='validationCodeGoogleAuthForm']/div/div[2]/input</value>
      <webElementGuid>9e50c1db-3143-4de8-953d-09f3dc8120d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>abb6f40d-8846-44a2-9f59-a987aea3618a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'validationCodeGoogleAuthForm:j_id52' and @name = 'validationCodeGoogleAuthForm:j_id52' and @type = 'submit']</value>
      <webElementGuid>bb714115-1276-4b34-b84d-081753ede69b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
