<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Envoyer</name>
   <tag></tag>
   <elementGuidId>6cbc893d-085e-420e-9bbd-c70021621e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='msgsend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msgsend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>166637b3-fb01-49c6-96d9-17fb7c41a987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msgsend</value>
      <webElementGuid>7aba6482-c9dd-44d7-ad3a-1632f6622b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md but text f24 egenbut</value>
      <webElementGuid>3b35a475-f8f8-4540-b50b-c0a9ebe0fd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>w.callpost('writepost',callok,callerror,'msgfrom',msgfrom.innerText,'msgto',msgto.value,'msgsubject',msgsubject.value,'msgbody',msgbody.innerHTML);</value>
      <webElementGuid>cc8f726a-9296-489e-a16b-d869a938bf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Envoyer</value>
      <webElementGuid>e9eca3e8-8854-4111-bc0e-2ee15b7cbaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msgsend&quot;)</value>
      <webElementGuid>3efc7f5e-34d5-44a0-9858-74fd7c2562f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Yopmail/Page_Boite de rception/iframe_Undo_ifmail</value>
      <webElementGuid>12c29d14-849e-4857-963c-c164ef896fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='msgsend']</value>
      <webElementGuid>f4f474a8-47f8-4a9e-ab6a-1048e95c19f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau message'])[1]/following::button[1]</value>
      <webElementGuid>442bf08c-823e-484c-9788-f175503d9e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::button[1]</value>
      <webElementGuid>eeee926d-8ce3-4559-9680-a84bf7a827a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>2941faa5-8f32-470e-a0b7-02dc75a4d8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'msgsend' and (text() = ' Envoyer' or . = ' Envoyer')]</value>
      <webElementGuid>0a825b97-acbf-4361-a441-a364c05fccf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
