<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(No need to type , , yopmail.co_32273b</name>
   <tag></tag>
   <elementGuidId>3d38e894-7ab2-4220-bba1-17e2e0f3ab4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='msgsubject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msgsubject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de0bdab2-7644-455a-921b-1c5caf2a782e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msgsubject</value>
      <webElementGuid>8d8eb2da-5f60-4755-9d8c-3e4840662d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>52617da0-0fa7-447a-814f-61300378b628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>364dbf8e-21e7-449a-8d53-4dcb6042168d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>52324533-d7e4-4440-9016-294ecda5fb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sujet</value>
      <webElementGuid>9aceaf15-3be3-40e3-aff4-97383185198d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sujet</value>
      <webElementGuid>c33cc025-52f0-4be1-8423-9ae5a144189a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msgsubject&quot;)</value>
      <webElementGuid>f2a1c5d7-2619-4d2c-bc53-7766f45bfd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Yopmail/Page_Boite de rception/iframe_Undo_ifmail</value>
      <webElementGuid>7b0b38d3-bdce-4372-85d4-e5d1dd09a19c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='msgsubject']</value>
      <webElementGuid>0c5e9036-ab88-4d6a-8b0c-c70e9da67c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>8c2e780e-25dd-46f4-af62-320231b5c4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'msgsubject' and @placeholder = 'Sujet']</value>
      <webElementGuid>5166284c-65f6-4a2a-9d52-f81252352a67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
