<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__msgto</name>
   <tag></tag>
   <elementGuidId>35c7c1f8-ce1c-4eaf-9452-b9e22b87fc4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='msgto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msgto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d062856d-dc42-4092-9929-fdce1a6c64d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msgto</value>
      <webElementGuid>74a8b995-2fba-427c-abfd-1eb1e4117d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>febadae3-7d41-40cc-abeb-f18e37a4deec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f60d03a-5e08-4fbc-a77f-2cfba7558db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ea029c54-d50a-410a-93fc-1bf26365616d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Destinataire (vers YOPmail uniquement)</value>
      <webElementGuid>405bdd70-b8ff-4687-9d19-2e30fb7be04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Recipient</value>
      <webElementGuid>9740125a-4611-4db1-a808-d633e46597e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msgto&quot;)</value>
      <webElementGuid>5f308a65-ddd0-4f01-8b20-9b99fb1dad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Yopmail/Page_Boite de rception/iframe_Undo_ifmail</value>
      <webElementGuid>e0c42c25-f99f-4974-85f5-56e0e21d5827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='msgto']</value>
      <webElementGuid>e598b716-5dbf-4619-a682-59a07f83a772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>073c2973-aec9-4bd8-a750-87b9109bbf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'msgto' and @placeholder = 'Destinataire (vers YOPmail uniquement)']</value>
      <webElementGuid>bc931488-b5c2-4fed-83ea-687cf24bc602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
