<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Remplissez le Captcha pour continuer_09aa2f</name>
   <tag></tag>
   <elementGuidId>ebf83b2b-df65-4bf4-8838-d9b8b2df982e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-1exxeuwielpw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-1exxeuwielpw&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>23b383d4-1358-41aa-b7e8-57c82a1f39fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>4f48f14d-716b-4601-9a77-48f5c9c1f655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcG5v8SAAAAAOdAn2iqMEQTdVyX8t0w9T3cpdN2&amp;co=aHR0cHM6Ly95b3BtYWlsLmNvbTo0NDM.&amp;hl=fr&amp;v=pCoGBhjs9s8EhFOHJFe8cqis&amp;theme=white&amp;size=normal&amp;cb=8jl6hnx2kh49</value>
      <webElementGuid>e7fdf58e-5848-40b9-b472-a733655cd090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>2c974b1f-9abc-44f7-902b-1a2f7dfbb376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>b136c792-b83a-4882-83d4-8a6f5534508b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ce7f8b21-9cca-4164-a063-97d08aa970c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-1exxeuwielpw</value>
      <webElementGuid>9d43caf0-6d5e-45a6-b7e6-582ce4ced037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8320367-2676-4198-b013-f2c41a066085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fe361c61-d4d2-4e9f-bbfa-90489d0e6875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>e2393e28-7c46-4141-a618-f0ee8090e421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r_element&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>8dab8967-a83c-4179-8a8f-01a251f9020e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-1exxeuwielpw']</value>
      <webElementGuid>ecf38b51-9715-41a0-8333-ce262fbf5659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='r_element']/div/div/iframe</value>
      <webElementGuid>b2cd9c13-b0bc-4190-b23b-912d60a09163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/iframe</value>
      <webElementGuid>2a315eb7-cb6a-4ced-9d0c-59aa5bd73123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcG5v8SAAAAAOdAn2iqMEQTdVyX8t0w9T3cpdN2&amp;co=aHR0cHM6Ly95b3BtYWlsLmNvbTo0NDM.&amp;hl=fr&amp;v=pCoGBhjs9s8EhFOHJFe8cqis&amp;theme=white&amp;size=normal&amp;cb=8jl6hnx2kh49' and @name = 'a-1exxeuwielpw']</value>
      <webElementGuid>9891830e-2cdb-49c3-8c21-e91c931814f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
