<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_voitures_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>9bf33e2b-91c1-4667-a237-a3be4d8811ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66c388fe-5eda-4988-b5d0-6f64471aca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>b5620ecc-28cb-4f04-91b9-98db55b7bdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AAYGu2RiNhQwKdBSzCuRTJH3G1NEut6hkhMDaYQv9B717zdCKBvGFIPrl02sMNkjzMM0p0qdFpbNck6cEvomA9sGc4dmdJrwANtjr9xypEoPlCA2nCDEb1SzIWuEV_SfSf31VMdZtUMzC6uB7S6o13JzBb_o1Ki1OALV12Hm1ZT2Dq5xP8g5mo-3C7NvjajFtzjBLNLazr38&amp;k=6LcG5v8SAAAAAOdAn2iqMEQTdVyX8t0w9T3cpdN2</value>
      <webElementGuid>006c18d8-9ed3-46d4-903b-1775426e291a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>acd12c27-e57f-43c0-9897-463b3dfdaf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_YOPmail - Ajouter un Domaine Alternatif/iframe_concat(html1bodyclass, , index genrs_fbab3a</value>
      <webElementGuid>b51bc166-efdc-48aa-bf55-93d68fc3b2b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>51a35601-0b45-486f-a2bf-c821774465c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AAYGu2RiNhQwKdBSzCuRTJH3G1NEut6hkhMDaYQv9B717zdCKBvGFIPrl02sMNkjzMM0p0qdFpbNck6cEvomA9sGc4dmdJrwANtjr9xypEoPlCA2nCDEb1SzIWuEV_SfSf31VMdZtUMzC6uB7S6o13JzBb_o1Ki1OALV12Hm1ZT2Dq5xP8g5mo-3C7NvjajFtzjBLNLazr38&amp;k=6LcG5v8SAAAAAOdAn2iqMEQTdVyX8t0w9T3cpdN2')])[5]</value>
      <webElementGuid>69358ad5-0218-4438-a3cd-0208de2066fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>aa1d41b0-d5d5-4c2e-abb9-dcc0371da645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AAYGu2RiNhQwKdBSzCuRTJH3G1NEut6hkhMDaYQv9B717zdCKBvGFIPrl02sMNkjzMM0p0qdFpbNck6cEvomA9sGc4dmdJrwANtjr9xypEoPlCA2nCDEb1SzIWuEV_SfSf31VMdZtUMzC6uB7S6o13JzBb_o1Ki1OALV12Hm1ZT2Dq5xP8g5mo-3C7NvjajFtzjBLNLazr38&amp;k=6LcG5v8SAAAAAOdAn2iqMEQTdVyX8t0w9T3cpdN2']</value>
      <webElementGuid>ef8991e0-6bc3-41ac-9435-8ba8d99ddebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
