<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_cliquer ici</name>
   <tag></tag>
   <elementGuidId>b04f97b9-6602-44fa-bbc2-0591cb9f1a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04ed93ea-354d-4c19-bb9a-9d517780dc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://10.10.2.101:8080/Guichet/activationCompteServletNewProcess?a=ec6ed65abf1e489d57f65e6aac26b97b497265047a6fa85e6c8dacd572c66a80</value>
      <webElementGuid>557e3b93-a88d-408d-bbf8-e138d080ab8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cliquer ici</value>
      <webElementGuid>ffd70aeb-558a-43cd-9e1f-8aab376324e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/a[1]</value>
      <webElementGuid>fb5ea39d-d3a5-49f7-a36b-b251647b46e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ActivationCompte/Page_Boite de rception/iframe_Undo_ifmail</value>
      <webElementGuid>a7df2dd6-59c7-46d2-af14-c81783786cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/a</value>
      <webElementGuid>6b768daf-89a2-4497-b677-e5ff5fca0b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'cliquer ici')]</value>
      <webElementGuid>383632e7-2f92-4960-8d23-966c714d715f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::a[1]</value>
      <webElementGuid>85f5922f-dbdb-4df0-ab25-9cfcd98a8fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lundi 7 août 2023 10:21:22'])[1]/following::a[1]</value>
      <webElementGuid>508d2ec4-0bc0-4bdc-846b-d63d849e3a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mail', '&quot;', ')/div[1]/a[1]')])[1]/preceding::a[1]</value>
      <webElementGuid>230b4bd8-eb96-4dce-afe3-bc848275c957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cliquer ici']/parent::*</value>
      <webElementGuid>59f93326-e792-4b5d-ba34-f1deb917cd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://10.10.2.101:8080/Guichet/activationCompteServletNewProcess?a=ec6ed65abf1e489d57f65e6aac26b97b497265047a6fa85e6c8dacd572c66a80']</value>
      <webElementGuid>26f839f0-16b0-4913-9a66-1005b7251853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ecc910d7-a488-43e1-ae57-008c9947f7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://10.10.2.101:8080/Guichet/activationCompteServletNewProcess?a=ec6ed65abf1e489d57f65e6aac26b97b497265047a6fa85e6c8dacd572c66a80' and (text() = 'cliquer ici' or . = 'cliquer ici')]</value>
      <webElementGuid>5a323266-e0e8-405c-b294-b4263f493ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
