<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(J, , accepte et j, , approuve)_b0e04d</name>
   <tag></tag>
   <elementGuidId>33d1426f-1033-4e01-a961-8959023de8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:checkValide']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9299030a-e811-479b-a694-b0d1d56a1f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:checkValide</value>
      <webElementGuid>60061e28-7abd-4d43-b5b3-f1be1459885a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>09e81dc8-8c1a-4ce1-a977-3c7c41d841e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:checkValide</value>
      <webElementGuid>7419df7d-9cdc-4f0a-9436-d227fd35916c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>J'accepte et j'approuve les conditions générales d'utilisation du service.</value>
      <webElementGuid>8498003c-46b5-4fdb-ad52-837902c160c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>55cfdfd2-6478-4005-b384-6a87dbb31994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:checkValide&quot;)</value>
      <webElementGuid>c9fd3674-b0a0-4e24-98ac-3811f448cc42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:checkValide']</value>
      <webElementGuid>03a0f7e2-73fb-4915-a6e9-aa4b31eb5b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id766_body']/div/label/input</value>
      <webElementGuid>e6479d96-ce93-4722-a762-c8fe2cc27cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>4bc309e6-e210-4008-af5d-bb59304532f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:checkValide' and @type = 'checkbox' and @name = 'dossierForm:checkValide' and @title = concat(&quot;J&quot; , &quot;'&quot; , &quot;accepte et j&quot; , &quot;'&quot; , &quot;approuve les conditions générales d&quot; , &quot;'&quot; , &quot;utilisation du service.&quot;)]</value>
      <webElementGuid>ef5404aa-5410-405f-b099-1555d938c220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
