<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Le certificat ngatif dont la date ne _2fe7ce</name>
   <tag></tag>
   <elementGuidId>c44a52f8-bb6f-473e-ad79-9331671a2132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-sidebar']//div[2]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>581d4a55-8bb2-4cb0-8c03-ca9dd3da3c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>c6568f02-9cce-4280-b4f4-c77cd48b58fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:deposerFinal</value>
      <webElementGuid>485945ba-0771-4730-8f97-84e5a42f25ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:deposerFinal</value>
      <webElementGuid>7321444f-45d3-4e7c-8e67-184f267f419f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setTimeout('document.getElementById(\'' + this.id + '\').disabled=true;', 50);;A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:deposerFinal','parameters':{'dossierForm:deposerFinal':'dossierForm:deposerFinal'} } );return false;</value>
      <webElementGuid>d32cfb64-9c9e-4aef-adf0-94d069362bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Déposer</value>
      <webElementGuid>21baff3e-3312-4dbe-9453-2db2b108d79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74c63b89-8988-4542-980c-814dd3c70f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d2dd74da-63ae-4197-b822-e8f719ac4487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:deposerFinal&quot;)</value>
      <webElementGuid>0aed23c6-643e-49f7-863c-7bf2880b99e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:deposerFinal']</value>
      <webElementGuid>a1749a50-920d-45d1-93c1-b99d8d9985d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:buttonrichpanel_body']/div/input</value>
      <webElementGuid>8773f3b2-d879-4e09-bb15-8877ae71c4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>5fcb81d3-fc86-4e38-a31b-8b1491a4894c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:deposerFinal' and @name = 'dossierForm:deposerFinal' and @type = 'button']</value>
      <webElementGuid>00606243-d17d-4faf-838e-1ff510dfd938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
