<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Le certificat ngatif dont la date ne _31576e</name>
   <tag></tag>
   <elementGuidId>26871297-443b-42c3-9e7b-9ddbb758945e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:piecesASigner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d917772e-68e5-45fe-95f9-bb57ae8c62b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>102345b0-e687-45fd-a768-e4a4dde58a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:piecesASigner</value>
      <webElementGuid>52c386b5-0cfb-4fc2-9d5a-07d8dbfe3c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:piecesASigner</value>
      <webElementGuid>c295e3ea-6873-47b8-9387-86a6dc7dd113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setTimeout('document.getElementById(\'' + this.id + '\').disabled=true;', 50);;A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:piecesASigner','parameters':{'dossierForm:piecesASigner':'dossierForm:piecesASigner'} } );return false;</value>
      <webElementGuid>206218fa-8c86-4306-a9a4-35157676dd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Signer les documents</value>
      <webElementGuid>fced1a1f-dcc6-49e1-8318-4a0f49e466be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdef9211-31a4-4d8e-8950-4c4c192cbb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9bb3136d-d842-47c3-9888-b60617e727d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:piecesASigner&quot;)</value>
      <webElementGuid>d9fb0714-1a23-4bdd-b311-ba7c5eaf977f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:piecesASigner']</value>
      <webElementGuid>d1e617aa-f40c-4dda-963b-893f82aab7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:buttonrichpanel_body']/div/input</value>
      <webElementGuid>dde3b213-4baf-4537-b768-5342aa876536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>c0ab612e-d8ea-40d1-bc5c-7f16e17ef2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:piecesASigner' and @name = 'dossierForm:piecesASigner' and @type = 'button']</value>
      <webElementGuid>3678a3af-ea8a-48d4-a354-9a2026b25b35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
