<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mon compte</name>
   <tag></tag>
   <elementGuidId>4654dc23-853c-42ca-9b54-6966f7262d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_id14 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;j_id15&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d06031c-3188-4228-abf2-64b8519faad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2b0055b4-845e-41ca-9903-c59e3ca5a586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(typeof jsfcljs == 'function'){jsfcljs(document.forms['j_id14'],'j_id14:j_id16,j_id14:j_id16','');}return false</value>
      <webElementGuid>e2e67506-edb3-4b2c-8d62-bf570d002c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>496b8fa8-0b4d-46e4-910f-dccf4346c585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mon compte</value>
      <webElementGuid>9dfe1cdb-3445-40a4-98c6-714ed1002e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id14&quot;)/a[1]</value>
      <webElementGuid>99019005-fb58-4d66-a58a-be5bcb5350f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;if(typeof jsfcljs == 'function'){jsfcljs(document.forms['j_id14'],'j_id14:j_id16,j_id14:j_id16','');}return false&quot;]</value>
      <webElementGuid>e8718a54-f337-40cc-a35f-a1f3e98d371f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_id14']/a</value>
      <webElementGuid>ba97bee1-d069-4550-bd16-240ded6082ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mon compte')]</value>
      <webElementGuid>4d914e1a-5b07-449b-aa91-d682d9c19438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Langues'])[1]/following::a[3]</value>
      <webElementGuid>f62ff809-f7dc-4576-b7f2-f98b1f23b275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='direct'])[1]/preceding::a[2]</value>
      <webElementGuid>6e4a8355-8da0-4679-85cc-f2c150caf57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='entreprise'])[1]/preceding::a[2]</value>
      <webElementGuid>643450c1-0b32-444b-8b96-87b9af57d551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mon compte']/parent::*</value>
      <webElementGuid>68049ac1-a7c3-4e9e-b634-c8980456d556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>6c361c01-f138-4836-9632-f21d08acd41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>e64457d4-05f5-40c1-9f9c-e76bafef4b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Mon compte' or . = 'Mon compte')]</value>
      <webElementGuid>3ad43c8b-60a4-4a57-945d-6096c927d221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
