<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Compte activ_img-responsive</name>
   <tag></tag>
   <elementGuidId>38a033f2-5f3d-4784-935e-c0918002930d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='googleAuth']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9272ca10-77e7-4d71-95f9-e7abbb97d8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQAQAAAACoxAthAAACW0lEQVR42u2cQXLsMAhEuQH3vyU3%0AIP9b0CBnXKkshBdpT2Wc2HreUEJNY0X814cQIUKECBEifw4xuQ5103+f6+z/T45fMILIJKKet0Xz%0AJOsciNY4InNIjlXETtf4K4xaI4i8gFhiCzRtYSbyJoJgXrluJcIfQknkIJLfpvis9WdLekSGkRAC%0A9vx5UhdEDiJ1WFxGUKXS34MaJ3IMSfWsIRDWehTha4KByDCSo1DjLHGNh2BpIjKKrMSHW1nkNBln%0AqHuIDCJV5Hgrc1I+eOk3IpNICYJIeFrzLGZePoTIICJReuIuzBsUp99UH5HzCIZEFoTDttaliPZt%0AihE5juSU0sxzW+5zg2NAZBYRrEelGuqv5g8QmUTyqmhr2pRmEC1vmsgcUvJ699UEj8jLREYRw3qk%0AUd9Yn1lB9ZKHyABSolq9ZDSEdsi49G6ITCFupdMsVcN6gqWeM/U9+kQGkEu4bRkuPU/ZdQKRaUQh%0Ao6ESpE8zeJ1EJhG0Bm5uAUbfUx+R80hmvR5DLRe6XyAyiISx2W0aw6uBui1IRAaRbmm2LkH21WDs%0AEBlFrF43g6cGLzqnWlqgROaQtNPSRkMpiki2WpTILII1CY5z/qhXO5rIIJI6ofYBaG/jNPlAZBjx%0AMjb7Lo3o38inUBI5jHQbelcJXgb0viQRGUDw6qxs97L5Kc1/JjKJ6F1et7q0vX72YYsZkaMIFEFv%0A2UhPhkLkRSTHQrSVLW1E3kRQ5rTtZt47aUQGEW+tzTJpMrLZwvmw+4nISQS5rSoeqXf/b3tmiEwh%0A/E8URIgQIUKEyOPxBcWqBtX8T7YXAAAAAElFTkSuQmCC</value>
      <webElementGuid>c7f46b22-d4a3-490b-8762-21b7f03fb77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>008273d1-10fa-40a3-83a8-6e4b744dab0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7ccc78bd-a6fa-4811-a455-0fd503ce0ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;googleAuth&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12 form-content&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>713354b5-d881-4aa1-a22d-466cd21dac9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='googleAuth']/div/div/img</value>
      <webElementGuid>7ac321ae-4e66-41ed-8fdc-3ee3e842e9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQAQAAAACoxAthAAACW0lEQVR42u2cQXLsMAhEuQH3vyU3%0AIP9b0CBnXKkshBdpT2Wc2HreUEJNY0X814cQIUKECBEifw4xuQ5103+f6+z/T45fMILIJKKet0Xz%0AJOsciNY4InNIjlXETtf4K4xaI4i8gFhiCzRtYSbyJoJgXrluJcIfQknkIJLfpvis9WdLekSGkRAC%0A9vx5UhdEDiJ1WFxGUKXS34MaJ3IMSfWsIRDWehTha4KByDCSo1DjLHGNh2BpIjKKrMSHW1nkNBln%0AqHuIDCJV5Hgrc1I+eOk3IpNICYJIeFrzLGZePoTIICJReuIuzBsUp99UH5HzCIZEFoTDttaliPZt%0AihE5juSU0sxzW+5zg2NAZBYRrEelGuqv5g8QmUTyqmhr2pRmEC1vmsgcUvJ699UEj8jLREYRw3qk%0AUd9Yn1lB9ZKHyABSolq9ZDSEdsi49G6ITCFupdMsVcN6gqWeM/U9+kQGkEu4bRkuPU/ZdQKRaUQh%0Ao6ESpE8zeJ1EJhG0Bm5uAUbfUx+R80hmvR5DLRe6XyAyiISx2W0aw6uBui1IRAaRbmm2LkH21WDs%0AEBlFrF43g6cGLzqnWlqgROaQtNPSRkMpiki2WpTILII1CY5z/qhXO5rIIJI6ofYBaG/jNPlAZBjx%0AMjb7Lo3o38inUBI5jHQbelcJXgb0viQRGUDw6qxs97L5Kc1/JjKJ6F1et7q0vX72YYsZkaMIFEFv%0A2UhPhkLkRSTHQrSVLW1E3kRQ5rTtZt47aUQGEW+tzTJpMrLZwvmw+4nISQS5rSoeqXf/b3tmiEwh%0A/E8URIgQIUKEyOPxBcWqBtX8T7YXAAAAAElFTkSuQmCC')]</value>
      <webElementGuid>4423edea-47a5-4091-8f52-885269635b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>616c3b4d-a04a-4878-88f4-599e683b7c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQAQAAAACoxAthAAACW0lEQVR42u2cQXLsMAhEuQH3vyU3%0AIP9b0CBnXKkshBdpT2Wc2HreUEJNY0X814cQIUKECBEifw4xuQ5103+f6+z/T45fMILIJKKet0Xz%0AJOsciNY4InNIjlXETtf4K4xaI4i8gFhiCzRtYSbyJoJgXrluJcIfQknkIJLfpvis9WdLekSGkRAC%0A9vx5UhdEDiJ1WFxGUKXS34MaJ3IMSfWsIRDWehTha4KByDCSo1DjLHGNh2BpIjKKrMSHW1nkNBln%0AqHuIDCJV5Hgrc1I+eOk3IpNICYJIeFrzLGZePoTIICJReuIuzBsUp99UH5HzCIZEFoTDttaliPZt%0AihE5juSU0sxzW+5zg2NAZBYRrEelGuqv5g8QmUTyqmhr2pRmEC1vmsgcUvJ699UEj8jLREYRw3qk%0AUd9Yn1lB9ZKHyABSolq9ZDSEdsi49G6ITCFupdMsVcN6gqWeM/U9+kQGkEu4bRkuPU/ZdQKRaUQh%0Ao6ESpE8zeJ1EJhG0Bm5uAUbfUx+R80hmvR5DLRe6XyAyiISx2W0aw6uBui1IRAaRbmm2LkH21WDs%0AEBlFrF43g6cGLzqnWlqgROaQtNPSRkMpiki2WpTILII1CY5z/qhXO5rIIJI6ofYBaG/jNPlAZBjx%0AMjb7Lo3o38inUBI5jHQbelcJXgb0viQRGUDw6qxs97L5Kc1/JjKJ6F1et7q0vX72YYsZkaMIFEFv%0A2UhPhkLkRSTHQrSVLW1E3kRQ5rTtZt47aUQGEW+tzTJpMrLZwvmw+4nISQS5rSoeqXf/b3tmiEwh%0A/E8URIgQIUKEyOPxBcWqBtX8T7YXAAAAAElFTkSuQmCC']</value>
      <webElementGuid>22cc3af9-d3f2-417e-a920-6dd144844089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
