<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ENG_PTG508783_07_08_2023_signed.pdf</name>
   <tag></tag>
   <elementGuidId>7f7567ce-055e-4406-ac41-01c4239d4332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LE > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LE']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59fdd0e6-6276-472f-bbd1-1668197038fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://10.10.2.101:8080/Guichet/file?filename=ENG_PTG508783_07_08_2023_signed.pdf&amp;ice=alt.d4-bywr6lb@yopmail.com&amp;typeDM=LE</value>
      <webElementGuid>84542493-5a0e-4a66-919a-43a6eeec2b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b9897ee-444e-43a0-ad01-c949df3f7b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENG_PTG508783_07_08_2023_signed.pdf</value>
      <webElementGuid>e85d62a9-4711-4a4c-b4bf-26cd949a97f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LE&quot;)/a[1]</value>
      <webElementGuid>051d3ff2-c808-499b-a366-321e4425f3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LE']/a</value>
      <webElementGuid>c7eb721e-98de-4e23-860c-4db6b7a9d1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ENG_PTG508783_07_08_2023_signed.pdf')]</value>
      <webElementGuid>ff8a26d5-d1a9-4228-9ffc-4b6f8108eb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sélectionner'])[1]/following::a[1]</value>
      <webElementGuid>ed0985b0-e939-4243-9d1c-b63f4feccca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::a[2]</value>
      <webElementGuid>defefa1e-3f2e-4f61-93b1-f9fccbb18ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nous vous avons envoyé un code SMS de validation de compte . Veuillez le saisir ci-dessus'])[1]/preceding::a[5]</value>
      <webElementGuid>78587709-9a10-4081-a167-79c1be4ef5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ENG_PTG508783_07_08_2023_signed.pdf']/parent::*</value>
      <webElementGuid>c6c30186-7dbf-4fbd-9a1b-25b21712e9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://10.10.2.101:8080/Guichet/file?filename=ENG_PTG508783_07_08_2023_signed.pdf&amp;ice=alt.d4-bywr6lb@yopmail.com&amp;typeDM=LE']</value>
      <webElementGuid>a6a0e9ef-5b03-480c-bd85-a4b5a9767b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>9d0f0968-f2dd-4622-b00b-e0e7b5e74ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://10.10.2.101:8080/Guichet/file?filename=ENG_PTG508783_07_08_2023_signed.pdf&amp;ice=alt.d4-bywr6lb@yopmail.com&amp;typeDM=LE' and (text() = 'ENG_PTG508783_07_08_2023_signed.pdf' or . = 'ENG_PTG508783_07_08_2023_signed.pdf')]</value>
      <webElementGuid>5e0681bb-ecce-4094-9c91-f9aa81d6d413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
