<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ENG_PTG508783_07_08_2023_signed.pdf_v_f41fb4</name>
   <tag></tag>
   <elementGuidId>8b198421-e398-436c-aa83-fb7342e61290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='validationCodeGoogleAuthForm:j_id61']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>028436e7-8460-4982-8294-36f8064beb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>ad2cba86-f0f1-4a31-99d9-6806ff879a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id61</value>
      <webElementGuid>9b963661-46f3-44f6-8ac4-08175471b350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>validationCodeGoogleAuthForm:j_id61</value>
      <webElementGuid>55c4a22e-a970-4e49-80e6-6d95eda81ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('validationCodeGoogleAuthForm',event,{'similarityGroupingId':'validationCodeGoogleAuthForm:j_id61','oncomplete':function(request,event,data){if('false'=='true'){document.getElementById('confirmAdhesion:popup_success').component.show();}},'parameters':{'validationCodeGoogleAuthForm:j_id61':'validationCodeGoogleAuthForm:j_id61'} } );return false;</value>
      <webElementGuid>7d00c708-4a0b-49cb-8fd9-57b5f41a85fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>f4f721c2-f2db-4c8b-bd1d-12f1510e90bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb756235-4e08-4166-b059-9d1ee3b06f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5328d251-7f88-46ff-9ffd-b2d3e6c34b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3402c85-e7bf-4d06-9ae2-99436bb9f8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCodeGoogleAuthForm:j_id61&quot;)</value>
      <webElementGuid>9a24721d-08a3-47c3-aa65-57b3a5961c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='validationCodeGoogleAuthForm:j_id61']</value>
      <webElementGuid>82807e60-26e1-4257-9a24-1908419b5398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='validationCodeGoogleAuthForm:panelsmspj']/div/div/div[3]/input</value>
      <webElementGuid>5e208a13-0c84-4758-bfbe-31e08a9ae533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6031ae45-11c5-4631-9f23-dbe86c95ef62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'validationCodeGoogleAuthForm:j_id61' and @name = 'validationCodeGoogleAuthForm:j_id61' and @type = 'button']</value>
      <webElementGuid>ea7601f3-8136-4409-87b2-d62fb41c0163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
