<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OK_confirmAdhesionformPieceJointeferm_4a0d9f</name>
   <tag></tag>
   <elementGuidId>fae471b0-10ec-46f5-999d-45ca1a91c4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/form[1]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de2e0b7a-c63d-4624-add3-157ea9d6ed7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmAdhesion:formPieceJointe:fermerDamande</value>
      <webElementGuid>7dfea2c8-173b-421b-a0d0-3a6e14fcff43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d2867fa9-f86e-4bea-8445-4639aa89a081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmAdhesion:formPieceJointe:fermerDamande</value>
      <webElementGuid>ed78a75f-2e88-4f74-80a2-0cd0639dd36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>6212eca8-044a-40d4-acf6-32b0c32b9736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>1a6ea70c-9294-4ef9-975d-bd9ef4166745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1fe2faac-caca-46f3-a02e-b0be33896375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmAdhesion:popup_successContentTable&quot;)/tbody[1]/tr[1]/td[@class=&quot;rich-mpnl-body&quot;]/span[@id=&quot;confirmAdhesion:modalContent&quot;]/form[@id=&quot;confirmAdhesion:formPieceJointe&quot;]/div[1]/input[@id=&quot;confirmAdhesion:formPieceJointe:fermerDamande&quot;]</value>
      <webElementGuid>c8904429-c90f-4ef9-8825-5b9fa41e117a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='confirmAdhesion:formPieceJointe:fermerDamande'])[2]</value>
      <webElementGuid>d02a6422-4e92-4f71-afe5-ff2770d9b5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='confirmAdhesion:formPieceJointe']/div/input)[2]</value>
      <webElementGuid>4265b85b-73c9-4612-a9ee-ac32b4e9c33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/table/tbody/tr/td/span/form/div/input</value>
      <webElementGuid>1941ba5a-95e2-4b01-ba07-640ff84a0b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmAdhesion:formPieceJointe:fermerDamande' and @type = 'submit' and @name = 'confirmAdhesion:formPieceJointe:fermerDamande']</value>
      <webElementGuid>315ad7f6-5969-47f8-b534-2c461630c759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
