<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lactivation de votre compte est en cou_39db1c</name>
   <tag></tag>
   <elementGuidId>6f740b2a-e308-4954-986d-61df7c66a31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//form[@id='confirmAdhesion:formPieceJointe']/span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0bacd73e-8de9-430c-9519-15f6186a17dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7eed672b-5e3c-4f53-8d76-b938efc6b7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>L'activation de votre compte est en cours. Vous serez notifiés dès qu'elle sera opéré afin de poursuivre votre authentification.</value>
      <webElementGuid>46045282-0255-4e9a-92a9-33a0b24b2eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmAdhesion:popup_successContentTable&quot;)/tbody[1]/tr[1]/td[@class=&quot;rich-mpnl-body&quot;]/span[@id=&quot;confirmAdhesion:modalContent&quot;]/form[@id=&quot;confirmAdhesion:formPieceJointe&quot;]/span[1]</value>
      <webElementGuid>caf331b2-9634-458d-9eb6-ffab8e86248a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='confirmAdhesion:formPieceJointe']/span)[2]</value>
      <webElementGuid>4a8d7ae8-9aaf-404b-bc1e-ff876b453465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::span[2]</value>
      <webElementGuid>7f477151-77a1-4a1e-a8a0-448d259c32c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Données personnelles'])[1]/following::span[3]</value>
      <webElementGuid>011c4ec2-4ec9-4256-a8ab-4c097d627414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/table/tbody/tr/td/span/form/span</value>
      <webElementGuid>94d61c77-0dea-415e-b8bc-314cb21e6dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;L&quot; , &quot;'&quot; , &quot;activation de votre compte est en cours. Vous serez notifiés dès qu&quot; , &quot;'&quot; , &quot;elle sera opéré afin de poursuivre votre authentification.&quot;) or . = concat(&quot;L&quot; , &quot;'&quot; , &quot;activation de votre compte est en cours. Vous serez notifiés dès qu&quot; , &quot;'&quot; , &quot;elle sera opéré afin de poursuivre votre authentification.&quot;))]</value>
      <webElementGuid>1eeca75b-d1f4-4cc5-918a-fba82d2f3d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
