<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1980</name>
   <tag></tag>
   <elementGuidId>95957fd8-ec4f-4b2a-9832-91b892db5eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcddb943-ed97-4754-98ce-6ff23e10d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1</value>
      <webElementGuid>be2e40b7-ea8d-4010-b62f-797f763047c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-editor-btn rich-calendar-editor-btn-over</value>
      <webElementGuid>d13131fa-3c62-45cd-8baf-4e154a3b18b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>Element.addClassName(this, 'rich-calendar-editor-btn-over');</value>
      <webElementGuid>690f7be5-3154-4fb1-9a49-c6a110d4102b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>Element.removeClassName(this,'rich-calendar-editor-btn-over');</value>
      <webElementGuid>037a754f-9ca6-4249-aeb2-0aa5c4871781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('demandeAdhesionAnonymeForm:dateNaissance').component.dateEditorSelectYear(1);</value>
      <webElementGuid>1c8dce5f-5c49-4907-a470-57fed6e92629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1980</value>
      <webElementGuid>f3a07977-1f8e-46ba-a979-45983c81bd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1&quot;)</value>
      <webElementGuid>a1f61f79-bf01-4a33-9669-74799d9e3b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1']</value>
      <webElementGuid>07a56cd5-8dae-4c12-baad-60df3b5a758a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayout']/tbody/tr[3]/td[3]/div</value>
      <webElementGuid>dc05e22e-43ce-48ef-9286-22f8f71a3793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sept.'])[1]/following::div[1]</value>
      <webElementGuid>70ebd6ae-ee81-4d94-9d9a-23f3be939708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mars'])[1]/following::div[2]</value>
      <webElementGuid>913e25dd-452d-4f8e-9025-4978df7619bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='avr.'])[1]/preceding::div[2]</value>
      <webElementGuid>077d5919-c425-4672-b1c6-500d0c4c0c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oct.'])[1]/preceding::div[3]</value>
      <webElementGuid>dc7d178b-66ff-42ae-a7fa-75b96f7ab344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1980']/parent::*</value>
      <webElementGuid>2e76f671-c74c-40fc-a1c7-45e7b49fa1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div</value>
      <webElementGuid>e24f9f6c-1d10-45fd-9b30-5a11d4d5d8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1' and (text() = '1980' or . = '1980')]</value>
      <webElementGuid>f34a3c30-b332-4d02-8b29-8e97151c07fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
