<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OK</name>
   <tag></tag>
   <elementGuidId>9444aca0-51f0-4633-a38d-256a1b683f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorButtonOk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48d0f5c3-e39f-43a1-bf66-57db86c43d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:dateNaissanceDateEditorButtonOk</value>
      <webElementGuid>7bb470ec-7260-4f3a-9ec1-6b76f76cbc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-time-btn</value>
      <webElementGuid>eda71e66-c1e3-4685-bbbf-cc09bdd7b04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>Element.addClassName(this, 'rich-calendar-time-btn-press');</value>
      <webElementGuid>10a7be21-5293-4c2a-b6bb-f21449b464f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>Element.removeClassName(this, 'rich-calendar-time-btn-press');</value>
      <webElementGuid>5dfe6ec7-916c-4537-b92d-9e970ae2a1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseup</name>
      <type>Main</type>
      <value>Element.removeClassName(this, 'rich-calendar-time-btn-press');</value>
      <webElementGuid>7befc746-aa78-4991-bae1-732bef1cb0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('demandeAdhesionAnonymeForm:dateNaissance').component.hideDateEditor(true);</value>
      <webElementGuid>a816891d-5f4a-4fae-8d5b-ce90914fa3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>1b6890a2-de64-4227-b1e5-646214ca3d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:dateNaissanceDateEditorButtonOk&quot;)</value>
      <webElementGuid>3765acdd-7be2-445b-9bb9-8c80ab3a6ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorButtonOk']</value>
      <webElementGuid>54ec2b42-6d04-424e-b6da-25246471a211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayout']/tbody/tr[7]/td/div</value>
      <webElementGuid>d2769b57-ab08-4b83-9b12-473d5b08a158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='déc.'])[1]/following::div[3]</value>
      <webElementGuid>dfb9d9c7-7c66-4bda-9395-ee6d08e9b83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='juin'])[1]/following::div[4]</value>
      <webElementGuid>62c57239-3f7f-4e8b-8cd2-04b995acfb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>3173d631-ca53-4fc3-9829-9e3c24f61a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div</value>
      <webElementGuid>f2de0d87-bda8-40a5-aba2-c784b20f9e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'demandeAdhesionAnonymeForm:dateNaissanceDateEditorButtonOk' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>ae971190-16fe-46fd-a98d-59e120219144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
