<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1971</name>
   <tag></tag>
   <elementGuidId>3beca034-4169-4761-92b9-c6da5c813124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1971&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d48e908f-3df1-40c7-a676-fd8d023587fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1</value>
      <webElementGuid>674d5081-4f98-4476-9d67-f37ac9b9baf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-editor-btn rich-calendar-editor-btn-over</value>
      <webElementGuid>ad79cbc8-d9df-4366-929b-be039b660111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>Element.addClassName(this, 'rich-calendar-editor-btn-over');</value>
      <webElementGuid>0df70986-5d06-4f1c-a59c-f120be358531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>Element.removeClassName(this,'rich-calendar-editor-btn-over');</value>
      <webElementGuid>79b201ad-4169-4db0-ab71-bb7793aab5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('demandeAdhesionAnonymeForm:dateNaissance').component.dateEditorSelectYear(1);</value>
      <webElementGuid>0118f88e-528e-4396-b9cc-306504cab13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1971</value>
      <webElementGuid>29f661ff-aae8-4cdd-842d-b73f72466f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1&quot;)</value>
      <webElementGuid>11846f8e-a48a-4559-b276-5511166ad371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1']</value>
      <webElementGuid>40bf3fca-b748-441e-9469-422e542c3776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayout']/tbody/tr[3]/td[3]/div</value>
      <webElementGuid>fc9ad541-72ca-4b26-9b62-8b1b7a96b69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sept.'])[1]/following::div[1]</value>
      <webElementGuid>159cf06e-cfce-4af6-8ef5-790cc378ce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mars'])[1]/following::div[2]</value>
      <webElementGuid>26203f34-85fa-4209-be8b-17aeaf11502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='avr.'])[1]/preceding::div[2]</value>
      <webElementGuid>43cf6a52-499f-4739-9209-5c5e9f4e3499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oct.'])[1]/preceding::div[3]</value>
      <webElementGuid>f99ac4ab-a2e8-49ab-9b76-c4479dd379f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1971']/parent::*</value>
      <webElementGuid>417351fb-649a-4743-9a14-c6d4f340be9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div</value>
      <webElementGuid>0286b467-6a2f-4d02-b408-e9bfa8cb7bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'demandeAdhesionAnonymeForm:dateNaissanceDateEditorLayoutY1' and (text() = '1971' or . = '1971')]</value>
      <webElementGuid>6789ce21-a982-4613-9fac-2b73267d413b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
