<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Avoir pleinement conscience de ses ob_8c344e</name>
   <tag></tag>
   <elementGuidId>338a0714-ac57-449d-b602-b943ff97ae7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5af22da5-c8ff-43e0-8581-e523b3a20e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande</value>
      <webElementGuid>97ad8d82-bbb0-4bc5-a59a-ae00b60e04d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>50dd5846-8abc-4509-9067-0632ddb7a461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande</value>
      <webElementGuid>6bce4ecc-cd9c-4764-9600-5475d40c0c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>99572570-c1d5-4370-885d-048acde5fed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>d91d7e4f-d3e4-44a3-96fc-f167ca935ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0699f652-d538-4272-9e73-1a1ec3889570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande&quot;)</value>
      <webElementGuid>54542023-3c7c-46b2-9d98-60edeb8eea85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande']</value>
      <webElementGuid>711b7e72-4478-4266-b377-501ab19c5345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='confirmAdhesion:confirmAdhesion:formPieceJointe']/div/input</value>
      <webElementGuid>eeb4b9f2-5b3e-4f4b-b88a-2a364b1a6998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div[2]/table/tbody/tr/td/span/form/div/input</value>
      <webElementGuid>dface5ef-c802-4ea2-94ec-dc989f9e436f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande' and @type = 'submit' and @name = 'confirmAdhesion:confirmAdhesion:formPieceJointe:fermerDamande']</value>
      <webElementGuid>5b7aca2a-3792-4e48-a401-618bde1b0cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
