<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__demandeAdhesionAnonymeFormisHomme</name>
   <tag></tag>
   <elementGuidId>dd7b1e35-9304-4f20-9340-051e1ecb8840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:isHomme:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3519b47e-753f-4e56-b944-94bc682fcf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4e78c836-9325-4f42-92d8-9a0a3eec920e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:isHomme</value>
      <webElementGuid>b7a89145-532a-47ea-a05d-b5e6d2d76606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:isHomme:0</value>
      <webElementGuid>9a71660a-7c5a-4f93-a54d-8e61da679cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39433150-cf5c-4def-8879-3e1277c56919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>199c88b7-b6ad-47f1-8535-a2cb1977ced0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:isHomme:0&quot;)</value>
      <webElementGuid>81c0200d-c127-49f1-b39e-8c7f120643f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:isHomme:0']</value>
      <webElementGuid>788e48cc-2151-4421-983e-7158d735d99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:isHomme']/tbody/tr/td/input</value>
      <webElementGuid>0fe56908-f2cf-45e6-983f-1be3b22db59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>66580006-4a60-4328-858c-229788dd9d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'demandeAdhesionAnonymeForm:isHomme' and @id = 'demandeAdhesionAnonymeForm:isHomme:0']</value>
      <webElementGuid>0e3bfbbc-d163-4081-af73-3e0a7a3f1a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
