<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supprimer tout_demandeAdhesionAnonyme_1e55dd</name>
   <tag></tag>
   <elementGuidId>f9df7639-a9ac-4e5d-ad20-0fa463dca142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:listPiecesAJoindre:0:fileUploadAttachement:file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c90da6e-2908-4760-bc7c-48883b26296c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:checkValide</value>
      <webElementGuid>141231b6-17bd-4312-a8dc-e602a3dbf546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>608ba85c-43f7-448e-b520-1ff89b36396b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:checkValide</value>
      <webElementGuid>dd91ada7-0f96-4cb3-a97b-11e61450db02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>J'accepte et j'approuve les conditions générales d'utilisation du service.</value>
      <webElementGuid>7c722237-aac3-49c8-943f-f7c45cbd4430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d1b65c98-73bc-4fe2-b030-42e32a42b725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:checkValide&quot;)</value>
      <webElementGuid>34dc7e11-f6d2-4e46-8339-e712237665b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:checkValide']</value>
      <webElementGuid>6f6df2de-54b9-4ae3-9751-0ef9ab854681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:j_id193_body']/div/label/input</value>
      <webElementGuid>1e27b29f-b7f2-4f93-83c4-f26439528d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>9fb1b241-4bb3-43bb-91d9-24a351f2dd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'demandeAdhesionAnonymeForm:checkValide' and @type = 'checkbox' and @name = 'demandeAdhesionAnonymeForm:checkValide' and @title = concat(&quot;J&quot; , &quot;'&quot; , &quot;accepte et j&quot; , &quot;'&quot; , &quot;approuve les conditions générales d&quot; , &quot;'&quot; , &quot;utilisation du service.&quot;)]</value>
      <webElementGuid>e7916ba3-7514-4368-8313-cc91cfcf4492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
