<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annuler_demandeAdhesionAnonymeFormval_c69a65</name>
   <tag></tag>
   <elementGuidId>ada0b9d0-a043-41c9-bbb2-036d809ea6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:validTermes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Valider&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccb97f3c-a9af-4240-8486-c8e1fa96bad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-suivant col-md-6</value>
      <webElementGuid>517ef7f2-f18d-4d05-8e66-82ee20e8a8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:validTermes</value>
      <webElementGuid>b2118efd-754a-4d5e-b38c-2b7acb3f5d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:validTermes</value>
      <webElementGuid>20226d44-c69a-4e6e-8ac5-243dfdc7ca74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setNumberFunction();setTimeout('document.getElementById(\'demandeAdhesionAnonymeForm:validTermes\').disabled=true;', 50);;A4J.AJAX.Submit('demandeAdhesionAnonymeForm',event,{'similarityGroupingId':'demandeAdhesionAnonymeForm:validTermes','oncomplete':function(request,event,data){if('false'=='true'){                     document.getElementById('confirmAdhesion:panelConfirmTermes').component.show();};setTimeout('document.getElementById(\'demandeAdhesionAnonymeForm:validTermes\').disabled=false;', 50);},'parameters':{'demandeAdhesionAnonymeForm:validTermes':'demandeAdhesionAnonymeForm:validTermes'} } );return false;</value>
      <webElementGuid>837c8d03-db88-4bc8-b5fe-08a26d3e9342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>68e7e904-08d1-4337-bdb8-23dffb34f2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed35c803-875b-420c-994f-2b459e516501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cfcf5ccd-8806-49e0-befb-7105f958f563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>488e9a57-8d2a-4bfc-9a6e-564b1d7d72b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:validTermes&quot;)</value>
      <webElementGuid>e60382cc-8ecd-4a82-8343-97dc6e504db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:validTermes']</value>
      <webElementGuid>d9cc4fa3-90ef-4448-9458-2d7fe93388bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:j_id44_body']/div/div[2]/input[2]</value>
      <webElementGuid>bfaf135b-c4c0-44fe-9132-df325f32445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>b48a53e0-e343-44ff-9a20-dbf22425b7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'demandeAdhesionAnonymeForm:validTermes' and @name = 'demandeAdhesionAnonymeForm:validTermes' and @type = 'button']</value>
      <webElementGuid>b596022e-68d2-498b-866d-42f336b1bec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
