<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Avoir pleinement conscience de ses ob_4bbe4c</name>
   <tag></tag>
   <elementGuidId>66d34d38-e7bd-4d64-a20e-7bdfa7360c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmAdhesion:formPieceJointe:accepterTerme']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;J'accepte&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eee3bba-1cc6-486e-99f1-7e07f8aa1817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion next</value>
      <webElementGuid>7f54d3a3-af0d-4259-b4c1-f7d21345d678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmAdhesion:formPieceJointe:accepterTerme</value>
      <webElementGuid>28ff9eab-9acc-43fe-8cc3-83cb153679cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmAdhesion:formPieceJointe:accepterTerme</value>
      <webElementGuid>a63e4de6-afb3-4a0b-a579-4a35ac8fcfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('confirmAdhesion:formPieceJointe',event,{'similarityGroupingId':'confirmAdhesion:formPieceJointe:accepterTerme','oncomplete':function(request,event,data){if('false'=='true'){document.getElementById('confirmAdhesion:confirmAdhesion:panelConfirmdemandeAjout').component.show();}},'parameters':{'confirmAdhesion:formPieceJointe:accepterTerme':'confirmAdhesion:formPieceJointe:accepterTerme'} } );return false;</value>
      <webElementGuid>20a0bb5a-4167-4f8f-9ca1-09aa235fb8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>J'accepte</value>
      <webElementGuid>b75944ee-a0c8-4ae9-b25f-fd32996a30a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad558f20-45b1-4ca1-842d-db580c5074fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5a2a6007-ec20-4473-80bf-7562f8c5d681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmAdhesion:formPieceJointe:accepterTerme&quot;)</value>
      <webElementGuid>ce825f15-7eeb-4472-a633-f09da96da47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmAdhesion:formPieceJointe:accepterTerme']</value>
      <webElementGuid>c10e2512-12e0-42a1-8e01-b739740b5b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='confirmAdhesion:formPieceJointe']/div[2]/input</value>
      <webElementGuid>126ac077-56c8-4681-a8bc-ddfa77404e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>5822fa9d-070c-4ad7-81dd-2f356e1d5845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmAdhesion:formPieceJointe:accepterTerme' and @name = 'confirmAdhesion:formPieceJointe:accepterTerme' and @type = 'button']</value>
      <webElementGuid>fdddabd3-c65d-4793-9754-f740dfa7c82b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
