<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__demandeAdhesionAnonymeFormdateNaissa_7ea77a</name>
   <tag></tag>
   <elementGuidId>8bc71845-21d8-482a-8a81-e2efef93a67e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:dateNaissanceInputDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a865885-5dd7-4a9a-8b67-c4ef700dc0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input </value>
      <webElementGuid>35fc5042-0c09-4251-bdbd-41d9e68eaaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:dateNaissanceInputDate</value>
      <webElementGuid>8bc9e936-4fab-4655-8609-44150f81d1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:dateNaissanceInputDate</value>
      <webElementGuid>c9d38e44-1112-4edb-a594-50acaec48e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0656db72-39a0-4961-98e8-aba4b19c20c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e095a84b-b6a7-48b4-86b1-10381baec08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b5846243-2c95-4b9e-96ee-2f518d2d9bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:dateNaissanceInputDate&quot;)</value>
      <webElementGuid>1851b909-7ddf-4be2-91aa-17749b72c874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:dateNaissanceInputDate']</value>
      <webElementGuid>04cca4e1-9cdf-4263-9fcc-2ab5fe7c8c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='demandeAdhesionAnonymeForm:dateNaissancePopup']/input</value>
      <webElementGuid>fcc8cb6a-2b2a-4e40-b15c-d94556960d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>67382070-afa5-4001-ac33-b30fc4270f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'demandeAdhesionAnonymeForm:dateNaissanceInputDate' and @name = 'demandeAdhesionAnonymeForm:dateNaissanceInputDate' and @type = 'text']</value>
      <webElementGuid>788c2e2c-04d6-472d-87b7-a4a933a09cfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
