<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supprimer tout_btn btn-suivant btn-ne_dcf575</name>
   <tag></tag>
   <elementGuidId>3715c0e3-a6f8-454e-aa36-4c7f8491f6db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-suivant.btn-next.col-md-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Suivant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>149945f8-1164-4f5c-b5b5-bb7754cb35d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84957fcb-d364-4593-b16a-1c4446e183c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-suivant btn-next col-md-6</value>
      <webElementGuid>3c8d517e-8c10-486f-b275-53dfb1be8988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>2d0b77d3-d697-47c4-9759-cc6b96098901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>17ffa8bd-c717-46e3-ac68-90778b81303b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5435cc0d-b8b8-41d3-bec0-946bec1ea40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:j_id44_body&quot;)/div[@class=&quot;col-md-12 text-center form-group&quot;]/div[@class=&quot;btnInfoCompte&quot;]/input[@class=&quot;btn btn-suivant btn-next col-md-6&quot;]</value>
      <webElementGuid>3530a12b-519e-46ac-855f-158bf688fb02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Suivant']</value>
      <webElementGuid>b78f96fe-9dde-4517-abb0-20da3f6b0daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:j_id44_body']/div/div/input[2]</value>
      <webElementGuid>9a5bbada-8025-455b-9192-103ebfcc9cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>8c49dfe5-c5d0-4b97-800b-3f41d9cb64e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>f4aa95ea-3929-46d6-91a6-9a9486867a60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
