<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_casablanca</name>
   <tag></tag>
   <elementGuidId>4863c54a-f6c5-469e-b5d8-3a9ffd8243c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loadingPopupDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;demandeAdhesionAnonymeForm:refProvince&quot;]/option[14]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd0a6164-4776-4ef4-ba46-be7a1e24bfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-mpnl-mask-div-opaque rich-mpnl-mask-div</value>
      <webElementGuid>08fc850a-bc0f-4201-a062-6e5c7a9633b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loadingPopupDiv</value>
      <webElementGuid>e7584a90-9438-497d-bbef-90789a74773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3164acea-fbee-401a-b170-ea03c715f2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadingPopupDiv&quot;)</value>
      <webElementGuid>fc4cd6b1-e327-4245-ac91-8a75f65438de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loadingPopupDiv']</value>
      <webElementGuid>c40b105f-23b9-43e3-ad76-721bf3394669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loadingPopupContainer']/div</value>
      <webElementGuid>35ccd30b-d2cd-4c90-b6b1-c89875207c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'loadingPopupDiv', '&quot;', ')')])[1]/following::div[2]</value>
      <webElementGuid>4cfc37cc-df57-4a8c-a55e-e40eb570789e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::div[4]</value>
      <webElementGuid>ea261413-1fcd-457d-89c7-5a1e9d22918f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>732346dd-8991-4a78-81f8-4a407a7d5897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loadingPopupDiv']</value>
      <webElementGuid>0ac0f4b1-3d75-45cd-91e6-5f8b6f2b1225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
