<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Al-FidaAnfaAssoukhour AssawdaAn-Choc_d721e0</name>
   <tag></tag>
   <elementGuidId>577d47bc-5eac-490d-8f3a-f678ead206b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;demandeAdhesionAnonymeForm:refCommune&quot;]/option[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>94b2b0a9-4bd2-4699-bba8-7c4b00e067ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
      <webElementGuid>314364c8-d6f0-454e-b6d2-0d0e25433df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:refCommune</value>
      <webElementGuid>4367ba8f-88f3-4c31-89b6-ea753d6c3b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:refCommune</value>
      <webElementGuid>f066f7d9-8fd5-44e7-9d3a-64d49c4aa587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>69444746-66ec-4293-b4bf-706686bf068a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7aea7cf4-83c9-426b-87ab-ed26c5e1e9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('demandeAdhesionAnonymeForm',event,{'similarityGroupingId':'demandeAdhesionAnonymeForm:j_id124','parameters':{'demandeAdhesionAnonymeForm:j_id124':'demandeAdhesionAnonymeForm:j_id124'} } )</value>
      <webElementGuid>ef932714-a116-4cf9-a7c0-5ecbdac8642c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane</value>
      <webElementGuid>57b4edb5-39d4-4efd-98c6-92c9dba0c0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:refCommune&quot;)</value>
      <webElementGuid>2acb5227-eeec-4f55-b45f-7e417dbcba56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='demandeAdhesionAnonymeForm:refCommune']</value>
      <webElementGuid>99a22a67-cf9b-415f-a79f-985f4c1a510d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:outputPanelVille']/div[2]/select</value>
      <webElementGuid>3891d2ff-ff2e-45ce-9dac-246020f49cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>f1919231-d1a3-41a9-a708-0486070d7be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code postal'])[1]/preceding::select[1]</value>
      <webElementGuid>adad9172-9c10-4591-a6b2-447b4bd3be45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>ecc3602a-9ef1-4c97-a75b-d7867d8d988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'demandeAdhesionAnonymeForm:refCommune' and @name = 'demandeAdhesionAnonymeForm:refCommune' and (text() = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane' or . = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane')]</value>
      <webElementGuid>7a2b4198-af28-45a6-9999-46fa728de1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
