<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_7</name>
   <tag></tag>
   <elementGuidId>052ead76-7901-4ba3-835f-cc369b00082d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='demandeAdhesionAnonymeForm:dateNaissanceDayCell10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f7a13212-66c0-4167-833e-c8ded839d8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-cell-size rich-calendar-cell rich-calendar-btn rich-calendar-hover</value>
      <webElementGuid>17dc6995-565f-4cbf-83ab-1dcab1ee7bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:dateNaissanceDayCell10</value>
      <webElementGuid>5851ec2e-341f-4024-9f0e-1085d2b1eb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('demandeAdhesionAnonymeForm:dateNaissance').component.eventCellOnClick(event, this);</value>
      <webElementGuid>7b1dc1e1-48f1-4795-a130-c35b098a9344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>$('demandeAdhesionAnonymeForm:dateNaissance').component.eventCellOnMouseOver(event, this);</value>
      <webElementGuid>5f63f348-9176-43e3-96db-07e83a89395e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>$('demandeAdhesionAnonymeForm:dateNaissance').component.eventCellOnMouseOut(event, this);</value>
      <webElementGuid>a05f75e2-997e-470f-84f0-0f9090e98620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>667fedc3-7914-41eb-ad93-40170cc9d39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>f703822b-36f3-4946-b179-bd4208e39235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:dateNaissanceDayCell10&quot;)</value>
      <webElementGuid>549594b0-656b-4a70-ab20-8a26a44a96a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='demandeAdhesionAnonymeForm:dateNaissanceDayCell10']</value>
      <webElementGuid>66864c79-9165-42fa-97fd-26a7a701116f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='demandeAdhesionAnonymeForm:dateNaissanceWeekNum2']/td[5]</value>
      <webElementGuid>c9ef8368-94a4-4f12-aec9-8f12236b5da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dim.'])[1]/following::td[13]</value>
      <webElementGuid>5336d733-3e79-4ad8-bdc1-12de1a29d93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sam.'])[1]/following::td[14]</value>
      <webElementGuid>dcb3d61f-3619-41bd-8e50-138bb28b7529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::td[40]</value>
      <webElementGuid>9f4d6c58-0ab4-4b3b-a3ce-597e8055d056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='janv.'])[1]/preceding::td[43]</value>
      <webElementGuid>931148e2-73a7-4b64-9377-5d5367ab48ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7']/parent::*</value>
      <webElementGuid>b8d9e548-b07c-4e44-b76a-a0cd5d957b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]</value>
      <webElementGuid>69fb4b5b-8080-4f77-a064-c5a433b0e324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'demandeAdhesionAnonymeForm:dateNaissanceDayCell10' and (text() = '7' or . = '7')]</value>
      <webElementGuid>53b86861-b9c7-4c9c-84a7-e01eeb0f9b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
