<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Pice dIdentit</name>
   <tag></tag>
   <elementGuidId>dc21de6b-4162-495e-ab70-b7cf1337aa74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='demandeAdhesionAnonymeForm:cinTab_lbl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;demandeAdhesionAnonymeForm\:cinTab_lbl&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e07bdac6-cddc-41a7-9f3a-1ecc21500f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:cinTab_lbl</value>
      <webElementGuid>1fd1a2c4-2773-484f-8fc1-a30b5c663334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>RichFaces.overTab(this);</value>
      <webElementGuid>1973fb2b-682b-40de-8da9-8b6e47dd323b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>RichFaces.outTab(this);</value>
      <webElementGuid>ae4b26b0-7137-4f0c-965b-2978c8f81b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-tab-header rich-tab-inactive rich-tbpnl-tb-sel</value>
      <webElementGuid>03f607bd-bc3e-4be4-b762-db4d46bf2462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>aeb71eae-d0cd-4d11-8250-b709738f17f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pièce d'Identité</value>
      <webElementGuid>0932d34f-70da-4dc6-8f8f-4d49a17e0df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:cinTab_lbl&quot;)</value>
      <webElementGuid>6dec96aa-35f9-47f2-973e-f613c0df7c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='demandeAdhesionAnonymeForm:cinTab_lbl']</value>
      <webElementGuid>dcf60dcb-68fb-4a55-abfd-405276acd43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:cinTab_shifted']/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>20fc027e-083b-43dd-b158-d6b4620336f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations du compte'])[1]/following::td[6]</value>
      <webElementGuid>737a7e96-c37f-46ad-8569-6f628cb7144c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Création De Compte'])[2]/following::td[12]</value>
      <webElementGuid>3d5fa681-7c7b-4a71-863e-716a7f19ec9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::td[3]</value>
      <webElementGuid>fd7e980b-15d2-4904-a185-7313f24faa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>679ae2db-46b5-44ab-ac71-f932015d9312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'demandeAdhesionAnonymeForm:cinTab_lbl' and (text() = concat(&quot;Pièce d&quot; , &quot;'&quot; , &quot;Identité&quot;) or . = concat(&quot;Pièce d&quot; , &quot;'&quot; , &quot;Identité&quot;))]</value>
      <webElementGuid>93ecde40-417b-43cd-9ded-88331d4fccf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
