<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multicanal_paiementFormcarteNational</name>
   <tag></tag>
   <elementGuidId>3ff7fee4-6c75-40b8-8b5e-6ee3113ec66a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paiementForm:carteNational:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>068d951e-2624-4602-9a62-b008287c2067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>71b4a96a-2209-4b61-92a6-9fbba7a34991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paiementForm:carteNational</value>
      <webElementGuid>1f10da9a-e0a4-4bec-a495-d76236845b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paiementForm:carteNational:0</value>
      <webElementGuid>be853544-a103-432e-9726-eac5ff5fa9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>carteNational</value>
      <webElementGuid>3ead1970-e668-45cb-9e6e-cc56837e5c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('paiementForm',event,{'similarityGroupingId':'paiementForm:j_id75','parameters':{'paiementForm:j_id75':'paiementForm:j_id75'} } )</value>
      <webElementGuid>7b0eeaae-9f26-4055-b268-458b9e157f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paiementForm:carteNational:0&quot;)</value>
      <webElementGuid>ce641649-6999-4986-9269-351b7df0b625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paiementForm:carteNational:0']</value>
      <webElementGuid>80619002-2881-4a0a-b1b3-11985f8952e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='paiementForm:carteNational']/tbody/tr/td/input</value>
      <webElementGuid>6f77d4fa-363a-4ee0-849b-ff4c2382774b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td/input</value>
      <webElementGuid>f9d4679a-56e9-4b5a-9eb8-724c0e4f4807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'paiementForm:carteNational' and @id = 'paiementForm:carteNational:0']</value>
      <webElementGuid>9a425c24-457c-4a45-b4d6-1151d3112d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
