<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carte bancaire_paiementFormfatouratiPm</name>
   <tag></tag>
   <elementGuidId>596a73bc-80c4-4b4e-8c7b-d023fef72a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paiementForm:fatouratiPm:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4e93e6d-aa67-42c7-9d4f-d3f57cc0d710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7c391d95-67a9-4bc3-9ebc-5b2c473a879a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paiementForm:fatouratiPm</value>
      <webElementGuid>f1108262-41b7-46e0-a9d5-9c1fca267a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paiementForm:fatouratiPm:0</value>
      <webElementGuid>bbcfdd72-4168-44fe-9252-73cfe00d0638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>fatourati</value>
      <webElementGuid>723c77b4-1dac-42ca-83a6-5ee39045c603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('paiementForm',event,{'similarityGroupingId':'paiementForm:j_id74','parameters':{'paiementForm:j_id74':'paiementForm:j_id74'} } )</value>
      <webElementGuid>a9f70cab-3e05-4906-8948-0a0d969c7642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c00c699a-4676-4560-8ae4-352523f97730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paiementForm:fatouratiPm:0&quot;)</value>
      <webElementGuid>99534e30-9884-4a4b-882b-a0fa84349174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paiementForm:fatouratiPm:0']</value>
      <webElementGuid>19b82c63-81b0-448e-a79a-f45ffbbf617f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='paiementForm:fatouratiPm']/tbody/tr/td/input</value>
      <webElementGuid>b221ac5a-874d-4a82-bfc1-08339be79dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/input</value>
      <webElementGuid>14c9f268-1d93-48e0-b1ae-50757b183ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'paiementForm:fatouratiPm' and @id = 'paiementForm:fatouratiPm:0']</value>
      <webElementGuid>3d7be5ee-3173-4eda-ac77-f17b80cc1751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
