<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numro du dossier_paiementFormcarte</name>
   <tag></tag>
   <elementGuidId>0451b8d8-5491-4b3c-acd1-a148d2d7b011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paiementForm:carte:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c61ba768-ecb8-4cf0-8226-6eedff3d7f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f3263161-9760-4728-bbe2-37337aa5466d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paiementForm:carte</value>
      <webElementGuid>3a0739d9-f8e1-4ee8-a913-77e4903dc68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paiementForm:carte:0</value>
      <webElementGuid>bd867e98-eca2-4b23-a5d7-c73367ae59ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>carte</value>
      <webElementGuid>ad9f96b6-7468-42ff-9aed-c19ffe158cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('paiementForm',event,{'similarityGroupingId':'paiementForm:j_id73','parameters':{'paiementForm:j_id73':'paiementForm:j_id73'} } )</value>
      <webElementGuid>eb8660f1-1ff4-42af-a31b-d598ccc1b4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d2d3c72a-9d04-4b1e-93db-bee5944d4eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paiementForm:carte:0&quot;)</value>
      <webElementGuid>f483f49f-b0ea-4e4b-8262-bbbb9b2ae7f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paiementForm:carte:0']</value>
      <webElementGuid>30bac0c2-1ffb-47d7-b7e4-cb83ba11fa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='paiementForm:carte']/tbody/tr/td/input</value>
      <webElementGuid>e3038061-42c6-40b2-bf1f-e2bb8a5ae9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a0368806-de17-4bda-90f2-4b122040c7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'paiementForm:carte' and @id = 'paiementForm:carte:0']</value>
      <webElementGuid>53457b32-876e-4b8e-ba82-e8e7648eba48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
