<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TOTAL A PAYER EN MAD_btn btn-connexion</name>
   <tag></tag>
   <elementGuidId>12a107c6-d31d-48d6-86f3-264bed35c267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-connexion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Valider']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3ee4dba-bab3-476e-adb8-d834ca67eb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>22fab92b-7779-47d8-9ca0-515974ca6838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>1847c9b6-3d47-4cea-8301-95006817d254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>0270004d-cebc-4fd5-b0ca-ca4262328975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validerPaiement&quot;)/form[@class=&quot;text-right&quot;]/input[@class=&quot;btn btn-connexion&quot;]</value>
      <webElementGuid>cb77810e-561f-40fa-bfe0-879786eb982c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Valider']</value>
      <webElementGuid>4cd2b6d4-dd63-4242-9b0b-c6b7788b701d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='validerPaiement']/form/input[46]</value>
      <webElementGuid>49040973-e205-4d1a-a8e9-cc463a44a0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[46]</value>
      <webElementGuid>cd4ad3ca-6c6a-4fa4-ae73-42c8c404409f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>68e093b5-a94f-405d-a9ae-5e2e50f9b26b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
