<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_liste des channels_paiementFormdownlo_d2a4cc</name>
   <tag></tag>
   <elementGuidId>b949a23e-afa4-4ddd-bae3-3d4dd54eb05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paiementForm:downloadRefFatourati']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dfa56fa-b8bb-4774-9e8c-b274eeb5d536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paiementForm:downloadRefFatourati</value>
      <webElementGuid>21f23c84-3bb7-4d82-9ef4-d00c224c55ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e79ed97d-7891-41cd-a624-75c4df46f256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paiementForm:downloadRefFatourati</value>
      <webElementGuid>10d4f4a7-573e-4a37-8671-8fd4ee5a3e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Télécharger la référence fatourati.</value>
      <webElementGuid>d3a847c2-459b-4b1c-9e94-b8f79cc8a285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Télécharger la référence fatourati.</value>
      <webElementGuid>745d89c9-82bf-44e5-afc9-af48f4329ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn imprimer</value>
      <webElementGuid>6881ae2a-b0e0-4f3e-bb7f-bfdf6df7cbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8b1abe29-927c-49eb-88cd-0dda0783e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paiementForm:downloadRefFatourati&quot;)</value>
      <webElementGuid>9c8b2a8d-e361-4e92-bc28-40e5c780a1a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paiementForm:downloadRefFatourati']</value>
      <webElementGuid>c5c170a6-10fc-4156-899b-78a176f7a643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paiementForm:j_id41_body']/div/div[2]/div/input</value>
      <webElementGuid>6242c140-1dee-49da-9ae0-fb7f877b2f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>4e5fbb1e-5124-429d-8303-9ffd4846bcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'paiementForm:downloadRefFatourati' and @type = 'submit' and @name = 'paiementForm:downloadRefFatourati' and @alt = 'Télécharger la référence fatourati.']</value>
      <webElementGuid>736b3455-14d2-4c79-b34b-a769d265cd56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
