<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Paiement</name>
   <tag></tag>
   <elementGuidId>055bf672-2a6c-45f5-a615-944e618cb924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.header2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paiementForm:j_id44_header']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96b034a5-2985-4696-9963-f310c1305584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header2</value>
      <webElementGuid>f92c236a-cb8a-4cd9-a20c-b82fd57de49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f07240bd-e22e-4bd6-9f92-d42026635b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paiement</value>
      <webElementGuid>1703a6da-5d47-416b-bfb3-0c071fd34cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paiementForm:j_id44_header&quot;)/span[@class=&quot;header2&quot;]</value>
      <webElementGuid>b3f2ae63-3e05-4c97-84c1-911aedb53dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paiementForm:j_id44_header']/span</value>
      <webElementGuid>989946fb-696a-4dd5-9c93-fd31ff946709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paiement'])[2]/following::span[1]</value>
      <webElementGuid>e7a7ac0d-20a0-44c9-afcb-87d441efa0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('La plateforme de création et d', &quot;'&quot;, 'accompagnement d', &quot;'&quot;, 'entreprises')])[1]/following::span[1]</value>
      <webElementGuid>85869d3d-e366-4aab-8211-787c73433597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carte bancaire'])[1]/preceding::span[3]</value>
      <webElementGuid>3725ebfe-1f19-4230-a8bc-900c08cf5ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/span</value>
      <webElementGuid>53ff0d86-3f61-4bb1-933e-fd0b9537533e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Paiement' or . = 'Paiement')]</value>
      <webElementGuid>0f32faf0-2ce3-4b79-8de9-0f2d4ebff492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
