<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_alt.g3-5o1w9gzryopmail.com</name>
   <tag></tag>
   <elementGuidId>85d667a7-2060-4421-8a12-263a3f468a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='autoaltcpt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autoaltcpt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54a5d8fb-bb7a-4a15-afd9-fc70304aad63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nw b</value>
      <webElementGuid>4e5e5ce0-0231-4d4c-af00-52b794228fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoaltcpt</value>
      <webElementGuid>a3787558-dcbe-4e3e-a1bc-563921f94ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>alt.g3-5o1w9gzr@yopmail.com</value>
      <webElementGuid>05e435bd-109f-4484-90ed-8d67a09937a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoaltcpt&quot;)</value>
      <webElementGuid>6f381c5a-e140-4635-8f74-2d618e5db0de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='autoaltcpt']</value>
      <webElementGuid>feb768db-4456-4a85-9c9b-fe104373b882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='webmail']/div/div/main/div/div/div[2]/span[2]</value>
      <webElementGuid>bdc1414c-bf46-4352-be7e-ea99fe55a90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::span[1]</value>
      <webElementGuid>8662ad3a-5163-41e1-9993-e6e0aa5d87a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[1]</value>
      <webElementGuid>d838ddb8-0d1c-4103-b309-b6e25eecfd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='@yopmail.com']/parent::*</value>
      <webElementGuid>6d3992bf-40d3-4bd2-b253-1ab166c54d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>a23723df-a333-4d4c-a80a-7c24f0ba416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'autoaltcpt' and (text() = 'alt.g3-5o1w9gzr@yopmail.com' or . = 'alt.g3-5o1w9gzr@yopmail.com')]</value>
      <webElementGuid>8d4525d0-0a09-4b43-afb6-6d2c77e04a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
