<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SMS_VALIDE_utilisateurProfFormlisteUt_1e015f</name>
   <tag></tag>
   <elementGuidId>f129237a-2581-4847-8e49-e640f3fdd659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='utilisateurProfForm:listeUtilisateurProf:0:visualiser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03c50e97-0a16-4a4c-b477-720d27ac08aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>utilisateurProfForm:listeUtilisateurProf:0:visualiser</value>
      <webElementGuid>0541875e-99c3-4efc-aad9-4bf1251a4179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>2717de93-5521-4a64-b35b-b54b2c40cf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images/commun/icone-view.gif</value>
      <webElementGuid>667d19ae-a922-4957-80bc-7a30d9faba54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utilisateurProfForm:listeUtilisateurProf:0:visualiser</value>
      <webElementGuid>d1529b05-9ceb-4c17-8344-586d14bf7cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>439a0c9e-bf2a-4a4c-bbb2-c83b07e2e575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;utilisateurProfForm:listeUtilisateurProf:0:visualiser&quot;)</value>
      <webElementGuid>209803d2-4094-4be5-9352-36db160d544b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='utilisateurProfForm:listeUtilisateurProf:0:visualiser']</value>
      <webElementGuid>af3f0d55-59c1-4a20-b550-14bf76939dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='utilisateurProfForm:listeUtilisateurProf:0:j_id96']/span/ul/input</value>
      <webElementGuid>12a843a3-9031-4940-bfd9-a13ed465f0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/input</value>
      <webElementGuid>2c4c242a-d590-4df0-8e64-7ca7b969934a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'utilisateurProfForm:listeUtilisateurProf:0:visualiser' and @type = 'image' and @src = '/Guichet/images/commun/icone-view.gif' and @name = 'utilisateurProfForm:listeUtilisateurProf:0:visualiser']</value>
      <webElementGuid>241f374a-9d32-4c2e-94f1-e54cbd6738b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
