<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type de compte_utilisateurProfFormrec_4af2c0</name>
   <tag></tag>
   <elementGuidId>518f5112-61c8-4ee2-83dc-63e441afcd9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='utilisateurProfForm:rechercherUtilisateurProf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d93308f-21e6-419e-90ee-a1db390f839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>14feb8fe-ebd5-4cf6-8606-4d28d68c9c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>utilisateurProfForm:rechercherUtilisateurProf</value>
      <webElementGuid>ca23f53d-644d-4d42-ade0-f0468ef5750d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utilisateurProfForm:rechercherUtilisateurProf</value>
      <webElementGuid>8a73b0a2-cfa7-4f35-8ffe-65af187eb5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('utilisateurProfForm',event,{'similarityGroupingId':'utilisateurProfForm:rechercherUtilisateurProf','parameters':{'utilisateurProfForm:rechercherUtilisateurProf':'utilisateurProfForm:rechercherUtilisateurProf'} } );return false;</value>
      <webElementGuid>714faaf9-8f60-4612-b955-55515ec18c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lancer la recherche</value>
      <webElementGuid>60f2c9cc-ab89-4394-812e-1625f02cc887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lancer la recherche</value>
      <webElementGuid>54d53af3-28fc-476f-8b8c-e611ee8bcf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2033988c-ada0-452f-af43-06c65c09ff45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d0d20c11-60d3-4f7e-9497-e66c80bd4462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;utilisateurProfForm:rechercherUtilisateurProf&quot;)</value>
      <webElementGuid>f5480537-16b2-4973-9b44-ef1a63ec2821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='utilisateurProfForm:rechercherUtilisateurProf']</value>
      <webElementGuid>38005755-0872-4f7c-8abd-09f6bf216de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='utilisateurProfForm:j_id45_body']/div[7]/input</value>
      <webElementGuid>d0ae0714-8e6d-4482-9e54-b3460125aeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>3a266319-a71a-4ca5-bead-7dc7dd50b2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'utilisateurProfForm:rechercherUtilisateurProf' and @name = 'utilisateurProfForm:rechercherUtilisateurProf' and @alt = 'Lancer la recherche' and @type = 'button']</value>
      <webElementGuid>b3f66a7e-19ea-4a40-9512-6081a548257b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
