<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Authentification</name>
   <tag></tag>
   <elementGuidId>33654d11-f43f-4148-848a-510d93adf07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-xs.page-title > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Partenaires'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Authentification&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7ed980b9-dbe4-415a-bde9-ed772814c173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>49cb62ae-2090-4927-a38d-69286f0f9397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authentification</value>
      <webElementGuid>f53419aa-a9d2-45b9-a778-35ba5ead05e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ltr&quot;]/body[1]/div[@class=&quot;page_content&quot;]/section[@class=&quot;login&quot;]/div[@class=&quot;container-xs page-title&quot;]/h1[1]</value>
      <webElementGuid>d0422350-82ad-48de-98a6-190502e6e8f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partenaires'])[1]/following::h1[1]</value>
      <webElementGuid>06f3a7ca-a321-4c85-a166-f4919d95eb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inscrit'])[1]/preceding::h1[1]</value>
      <webElementGuid>83440eca-f809-43a6-b1cb-dbc1e9dfa7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/h1</value>
      <webElementGuid>9a508c55-f348-4b87-aeeb-1953b36b5749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Authentification' or . = 'Authentification')]</value>
      <webElementGuid>525fd9bd-8ad9-4d54-8880-65db619f4d03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
