<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfimerMonchoix</name>
   <tag></tag>
   <elementGuidId>8267fa88-ca6f-40e9-a76e-2c9e27bacc52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmAdhesion:formPieceJointe:accepterTerme']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;J'accepte&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a411621d-ad3f-4a27-a8ca-a271bdad223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion next</value>
      <webElementGuid>15821e78-29f8-4ba4-a34d-f1ef07d35676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmAdhesion:formPieceJointe:accepterTerme</value>
      <webElementGuid>8b01b4b4-55c4-4858-8a08-e6322e2fd53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmAdhesion:formPieceJointe:accepterTerme</value>
      <webElementGuid>f2175f50-a28e-407c-ba82-ac829f010afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('confirmAdhesion:formPieceJointe',event,{'similarityGroupingId':'confirmAdhesion:formPieceJointe:accepterTerme','oncomplete':function(request,event,data){if('false'=='true'){document.getElementById('confirmAdhesion:confirmAdhesion:panelConfirmdemandeAjout').component.show();}},'parameters':{'confirmAdhesion:formPieceJointe:accepterTerme':'confirmAdhesion:formPieceJointe:accepterTerme'} } );return false;</value>
      <webElementGuid>cd21baa1-431c-449f-a852-ae7284e3343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>J'accepte</value>
      <webElementGuid>61fbf353-b234-4c5b-bcc2-9984023e6925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6957902-f1e6-4a1b-880f-60a3ddd4e787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ce9799cc-eb37-45d6-a450-db49d736b693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmAdhesion:formPieceJointe:accepterTerme&quot;)</value>
      <webElementGuid>cf2d550b-083f-4c81-bdb5-b1d092c3da8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmAdhesion:formPieceJointe:accepterTerme']</value>
      <webElementGuid>0eec73e0-eac4-4bb9-864e-a660f3409fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='confirmAdhesion:formPieceJointe']/div[2]/input</value>
      <webElementGuid>af659ede-b544-44a6-8a25-0b91364a6e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>f07e21ee-4fb6-4576-a4e4-41957dd5768b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmAdhesion:formPieceJointe:accepterTerme' and @name = 'confirmAdhesion:formPieceJointe:accepterTerme' and @type = 'button']</value>
      <webElementGuid>2ac66c3f-49d5-4dce-a97e-98c162830d9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
