<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supprimer tout_demandeAdhesionAnonyme_fbe7b2</name>
   <tag></tag>
   <elementGuidId>f1c85de9-8bd2-496f-9b1d-449b43ee7ab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='demandeAdhesionAnonymeForm:validTermes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Valider&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a43e140-aaab-4b4d-9446-78b3ce95a62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-suivant col-md-6</value>
      <webElementGuid>94003f0a-02d9-4d2b-92b9-60e679c1faa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:validTermes</value>
      <webElementGuid>d6e45a5d-4c91-425a-8f43-82d8bb2cb2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:validTermes</value>
      <webElementGuid>f51a5a76-049d-4ef8-8032-53ebca0866de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setNumberFunction();setTimeout('document.getElementById(\'demandeAdhesionAnonymeForm:validTermes\').disabled=true;', 50);;A4J.AJAX.Submit('demandeAdhesionAnonymeForm',event,{'similarityGroupingId':'demandeAdhesionAnonymeForm:validTermes','oncomplete':function(request,event,data){if('false'=='true'){                     document.getElementById('confirmAdhesion:panelConfirmTermes').component.show();};setTimeout('document.getElementById(\'demandeAdhesionAnonymeForm:validTermes\').disabled=false;', 50);},'parameters':{'demandeAdhesionAnonymeForm:validTermes':'demandeAdhesionAnonymeForm:validTermes'} } );return false;</value>
      <webElementGuid>31560b65-6150-4350-8e64-bfd492f8b84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>4d8c0327-dd81-4515-92a4-29004694cf0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea2e1abf-fe72-4637-9390-374b9dd73b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>310b2f63-2dc1-412a-a060-445aecee877a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:validTermes&quot;)</value>
      <webElementGuid>683f7c68-561c-43e0-91cf-0e477cbde8fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='demandeAdhesionAnonymeForm:validTermes']</value>
      <webElementGuid>a8a26f28-e210-49fb-b92d-8b6570c603a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demandeAdhesionAnonymeForm:j_id44_body']/div/div[2]/input[2]</value>
      <webElementGuid>b7050dda-d29d-4349-80be-f9b6b769f8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>ef00933c-2860-4e33-bf9e-f9541a0aba6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'demandeAdhesionAnonymeForm:validTermes' and @name = 'demandeAdhesionAnonymeForm:validTermes' and @type = 'button']</value>
      <webElementGuid>dd604249-4e93-4e6d-8db6-4da35bcc94a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
