<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Pice dIdentit</name>
   <tag></tag>
   <elementGuidId>e8a016d3-bf89-43cf-838a-ff7b3b54af23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='demandeAdhesionAnonymeForm:cinTab_lbl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;demandeAdhesionAnonymeForm\:cinTab_lbl&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dde2a987-3f57-4d4b-b013-1a5490a6e461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demandeAdhesionAnonymeForm:cinTab_lbl</value>
      <webElementGuid>85088d88-1719-499b-8a21-b99c34f7cb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>RichFaces.overTab(this);</value>
      <webElementGuid>d48c925f-2236-452a-aa22-e999f8ae89ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>RichFaces.outTab(this);</value>
      <webElementGuid>73d7c9fc-7a0a-4ddc-a2bd-91389b2895ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-tab-header rich-tab-inactive     rich-tbpnl-tb-sel</value>
      <webElementGuid>8c7256ab-52ff-46a0-a15e-c531fb2a09c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5d6968a2-1c8b-4808-a659-b9afab464778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pièce d'Identité</value>
      <webElementGuid>9d844c5c-43f2-4efc-b72e-729860e8a05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demandeAdhesionAnonymeForm:cinTab_lbl&quot;)</value>
      <webElementGuid>bdde4a13-905a-4309-8726-0747eeb76269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='demandeAdhesionAnonymeForm:cinTab_lbl']</value>
      <webElementGuid>570f1957-8fb8-4e77-bd85-6b2553dd896f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='demandeAdhesionAnonymeForm:cinTab_shifted']/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>b4c630d3-8385-42a0-91e0-b146ede2b180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations du compte'])[1]/following::td[6]</value>
      <webElementGuid>cc64f01a-2f55-41da-9760-8c5c776b9c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Création De Compte'])[2]/following::td[12]</value>
      <webElementGuid>02f799f4-2ce1-4160-9d6a-68b06098072f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::td[3]</value>
      <webElementGuid>5db90aa5-c4c2-42b6-84a7-662144d4664d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td[2]/table/tbody/tr/td</value>
      <webElementGuid>07c5a029-5959-4ebf-affe-7273481ee615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'demandeAdhesionAnonymeForm:cinTab_lbl' and (text() = concat(&quot;Pièce d&quot; , &quot;'&quot; , &quot;Identité&quot;) or . = concat(&quot;Pièce d&quot; , &quot;'&quot; , &quot;Identité&quot;))]</value>
      <webElementGuid>30e1a03e-5fb1-406a-b48e-fd8802ac4a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
