<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Non_signatureDocumentsFormj_id51</name>
   <tag></tag>
   <elementGuidId>06cdb125-a409-492b-966b-6e600344703d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:j_id51']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0390283-d444-4366-acda-f9cebe04e4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>3e0c38e4-4cb8-4de9-bcea-4a19be71b0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:j_id51</value>
      <webElementGuid>8a4132fb-2483-480b-b167-6a2c711bfa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:j_id51</value>
      <webElementGuid>9fc941f1-d674-494a-8c62-c0f25d0e2dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('signatureDocumentsForm',event,{'similarityGroupingId':'signatureDocumentsForm:j_id51','oncomplete':function(request,event,data){updateSignatureVariables()},'parameters':{'signatureDocumentsForm:j_id51':'signatureDocumentsForm:j_id51'} } );return false;</value>
      <webElementGuid>3b1f720c-ccfb-4746-9a03-a53573129340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Signer</value>
      <webElementGuid>9f49565d-8033-45d5-917d-3f04dd53e3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60da72e6-62f2-40f4-bf02-48af29672525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1f6d8975-e91f-4c6e-a750-8afc6794e5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:j_id51&quot;)</value>
      <webElementGuid>fb2457b5-d44c-4d52-9b34-1fe7cfdf9e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:j_id51']</value>
      <webElementGuid>1f3a88a8-a300-4829-bf86-bef3c473dea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signatureDocumentsForm:j_id42']/div[3]/div[2]/div/input</value>
      <webElementGuid>2785649c-1de0-4203-84ee-3bca62c3fa49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9cd5f2b4-26c0-4d9d-aa7f-c0466def94e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signatureDocumentsForm:j_id51' and @name = 'signatureDocumentsForm:j_id51' and @type = 'button']</value>
      <webElementGuid>724d64ba-4387-4ca3-9191-1d8af3c4581e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
