<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MODPM.pdf_signatureDocumentsFormj_id239</name>
   <tag></tag>
   <elementGuidId>28b8c720-8a2a-4d58-b354-a3fa972360c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;signatureDocumentsForm:j_id239&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='signatureDocumentsForm:j_id239']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d4dfdde-beba-4621-b26b-7a1da3e7185f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c1035b21-2396-4612-96c3-ba9183573f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:j_id239</value>
      <webElementGuid>e6a3cee1-9e8c-40bf-97e8-e98a5b535151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Récépissé de dépôt et reçu de paiement</value>
      <webElementGuid>916ec3bd-68e7-4464-9752-64e278217f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Récépissé de dépôt et reçu de paiement</value>
      <webElementGuid>900d8fec-be84-4238-9432-e0b56d41919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>a8bd991d-3b6a-4a43-8d73-9471d31a0919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:j_id191&quot;)/div[@class=&quot;form-group text-center&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;btn btn-connexion&quot;]</value>
      <webElementGuid>43110902-ccdd-4229-add9-31278b3c17d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='signatureDocumentsForm:j_id239']</value>
      <webElementGuid>abcebb25-619f-4ec9-be73-f04f79b8544b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signatureDocumentsForm:j_id191']/div[2]/div[11]/input</value>
      <webElementGuid>a02a905f-5ff5-4442-b580-a05e0e021199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>62300b23-673a-45c1-a8f6-5f5579a44e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'signatureDocumentsForm:j_id239' and @alt = 'Récépissé de dépôt et reçu de paiement']</value>
      <webElementGuid>8312e82a-56c0-4a1c-8de2-02fddab28134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
