<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_signatureDocumentsFormselectedSig_0a84ea</name>
   <tag></tag>
   <elementGuidId>4dea1427-4adb-42ee-a940-c08066d7d2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatureDocumentsForm:selectedSignatureClasse:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>697a5046-d172-4481-8479-fdeabff28017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c90f27bc-2013-4fa4-8c23-0ca1bb683f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatureDocumentsForm:selectedSignatureClasse</value>
      <webElementGuid>12a725bb-3744-4f8c-bb6a-981afcfcac62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatureDocumentsForm:selectedSignatureClasse:1</value>
      <webElementGuid>3a3db07b-6321-4e99-8abc-78771389e590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>class1</value>
      <webElementGuid>23edf4d1-9835-440a-bafe-00adf09d49e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateSelectedSignatureClasse(this.value);</value>
      <webElementGuid>74e1e727-4ce6-4f11-bc7b-3ac759b054ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>019d0295-520d-4c48-aea3-f86acb3cc9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatureDocumentsForm:selectedSignatureClasse:1&quot;)</value>
      <webElementGuid>7fa84671-fb60-421d-baff-928577780ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatureDocumentsForm:selectedSignatureClasse:1']</value>
      <webElementGuid>74b1b810-93c0-4e71-9e4a-e87120a8df4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='signatureDocumentsForm:selectedSignatureClasse']/tbody/tr/td[2]/input</value>
      <webElementGuid>e3abc2e9-9ba8-43d1-9910-46eec2178ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>e247437a-89f3-4284-882b-dece07c233a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'signatureDocumentsForm:selectedSignatureClasse' and @id = 'signatureDocumentsForm:selectedSignatureClasse:1']</value>
      <webElementGuid>2dad91f8-9ff5-434f-ab9f-3749e4fc2752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
