<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Recherche des dossiers</name>
   <tag></tag>
   <elementGuidId>9de6a311-ee83-474c-ac09-bbe6ce9188aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='iconj_id243:liste_dossier_pm_jsf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>102eed2e-3b68-4c83-9013-366276f467ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-pmenu-group-self-label rich-pmenu-item-label</value>
      <webElementGuid>38c81a8a-24ea-4333-a337-d6c119aa9176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iconj_id243:liste_dossier_pm_jsf</value>
      <webElementGuid>be56c5d5-89c6-491a-831d-56d25f2d42d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0190377f-0246-4219-8d3f-98b1636cff27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recherche des dossiers</value>
      <webElementGuid>4d84a79a-3ff6-46af-8f42-8feba48a97d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iconj_id243:liste_dossier_pm_jsf&quot;)</value>
      <webElementGuid>0345677e-26f9-4588-a7e0-19be9a0e6de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='iconj_id243:liste_dossier_pm_jsf']</value>
      <webElementGuid>b341f11f-c254-4907-b2d3-67bc93afd6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_j_id243:liste_dossier_pm_jsf']/td[2]</value>
      <webElementGuid>9692bc5c-95c1-4f02-a79c-0e8c113e108e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[1]/following::td[3]</value>
      <webElementGuid>f15251f5-fe59-4168-918a-ab30481267d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personne morale'])[1]/following::td[6]</value>
      <webElementGuid>0632cd82-1cd4-4145-b0e2-0ff487243dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Succursale d', &quot;'&quot;, 'une entreprise Marocaine')])[1]/preceding::td[3]</value>
      <webElementGuid>1fa2d9e3-1f43-4c27-a56f-c6c62cac475a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nouveau dossier'])[2]/preceding::td[9]</value>
      <webElementGuid>6d38bd56-fc37-4495-9d23-f7118fde4d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recherche des dossiers']/parent::*</value>
      <webElementGuid>fa5404e8-88c6-4180-9f5f-c83da9522c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>fd6e87bd-f722-46ed-8b0f-25812dc0adc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'iconj_id243:liste_dossier_pm_jsf' and (text() = 'Recherche des dossiers' or . = 'Recherche des dossiers')]</value>
      <webElementGuid>eb0a47c6-457c-4e29-9f0a-0289ee91f0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
