<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prt pour signature_dossierFormlisteDo_df86db</name>
   <tag></tag>
   <elementGuidId>a79c9859-777a-419d-bc6c-a997896f230b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;dossierForm\:listeDossierEnPreparation\:0\:cbvisualiser&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38ac6263-bca1-4508-92f9-fc605e3f561c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbvisualiser</value>
      <webElementGuid>897cadf4-ad4a-4db7-989c-6bdab38d2c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ffc34e61-8ac5-495b-b30a-70fccc0e4c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/commun/icone-view.gif</value>
      <webElementGuid>eb6a1cde-a307-4bed-a2ca-a04dfcd4ebb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeDossierEnPreparation:0:cbvisualiser</value>
      <webElementGuid>3643fb3b-9435-4595-8ce7-6408fe6c7c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>483bc6f3-366d-4574-86e9-82fa3072cc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeDossierEnPreparation:0:cbvisualiser&quot;)</value>
      <webElementGuid>23b52dd0-af0c-4a0b-96c7-625d9ada9290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      <webElementGuid>7b0421b7-70e1-4126-a26b-3fe9977912f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeDossierEnPreparation:0:j_id113']/span/ul/input</value>
      <webElementGuid>b632da02-efe1-4c73-9bb9-5997d50deffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/input</value>
      <webElementGuid>154b7ef7-531a-4489-93c3-4e0b1a964511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:listeDossierEnPreparation:0:cbvisualiser' and @type = 'image' and @src = '/images/commun/icone-view.gif' and @name = 'dossierForm:listeDossierEnPreparation:0:cbvisualiser']</value>
      <webElementGuid>e6a041d9-da51-4a35-be4b-071d3a485b00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
