<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>844fadd9-f49a-4fd3-8422-974a74da2bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-keyboard-button.ui-keyboard-1608.ui-state-default.ui-corner-all.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[50]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3891dbbf-747d-4421-8d74-c42ba4a87846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9402b15c-7892-428a-90ae-3ee32cb8c082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ab0c798-bbcb-47c1-92b9-41823f45865e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb2c1921-ef0d-4e46-a63e-5b8545a103b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>318bec32-d983-4662-a8ee-cdb17f012357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-keyboard-button ui-keyboard-1608 ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>c03217e6-02a6-4f7f-a272-c75c7ea9ec5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>و</value>
      <webElementGuid>f1f803de-8abe-4b44-994a-012b23b3eda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>و</value>
      <webElementGuid>9992d844-0544-4000-a1ca-0dd2b93d5ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pos</name>
      <type>Main</type>
      <value>3,8</value>
      <webElementGuid>e2447f89-996a-4c1e-aad0-7c54661adb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>و</value>
      <webElementGuid>4db3a8c2-78c9-4cb2-9776-e78ca816f2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>&lt;span class=&quot;ui-keyboard-text&quot;>&amp;#1608;&lt;/span></value>
      <webElementGuid>88b1025a-c14e-4f54-a816-a35ae18d2fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>و</value>
      <webElementGuid>17d312b9-132a-4af7-9150-8f13c8f44e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:adresse1ArInGerantPersPhys_keyboard&quot;)/div[@class=&quot;ui-keyboard-keyset ui-keyboard-keyset-normal&quot;]/button[@class=&quot;ui-keyboard-button ui-keyboard-1608 ui-state-default ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>ab2d4a28-87a9-47c2-96f5-485d2068bc6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[50]</value>
      <webElementGuid>7eae5398-b507-4a39-9e8d-9a1e6efed115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gerantPersPhysPopUpForm:adresse1ArInGerantPersPhys_keyboard']/div/button[48]</value>
      <webElementGuid>9bfdf0dc-672f-4af5-b018-9b0f2a1fbe83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ة'])[1]/following::button[1]</value>
      <webElementGuid>3cf6c58c-46e0-47de-b38b-789d9f25f24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ى'])[1]/following::button[2]</value>
      <webElementGuid>d4dafebd-f1cd-4bc3-891b-26e58ecc91e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ز'])[1]/preceding::button[1]</value>
      <webElementGuid>23690f29-fd88-4958-8a33-8598aa4dba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[48]</value>
      <webElementGuid>dbb5d7f6-74c3-4aae-9f41-938539623102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'و' or . = 'و')]</value>
      <webElementGuid>fe8eb72a-3af4-4c16-95ac-68fc8a01294b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
