<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>c8e50b88-76e9-48fb-93ae-3c1700e0bee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-keyboard-button.ui-keyboard-1604.ui-state-default.ui-corner-all.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[76]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50645962-5c11-4673-9480-dd6f5dedc799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c9f294a-072e-4921-bcc2-c9b3883b887b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98fa27cb-bb82-470f-9eb2-570455e64493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ef3d35c-8fb2-4e4d-b0e4-01f310177aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>240616c9-a27e-4df4-8766-3932e26baae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-keyboard-button ui-keyboard-1604 ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>19af19f2-1389-4443-914c-08c69b4aa05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>ل</value>
      <webElementGuid>32613048-f9f2-4f33-b6fc-1d0d7b0ca753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>ل</value>
      <webElementGuid>998b9881-0b13-4f59-858d-42e2d64365cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pos</name>
      <type>Main</type>
      <value>1,5</value>
      <webElementGuid>f17788d8-181b-4a0c-96b4-55e4f0d73073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>ل</value>
      <webElementGuid>5645f6e3-f608-4e29-877b-a86ca4c5f0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-html</name>
      <type>Main</type>
      <value>&lt;span class=&quot;ui-keyboard-text&quot;>&amp;#1604;&lt;/span></value>
      <webElementGuid>e96f9b2d-1f10-4f11-83d4-090a7f120d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ل</value>
      <webElementGuid>420cfc41-eed3-41ea-b263-7bb72c0b5eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:objSocialAr_keyboard&quot;)/div[@class=&quot;ui-keyboard-keyset ui-keyboard-keyset-shift&quot;]/button[@class=&quot;ui-keyboard-button ui-keyboard-1604 ui-state-default ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>d9b2b1af-2af1-475e-a33e-9e4a10889685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[76]</value>
      <webElementGuid>bdbde6b2-14eb-400b-9b75-890418871bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:objSocialAr_keyboard']/div[2]/button[20]</value>
      <webElementGuid>61a56b46-dde8-44c2-80f0-33eafaf8e578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ٌ'])[1]/following::button[1]</value>
      <webElementGuid>87b566eb-9271-4711-aa52-d0a0588fc946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ُ'])[1]/following::button[2]</value>
      <webElementGuid>675820be-c82d-4ccc-85be-09aba12c80d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إ'])[1]/preceding::button[1]</value>
      <webElementGuid>38082f0a-422b-4e8d-a534-ea2b27055470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[20]</value>
      <webElementGuid>c61182cd-f947-4aa3-af2c-0ec6ddf0a7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ل' or . = 'ل')]</value>
      <webElementGuid>2882b2ce-d06b-4c34-a284-b34c51964e87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
