<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , panelDiv, , ))_panelDiv</name>
   <tag></tag>
   <elementGuidId>ae1fdffb-53ef-45de-a833-ca63f9f7f3d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panelDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panelDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0529b98-15d5-46a1-ab58-9fd59b851da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-mpnl-mask-div-opaque rich-mpnl-mask-div</value>
      <webElementGuid>8474e421-cd51-4b71-9566-8768315d1e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panelDiv</value>
      <webElementGuid>524ffa49-88e0-44e0-ae7e-01122e6d89da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ee1146a0-bccf-410b-8e03-85ca1332fa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panelDiv&quot;)</value>
      <webElementGuid>ab5e9578-a576-4c8f-ade6-1cc476c356e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panelDiv']</value>
      <webElementGuid>ba011814-6107-4164-a622-44e352bc98aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panelContainer']/div</value>
      <webElementGuid>74e96d76-ae84-4835-a962-29518cd29f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'panelDiv', '&quot;', ')')])[1]/following::div[2]</value>
      <webElementGuid>260fb008-0a32-413f-9ceb-70780a338d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/following::div[4]</value>
      <webElementGuid>946deb59-c842-4575-827a-765b8bd62f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[20]/preceding::div[2]</value>
      <webElementGuid>4dcb83f8-e99d-4f94-bd92-2b57b9f3b20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter Dirigeant Personne Physique'])[1]/preceding::div[3]</value>
      <webElementGuid>d4c85260-44ac-408c-8fcc-854c8213dc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>875ecb61-54f3-41e7-8ada-43b01b24f9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panelDiv']</value>
      <webElementGuid>3f9b7d7e-bc36-448a-909b-7cdeb0c82c6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
