<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signature et dpt_dossierFormj_id1271</name>
   <tag></tag>
   <elementGuidId>b40a14e9-763c-4526-a0be-7e585940faf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dossierForm:j_id1271&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dossierForm:j_id1271']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2c7ec62-948e-43e6-836a-1d443317e347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5d96d87e-c6a1-479e-8c90-ad852ba2850a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:j_id1271</value>
      <webElementGuid>db544891-32dc-470a-97c1-6f1ec08effb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Précédent</value>
      <webElementGuid>e5bb1564-30f8-4cf8-bab1-722c452277e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion prev</value>
      <webElementGuid>0476b582-f8be-46f0-b2cd-33dfee7b2785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3b0f4933-a1be-4156-8c05-e670fcfb2fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:informationsFiscales&quot;)/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content&quot;]/input[@class=&quot;btn btn-connexion prev&quot;]</value>
      <webElementGuid>bd0abd7e-3f3a-48e2-8159-38450bf4f9cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dossierForm:j_id1271']</value>
      <webElementGuid>fc23b8a7-5b86-44dd-a441-b9b98f21f614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:informationsFiscales']/table/tbody/tr/td/input</value>
      <webElementGuid>bd74661f-8733-4767-8389-51f90fb5f752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>575823e5-9c6b-4749-a4aa-e9ef71c4b979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'dossierForm:j_id1271']</value>
      <webElementGuid>a9ae0bbd-e8d6-488f-9828-66df4e795905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
