<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_dossierFormassistanceChambreCommerce</name>
   <tag></tag>
   <elementGuidId>ae28e815-0a35-4181-bb35-f46b3c8c9741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:assistanceChambreCommerce:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af985e2e-4ccb-4972-8bf7-b233951dd3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c8c88fe3-8d70-4a8d-855b-452874d8d145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:assistanceChambreCommerce</value>
      <webElementGuid>11a16544-3048-42f9-b177-02bb18c03db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:assistanceChambreCommerce:1</value>
      <webElementGuid>8570b105-8b33-4f3a-8a2d-3494072b7acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>2fb959bf-3559-4de6-91cf-37be58b676e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id68','parameters':{'dossierForm:j_id68':'dossierForm:j_id68'} } )</value>
      <webElementGuid>f03795c5-6808-4808-8890-8e2c3e752de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:assistanceChambreCommerce:1&quot;)</value>
      <webElementGuid>ac1a853f-eed2-429f-a0e2-9b2fbfb5da2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:assistanceChambreCommerce:1']</value>
      <webElementGuid>acf5dfca-348a-448d-b41d-40fd514bd0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierForm:assistanceChambreCommerce']/tbody/tr/td[2]/input</value>
      <webElementGuid>b2529727-496e-4370-87c6-d00d9b7aff08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>d18561bf-59bf-4ad5-bd42-5e6d94aaf96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'dossierForm:assistanceChambreCommerce' and @id = 'dossierForm:assistanceChambreCommerce:1']</value>
      <webElementGuid>983e137e-94d7-47e8-b734-1e12e85aa4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
