<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fax_associePersPhysPopUpFormfaxInAsso_0350e2</name>
   <tag></tag>
   <elementGuidId>ba4ada2a-303d-4a9f-91e7-7b8496873102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='associePersPhysPopUpForm:faxInAssociePersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97b811bf-012e-4f1d-a26f-4faf3b320888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>associePersPhysPopUpForm:faxInAssociePersPhys</value>
      <webElementGuid>8a8a0c31-6475-4e81-8180-974b910113bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e2fc7e4-b698-4539-bfb5-bf09377a3752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>associePersPhysPopUpForm:faxInAssociePersPhys</value>
      <webElementGuid>d0274117-f1e1-4aba-a74b-aea76db77bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d40f29e-e3e7-404d-a005-ed1ad2ab9a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>efc21f7e-fbd1-4b9d-98a5-32d2d3fa5184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>70d1a0b9-710f-420e-94d1-765da5732e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ab780ffb-55c1-4570-8620-3fff6e9f86fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;associePersPhysPopUpForm:faxInAssociePersPhys&quot;)</value>
      <webElementGuid>039e78c9-bd42-4c37-a45f-41acdd74a325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='associePersPhysPopUpForm:faxInAssociePersPhys']</value>
      <webElementGuid>471c1ade-04ae-4a43-9faf-3f7c2667bb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='associePersPhysPopUpForm']/div[12]/div[3]/input</value>
      <webElementGuid>1af5e23c-edab-4025-b55c-885ee9f128c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[3]/input</value>
      <webElementGuid>f232e2d7-d0ec-4a43-b79f-aea6c98d2c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'associePersPhysPopUpForm:faxInAssociePersPhys' and @type = 'text' and @name = 'associePersPhysPopUpForm:faxInAssociePersPhys']</value>
      <webElementGuid>1696c5dc-181f-4e4f-bd74-0c914f450137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
