<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CINqs12312230082023_dossierFormlisteA_5f53ca</name>
   <tag></tag>
   <elementGuidId>448e8ad9-d469-4a04-b3ad-2d0c4b6cccd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ae48dfb-883c-4fc9-a215-3f336b62ab05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-line</value>
      <webElementGuid>492a6933-22d9-4071-a860-50960c736b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys</value>
      <webElementGuid>2f161a8d-c25c-4c8d-9367-6b32eda37119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys</value>
      <webElementGuid>8ca3dd5d-55e8-4725-b385-9a1eb0f5b629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys','oncomplete':function(request,event,data){jQuery('*').attr('autocomplete','no');document.getElementById('panelAssocie').component.show()},'parameters':{'dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys':'dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys'} } );return false;</value>
      <webElementGuid>4721cf94-aae3-49b7-9734-3c81ccaf37b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Modifier</value>
      <webElementGuid>5eb98f3b-14d7-4467-a0ea-358ad5bdafa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>694fa02b-f401-4ba4-b950-98cd40b2f622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images-new/svg/edit.svg</value>
      <webElementGuid>16f35307-ed39-4fc5-b8c4-e3de0704a276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>98e59136-3186-42c4-975c-72f1ed84a4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys&quot;)</value>
      <webElementGuid>821fafa1-a38c-42fb-8e04-43c2b9d33c1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys']</value>
      <webElementGuid>79f180c4-c62c-47a1-9f32-2949116b57d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeAssociePersPhys:0:j_id1532']/input</value>
      <webElementGuid>74ac3f1f-529b-42d5-868b-48d2093bd281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>9148b5df-b60e-42e6-8e85-0e1b3bdff355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys' and @name = 'dossierForm:listeAssociePersPhys:0:modifierDossierAssociePersPhys' and @alt = 'Modifier' and @type = 'image' and @src = '/Guichet/images-new/svg/edit.svg']</value>
      <webElementGuid>af39d917-c484-4397-b711-afd9614ab613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
