<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormdateValPieceI_6b6248</name>
   <tag></tag>
   <elementGuidId>bc27fbb7-b4ee-40c2-94e4-9ea643a159de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4c09499-ebfa-415c-aea9-ea2dcf695ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input</value>
      <webElementGuid>bf4047fb-3c87-4ec6-8cfe-3263f70eec30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate</value>
      <webElementGuid>6dde166f-0974-40a0-8d9b-03b053e57366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate</value>
      <webElementGuid>87991af7-c098-4246-8273-62fffed3e8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dccd641f-3495-4ac1-9176-9cc76163d260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ac4d3a07-64e1-4335-a2e0-8023b72785ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08b9c015-0d45-48ff-8621-31a32b2798ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>28331be6-02d4-44b6-af5d-035888b046fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate&quot;)</value>
      <webElementGuid>aac581bd-951e-4605-abcb-7deca3196933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate']</value>
      <webElementGuid>952927f7-97b5-4b2a-8f81-ff49ed4300b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysPopup']/input</value>
      <webElementGuid>bb4a66d1-7078-447e-ab0c-ce1f8d825989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/span/input</value>
      <webElementGuid>0892ca9e-45d7-4752-89c0-1ea863ce5f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate' and @name = 'gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysInputDate' and @type = 'text']</value>
      <webElementGuid>545a6485-f437-46d9-9ab6-64cf55cd7e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
