<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__associePersPhysPopUpFormpartsActions_ba3459</name>
   <tag></tag>
   <elementGuidId>fb26a4ce-e0ef-4c34-9a7c-bad4c61de116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='associePersPhysPopUpForm:partsActionsInAssociePersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad8d642e-85ad-4a89-9a64-fa2f86a7820c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>associePersPhysPopUpForm:partsActionsInAssociePersPhys</value>
      <webElementGuid>95603ea7-f991-4860-ad30-bbb85bb7a478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81f0fb65-93d1-4e5e-8d56-8a26aec62bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>associePersPhysPopUpForm:partsActionsInAssociePersPhys</value>
      <webElementGuid>0fccfaea-0519-4fb7-b714-5a91b3e2fe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0fb57388-3800-4b29-a0ff-0c15a52dd8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>40db481d-d379-45be-b656-8bf424d6b59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKey(event)</value>
      <webElementGuid>92141813-ce95-4b8a-9c9c-7c0c24637aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2dd5ed26-bd5b-4598-83aa-4e0179401509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;associePersPhysPopUpForm:partsActionsInAssociePersPhys&quot;)</value>
      <webElementGuid>ed4c16bc-6e75-4eb1-a83b-6cccfbbed689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='associePersPhysPopUpForm:partsActionsInAssociePersPhys']</value>
      <webElementGuid>8d171227-4b23-4092-8589-da1704ac217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='associePersPhysPopUpForm']/div/div/input</value>
      <webElementGuid>8b3100b1-d15e-4164-bce6-525880a338b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/div/div/input</value>
      <webElementGuid>2a861505-ec28-43ae-8088-a20d2c8e7534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'associePersPhysPopUpForm:partsActionsInAssociePersPhys' and @type = 'text' and @name = 'associePersPhysPopUpForm:partsActionsInAssociePersPhys']</value>
      <webElementGuid>c5cfd7b2-05d1-4b82-8798-848127de132c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
