<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Activit_associePersPhysPopUpFormvalid_1e5503</name>
   <tag></tag>
   <elementGuidId>640c2be5-d8b9-4d05-aba1-c070c4f28314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='associePersPhysPopUpForm:validerDossierAssociePersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e5393f4-2d6f-4c04-92e7-846893517293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion pull-right</value>
      <webElementGuid>69982648-e165-4c91-878a-e749c3786792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>associePersPhysPopUpForm:validerDossierAssociePersPhys</value>
      <webElementGuid>496341e7-86b4-434b-8602-0ccb7a3cf187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>associePersPhysPopUpForm:validerDossierAssociePersPhys</value>
      <webElementGuid>db7344ae-9dd2-4234-b3a6-c06ad1d3551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('associePersPhysPopUpForm',event,{'similarityGroupingId':'associePersPhysPopUpForm:validerDossierAssociePersPhys','oncomplete':function(request,event,data){if('false'=='true'){document.getElementById('panelAssocie').component.hide();}},'parameters':{'associePersPhysPopUpForm:validerDossierAssociePersPhys':'associePersPhysPopUpForm:validerDossierAssociePersPhys'} } );return false;</value>
      <webElementGuid>29cc9678-e49c-415e-8133-313f338ba137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>c9cd25fc-d0c8-45d1-8961-f91185206f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51db94d9-dbab-4308-a300-354de50611fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ab94cbf7-bd7a-48a0-a3b1-847e31f58f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;associePersPhysPopUpForm:validerDossierAssociePersPhys&quot;)</value>
      <webElementGuid>03315b57-9aef-4576-b797-fb3ed0ba0796</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='associePersPhysPopUpForm:validerDossierAssociePersPhys']</value>
      <webElementGuid>8f6f7271-2e92-46a5-bf6d-059b7311a6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='associePersPhysPopUpForm']/input[4]</value>
      <webElementGuid>efe7c920-4a36-4e69-a5c8-eeb7c595f96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/input[4]</value>
      <webElementGuid>ab2537df-77c1-4b02-9a74-1cd48ff20f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'associePersPhysPopUpForm:validerDossierAssociePersPhys' and @name = 'associePersPhysPopUpForm:validerDossierAssociePersPhys' and @type = 'button']</value>
      <webElementGuid>bf676aab-42b7-4418-9f10-409c68cf3179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
