<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Il se peut qu, , une autorisat_e745b6</name>
   <tag></tag>
   <elementGuidId>c67518d1-07cc-4515-bbee-4a91aa14dbd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fermerDamande</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fermerDamande']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34a885a5-0d1e-4c76-b708-177d71daeb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e4cafe4-67ad-4987-9dc8-6d1b93725169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fermerDamande</value>
      <webElementGuid>80cd3fc2-1f1e-469f-ba40-c35c5b2c8f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>c876a4e3-0a94-4af8-8e42-e435a8a7f820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>923fed17-d143-49d5-ab55-fc41f1ff35bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>functiontest()</value>
      <webElementGuid>9d7ff895-ad9d-401e-9836-9dffa9b430c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2a247080-2cb1-49ae-907b-7e8062d05962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fermerDamande&quot;)</value>
      <webElementGuid>5a666eaa-9009-4d44-87a1-7c29738a66cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fermerDamande']</value>
      <webElementGuid>2d0f5157-4d80-441c-9fb1-53252f0a8af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divbutton']/input</value>
      <webElementGuid>f2956f56-e647-4bf4-93ec-db8cacf2b9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div[2]/input</value>
      <webElementGuid>0dc9761b-24c3-4abf-b970-bf2ae138a9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'fermerDamande']</value>
      <webElementGuid>643166d0-2ae1-4d46-9816-41dafee3c6b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
