<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dossierFormdateEngagementPremierSala_aaab0f</name>
   <tag></tag>
   <elementGuidId>86af0b70-2af6-465a-a437-ba58d4aa95e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:dateEngagementPremierSalarieInputDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7104a633-593e-4bcf-9f49-85b478e7336b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input</value>
      <webElementGuid>0256a291-437b-4268-97da-4e841461a4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:dateEngagementPremierSalarieInputDate</value>
      <webElementGuid>ffe1ddee-5c3d-4335-a7da-ec0f2bbca533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:dateEngagementPremierSalarieInputDate</value>
      <webElementGuid>5ffdad8c-efe4-4210-8f65-fd1fe8749425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99ecff22-2ecb-4c07-8687-a82828ddc2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ad39556a-87ad-4f98-a9a7-560adb86fc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:dateEngagementPremierSalarieInputDate&quot;)</value>
      <webElementGuid>cc91ab1b-5243-4da3-b59a-f0aefb6f7d6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:dateEngagementPremierSalarieInputDate']</value>
      <webElementGuid>17301f75-bc5c-48d8-a060-6738508195f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dossierForm:dateEngagementPremierSalariePopup']/input</value>
      <webElementGuid>1a08432d-fced-40ac-a7a2-d5af3c994ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>a251062a-2a67-4f48-822d-b147560b429c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:dateEngagementPremierSalarieInputDate' and @name = 'dossierForm:dateEngagementPremierSalarieInputDate' and @type = 'text']</value>
      <webElementGuid>2390107a-cefa-4506-8bca-ebaecee58d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
