<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signature et dpt_dossierFormj_id1490</name>
   <tag></tag>
   <elementGuidId>5115dc64-d99e-4675-be89-835544ac29f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dossierForm:j_id1490&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dossierForm:j_id1490']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e58d23d-1460-47ca-b896-1b1d0d68ccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cb1318de-6297-4a0b-b0f9-a1afde2aff5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:j_id1490</value>
      <webElementGuid>dc9cdc1c-d8a6-4d1c-aa56-ff612647414a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>4ad8d1a2-acbf-4cc8-ade6-6a5f0c407fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion next</value>
      <webElementGuid>4354ca35-571d-439d-8417-18aad38691f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0553dc96-60a5-46d4-abeb-7468f9a4eb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c808dc2b-e6b5-4f87-afd9-709dfc4fb7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:gerant&quot;)/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content&quot;]/input[@class=&quot;btn btn-connexion next&quot;]</value>
      <webElementGuid>a7ce811d-b20c-444d-bf2f-d5e1ace21839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dossierForm:j_id1490']</value>
      <webElementGuid>c2f12c5f-7304-42bf-81ca-a0c22ee7cdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:gerant']/table/tbody/tr/td/input[2]</value>
      <webElementGuid>b693bdc1-e59e-4e67-8930-136c6ff22db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[2]</value>
      <webElementGuid>ac3ff678-03ea-4e65-af07-3df0248636a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'dossierForm:j_id1490']</value>
      <webElementGuid>0367ed69-7b7e-495c-b231-8d5249e65c7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
