<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormprenomInGeran_daf565</name>
   <tag></tag>
   <elementGuidId>016edcda-d39b-4250-8ab7-84cb6390b5b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:prenomInGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d3ec8ce-c2e8-45b7-acb5-d8380223ed46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:prenomInGerantPersPhys</value>
      <webElementGuid>10ca1b93-52a5-480a-89b9-05145cf00890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c1172bb-a48f-4271-9ddf-e22af7b99840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:prenomInGerantPersPhys</value>
      <webElementGuid>b1f0c016-6045-4319-867a-cd34fd9f508e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control frenchLettersTxt</value>
      <webElementGuid>f865f7ad-d0bc-42ba-bfaf-43b250bba32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4c0bb32a-8f69-49a8-a757-574c8c89472e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0f953cb9-83e7-4bb1-a2eb-f37a20a787a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:prenomInGerantPersPhys&quot;)</value>
      <webElementGuid>8dc11b42-9b11-480b-994f-6dc4a6e6be4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:prenomInGerantPersPhys']</value>
      <webElementGuid>06ed3d9a-e0f9-4269-ab3c-789a72a3fb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[5]/input</value>
      <webElementGuid>b81f27c8-a567-456d-828c-4ce89be1951b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/div[5]/input</value>
      <webElementGuid>fe3cad6e-bf91-4383-b76a-f5d3256682e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:prenomInGerantPersPhys' and @type = 'text' and @name = 'gerantPersPhysPopUpForm:prenomInGerantPersPhys']</value>
      <webElementGuid>ffa5e6ee-2041-40fb-aeed-78837c18d220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
