<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dossierFormj_id801</name>
   <tag></tag>
   <elementGuidId>12cf5b6b-56d6-4d83-bd2f-cab998757135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:j_id801']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0a57bc4-95b9-40eb-a803-b0c7e070b17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addActivite</value>
      <webElementGuid>1c12ec31-b726-4aeb-8bca-f8b7ae401a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:j_id801</value>
      <webElementGuid>fff64d4c-e61c-460b-9411-1114b382c65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:j_id801</value>
      <webElementGuid>fa7170be-43e9-4c37-b29d-3e1826172c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id801','oncomplete':function(request,event,data){document.getElementById('creerViewActivitePrimaire:panelAjouterActivitePrimaire').component.show()},'parameters':{'dossierForm:j_id801':'dossierForm:j_id801'} } );return false;</value>
      <webElementGuid>b8a33a39-b9c3-49cc-bab0-65e5988e14f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ajouter</value>
      <webElementGuid>7debbbf6-51a8-4ca7-be4f-38c3ca65ae05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>d0fad9cc-e431-4b58-8851-d443738be364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images-new/svg/add.svg</value>
      <webElementGuid>4f1076d0-c642-40f5-9825-be1d4bd738fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ajouter</value>
      <webElementGuid>0a760616-cbd4-4067-ab75-24f89071f86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0c9932d4-006a-4839-a77f-160558b2e796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:j_id801&quot;)</value>
      <webElementGuid>c67d26d6-d6e4-45ca-81b6-e5acfde8a12a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:j_id801']</value>
      <webElementGuid>d06feb2b-bbb8-4163-8f4f-1f41a262559a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:panelGridActivitiesP_body']/input</value>
      <webElementGuid>a9f94a7f-86f1-4216-a7b1-ef84aa0046a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>0bd14f38-3dd0-4b50-b3f1-15e86c4c5a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:j_id801' and @name = 'dossierForm:j_id801' and @type = 'image' and @src = '/Guichet/images-new/svg/add.svg' and @alt = 'Ajouter']</value>
      <webElementGuid>ed3970cf-8b59-4486-af37-c545f3ea59cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
