<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Veuillez cliquer sur cet icne pour aj_89bb85</name>
   <tag></tag>
   <elementGuidId>ac49d52c-9933-4210-bbdf-ce8a930de3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:j_id1288']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cab18847-d6b3-4ec3-863d-a46de855edcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addPersonne</value>
      <webElementGuid>c308807f-c015-49d9-8e7c-8c6276e4c67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:j_id1288</value>
      <webElementGuid>392dea7b-893a-4fc4-b476-65e43998bb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:j_id1288</value>
      <webElementGuid>8c3bdfed-77d8-4df9-ba86-0de54e0754a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id1288','oncomplete':function(request,event,data){jQuery('*').attr('autocomplete','off');document.getElementById('panel').component.show()},'parameters':{'ajaxSingle':'dossierForm:j_id1288','dossierForm:j_id1288':'dossierForm:j_id1288'} } );return false;</value>
      <webElementGuid>df72ed33-d42a-4ffb-9faa-131edeecfbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>b8a61296-7d65-4f14-8ab2-7682b2fd94cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images-new/svg/add.svg</value>
      <webElementGuid>8b8da6d6-e812-469b-bd99-344e95e1738a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>372125bc-9d06-48cf-b30e-84acc283c6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:j_id1288&quot;)</value>
      <webElementGuid>662ad52c-ed02-4010-87af-48cc0aac0cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:j_id1288']</value>
      <webElementGuid>3bc3a16b-2104-4389-821c-1602f01b781f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:panelGerantPersPhys']/input</value>
      <webElementGuid>6b9321fb-645d-44c4-b373-6e7274d76bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>82dd1e38-f0f0-48a3-ad32-fb9f48500449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:j_id1288' and @name = 'dossierForm:j_id1288' and @type = 'image' and @src = '/Guichet/images-new/svg/add.svg']</value>
      <webElementGuid>e80cf0dd-fc1d-40cf-9257-3c0d73e8b0e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
