<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormtelephoneInGe_564cdb</name>
   <tag></tag>
   <elementGuidId>ee95dc4a-4a1a-4181-90cc-9649bd57d13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:telephoneInGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3571dd1d-5833-4c12-acc6-74fe2f912fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:telephoneInGerantPersPhys</value>
      <webElementGuid>293e159b-afcf-4c90-b44c-0f7bd2ee6e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb4b4a82-cd0c-4681-9db3-a82213d4cc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:telephoneInGerantPersPhys</value>
      <webElementGuid>25e66b77-db83-4067-8928-913f7af3dd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c90dbeae-0c81-4b27-a22d-9ea2eb3b4aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>ecc8ae16-4be9-469b-9adf-f3ea93ad27ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumberKey(event)</value>
      <webElementGuid>c674d597-3bca-4136-be84-a950108fb327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>defa500f-4b04-4f5f-874d-5c5377aa7d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de2625cf-dd19-4fcc-96b0-84bb3e7353fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:telephoneInGerantPersPhys&quot;)</value>
      <webElementGuid>044f63e6-7e17-44db-b704-57a7eff05011</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:telephoneInGerantPersPhys']</value>
      <webElementGuid>f537370e-8be6-4f90-8ca7-61ae3b336dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[16]/div/input</value>
      <webElementGuid>f36919e7-de64-424f-aa88-6b066f38fad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>053f2169-3b34-4145-baca-22285bc0dafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:telephoneInGerantPersPhys' and @type = 'text' and @name = 'gerantPersPhysPopUpForm:telephoneInGerantPersPhys']</value>
      <webElementGuid>0bdf1ecb-bf8e-4a57-b255-cd85de189266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
