<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Non_gerantPersPhysPopUpFormvaliderDos_f7e7c5</name>
   <tag></tag>
   <elementGuidId>2c7329b8-79f9-4f66-9275-c1693d310927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:validerDossierGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>421e08e2-bfbb-4f2d-8431-db475d642e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion pull-right</value>
      <webElementGuid>a2f9cc7c-4d47-495e-b427-66fffbc85492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:validerDossierGerantPersPhys</value>
      <webElementGuid>fd2a0334-3398-459c-a51a-327863914772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:validerDossierGerantPersPhys</value>
      <webElementGuid>5633bb0c-95a6-494f-88d3-ea13dee45988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setTimeout('document.getElementById(\'' + this.id + '\').disabled=true;', 50);;A4J.AJAX.Submit('gerantPersPhysPopUpForm',event,{'similarityGroupingId':'gerantPersPhysPopUpForm:validerDossierGerantPersPhys','oncomplete':function(request,event,data){if('false'=='true'){document.getElementById('panel').component.hide();}},'parameters':{'gerantPersPhysPopUpForm:validerDossierGerantPersPhys':'gerantPersPhysPopUpForm:validerDossierGerantPersPhys'} } );return false;</value>
      <webElementGuid>3426e6bd-8de3-4041-a3bd-91b0c6f42e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>c3d6f50b-6a50-4cfd-9287-0fdd9afbcc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ab789b3-8d6b-4f93-ae0b-e4c6af4b2b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4403927e-a02c-4797-8878-881273e2c90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:validerDossierGerantPersPhys&quot;)</value>
      <webElementGuid>11e63c9c-7f7e-4009-9cff-e58b48651e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:validerDossierGerantPersPhys']</value>
      <webElementGuid>4040d88b-7188-461e-b4e2-33b42e67d80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/input[6]</value>
      <webElementGuid>761a37be-7626-4634-bbe0-422193f76d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>445a4658-b498-4f76-be5f-8eed00022a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:validerDossierGerantPersPhys' and @name = 'gerantPersPhysPopUpForm:validerDossierGerantPersPhys' and @type = 'button']</value>
      <webElementGuid>5a7f7d9a-49e5-4780-bfc9-d97cc32ca1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
