<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormnomArInGerant_9eeac2</name>
   <tag></tag>
   <elementGuidId>1badafb3-6f13-4f15-a810-fedbb1e084a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;gerantPersPhysPopUpForm:nomArInGerantPersPhys&quot;]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>437ae910-6ba5-4d2d-b365-fb9fb5f5c8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:nomArInGerantPersPhys</value>
      <webElementGuid>ec40ce4d-afaf-42fa-93a2-41c70ed72dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>665b611a-bd5c-4b97-87ae-36ff8b734f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:nomArInGerantPersPhys</value>
      <webElementGuid>049489e3-1584-47ac-bdc3-2bfe697267c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>اسم</value>
      <webElementGuid>f26f6e97-7a87-404b-8341-3f13d22ed01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ArabicLettersTxt ui-keyboard-input ui-widget-content ui-corner-all rtl ui-keyboard-input-current</value>
      <webElementGuid>34be7405-126d-4ae0-b5fd-eda855115c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2d04425a-911e-4214-acbb-d4204e3b7eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c4607ec-055a-4b74-bd68-fd435e5a37b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>94c57d2b-44c7-48ba-9b17-8403928242f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:nomArInGerantPersPhys&quot;)</value>
      <webElementGuid>eccd36f7-40d3-4526-9629-076cc0b13171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:nomArInGerantPersPhys']</value>
      <webElementGuid>da7dd8b8-f2b9-4922-9a3d-f003380d3c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[7]/input</value>
      <webElementGuid>1759972e-df62-43b5-ade3-1e830269abc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/div[7]/input</value>
      <webElementGuid>0f965491-5aef-45bf-a1c7-f4b25c4ab161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:nomArInGerantPersPhys' and @type = 'text' and @name = 'gerantPersPhysPopUpForm:nomArInGerantPersPhys']</value>
      <webElementGuid>f6936f40-d0f8-4c3c-b419-49f3ae3ee81e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
