<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signature et dpt_dossierFormj_id1272</name>
   <tag></tag>
   <elementGuidId>3cf7f86f-2c81-446b-b150-e56a41162d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dossierForm:j_id1272&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dossierForm:j_id1272']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f068b8c6-1de0-48cd-a4af-9e98a80a9e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e4a1cf25-b974-4678-bdae-43627d7e531d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:j_id1272</value>
      <webElementGuid>4f8a8506-119a-446a-a00a-090e0354da6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>77cbeb93-88fb-4af2-aa81-7373965af21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion next</value>
      <webElementGuid>3e4abd8f-7a48-48e8-a0aa-e791d8f339e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8ce614f0-2f36-497f-a15a-fc6064017e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>67417654-d552-4e9c-b2f0-e2c889b2762b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:informationsFiscales&quot;)/table[@class=&quot;rich-tabpanel-content-position&quot;]/tbody[1]/tr[1]/td[@class=&quot;rich-tabpanel-content&quot;]/input[@class=&quot;btn btn-connexion next&quot;]</value>
      <webElementGuid>cdfa104f-8cef-45b4-b965-75676999e90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dossierForm:j_id1272']</value>
      <webElementGuid>2162440e-3389-423b-9e9d-fce2f8b1e764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:informationsFiscales']/table/tbody/tr/td/input[2]</value>
      <webElementGuid>0567573d-604d-4efd-b5af-4c6c7befaa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[2]</value>
      <webElementGuid>c8119666-954d-4e5b-af11-4ff362cdb1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'dossierForm:j_id1272']</value>
      <webElementGuid>44a7f851-fbfb-417f-a6f2-aec4d7280f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
