<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Activits des organisations et organis_853f0d</name>
   <tag></tag>
   <elementGuidId>935086f1-1590-4270-ba11-e5ca27ed013c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeActivitePrim:0:actPriReg:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fde131c3-b058-47ec-a316-43983959f9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>96c489bc-66ad-404a-bf2d-958213604d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeActivitePrim:0:actPriReg</value>
      <webElementGuid>86eae31e-19aa-471e-aa27-1d8e201210e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeActivitePrim:0:actPriReg:0</value>
      <webElementGuid>cbe7f85f-fb29-47d2-8a08-77648bef927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>d3e8eb98-327b-4b68-951e-daef62f5cc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return showPopUp(this.value)</value>
      <webElementGuid>7e10f3f3-78ac-4e02-ba75-5076b54d7fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e0ba5dea-f428-482c-a78b-a6fc64d69df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeActivitePrim:0:actPriReg:0&quot;)</value>
      <webElementGuid>74d81ca1-2714-4bbf-881a-b209e16ad198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeActivitePrim:0:actPriReg:0']</value>
      <webElementGuid>f4c173f9-c48d-4e0d-9de8-72d09174b27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dossierForm:listeActivitePrim:0:actPriReg']/tbody/tr/td/input</value>
      <webElementGuid>5bf962c3-a56a-490f-9e45-1264632fb8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>689261da-420e-4794-a208-410a4c991bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'dossierForm:listeActivitePrim:0:actPriReg' and @id = 'dossierForm:listeActivitePrim:0:actPriReg:0']</value>
      <webElementGuid>29ba321e-068d-4428-af45-9d6cd9df4326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
