<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CINqs12312230082023_dossierFormlisteG_42b6a1</name>
   <tag></tag>
   <elementGuidId>fd92c9e0-6fda-4b22-ad1b-49adb013b82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39aaab81-45b2-4bba-8120-7ade83b371e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-line</value>
      <webElementGuid>60d8d620-f8de-4fad-a420-6d2f94443700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys</value>
      <webElementGuid>afca4948-c6cf-43ee-8b66-18204053cf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys</value>
      <webElementGuid>3f5eb20b-b290-4d2c-9f1e-2bc9c17b311d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys','oncomplete':function(request,event,data){jQuery('*').attr('autocomplete','off');document.getElementById('panel').component.show()},'parameters':{'dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys':'dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys'} } );return false;</value>
      <webElementGuid>41c65341-b89f-4085-8188-42ba503c9740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Modifier</value>
      <webElementGuid>33799a7e-a920-4658-85e3-cc9dc40d49a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>0a232723-01f8-405f-9e26-dae9ea338175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images-new/svg/edit.svg</value>
      <webElementGuid>29036b01-0f52-4e3e-914b-afea65349735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>932dfbda-0b50-407f-a701-38ef44ad2448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys&quot;)</value>
      <webElementGuid>d12cdc8e-4e1e-40c9-8a41-57e903cf656c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys']</value>
      <webElementGuid>d8aaafd5-72ac-49fc-a85d-bd6b693f7ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dossierForm:listeGerantPersPhys:0:j_id1318']/input</value>
      <webElementGuid>1b0410f8-c580-42ee-a35c-8a06329576d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>f58736e4-c982-43c4-a832-8501f66d0ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys' and @name = 'dossierForm:listeGerantPersPhys:0:modifierDossierGerantPersPhys' and @alt = 'Modifier' and @type = 'image' and @src = '/Guichet/images-new/svg/edit.svg']</value>
      <webElementGuid>40cb53f6-03ea-40a4-a60a-02982fc5a201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
