<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormprenomArInGer_89ce7d</name>
   <tag></tag>
   <elementGuidId>3d3357b3-5311-48f5-b7e7-fb9993459851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;gerantPersPhysPopUpForm:prenomArInGerantPersPhys&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d58b4d3-806a-4849-bdd5-9b8141d8ae57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:prenomArInGerantPersPhys</value>
      <webElementGuid>ae502cc4-a569-4d42-aae9-a586ded9aeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>386ecd90-2c1f-4930-adf9-e9fd84bc88ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:prenomArInGerantPersPhys</value>
      <webElementGuid>3fecff78-e830-434f-8d22-9e004657972e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ArabicLettersTxt ui-keyboard-input ui-widget-content ui-corner-all rtl ui-keyboard-input-current</value>
      <webElementGuid>11bd0f55-a15b-4336-807d-da67ac335eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e1cbceef-8c28-4ebb-8b7c-637ba5ea2dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8fe8c871-1d43-4a5d-8674-ad4b8a0ff8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02b21090-9f4b-414d-bcf4-b16f61581414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1bceeb33-c2ca-4f57-bd06-8648905e34b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:prenomArInGerantPersPhys&quot;)</value>
      <webElementGuid>7b3c1836-7e72-473a-8bfa-8458672f3a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:prenomArInGerantPersPhys']</value>
      <webElementGuid>f6f41c7d-3a14-4223-b85a-54f95db7d4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[8]/input</value>
      <webElementGuid>44bbffd1-ee6f-4ef7-8475-ad41c4bd23c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/div[8]/input</value>
      <webElementGuid>969620ed-818f-48cb-8d05-ce80d2e6542b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:prenomArInGerantPersPhys' and @type = 'text' and @name = 'gerantPersPhysPopUpForm:prenomArInGerantPersPhys']</value>
      <webElementGuid>8ff31eb3-6456-44ff-b843-c07f957a85d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
