<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TRANSPORTS ET ENTREPOSAGE_creerViewAc_dfce60</name>
   <tag></tag>
   <elementGuidId>4f7d33b1-2551-4efe-919c-80929bab1bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0b4af7c-6b64-42b1-88f2-f167e93ac92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion</value>
      <webElementGuid>55c6d709-9970-4979-add7-3e69b8c3b1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire</value>
      <webElementGuid>fdaad0af-6dda-48f8-94fe-f737b3b03338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire</value>
      <webElementGuid>dbf86487-0121-47ee-a201-33fe15400123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('creerViewActivitePrimaire:formActivitePrimaire',event,{'similarityGroupingId':'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire','oncomplete':function(request,event,data){{document.getElementById('creerViewActivitePrimaire:panelAjouterActivitePrimaire').component.hide();}},'parameters':{'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire':'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire','ajaxSingle':'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire'} } );return false;</value>
      <webElementGuid>5b7b3b7b-bda3-4d78-9105-6fce38fe127e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>e7a4c839-bc69-4c8b-9be1-4d9065d7c078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3509c307-bbd8-4bd3-a453-e517f34289e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire&quot;)</value>
      <webElementGuid>32f4d9d7-25ba-4fed-b86c-f6e63e5dee7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire']</value>
      <webElementGuid>876077a6-e1b8-421b-a43d-93f1331a8b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='creerViewActivitePrimaire:formActivitePrimaire:j_id4196']/input</value>
      <webElementGuid>9a786c25-a867-41f8-ad34-944ebb1592a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/span/form/div[2]/span/input</value>
      <webElementGuid>652bfb1f-01ef-4b64-9d87-f1df8edf4298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire' and @name = 'creerViewActivitePrimaire:formActivitePrimaire:ajouterActivitePrimaire' and @type = 'button']</value>
      <webElementGuid>1d7a630c-4e09-4954-b8fe-640e046a3f8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
