<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormdateNaissance_e80574</name>
   <tag></tag>
   <elementGuidId>7f4b6f46-7a66-41a8-98e1-99d4c027fc3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f903e5db-259c-4320-9106-1f15ad88d00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input</value>
      <webElementGuid>fb9a62ec-f7f7-40a0-9724-be56d3078dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate</value>
      <webElementGuid>2e83235a-d5ff-426b-acb0-55a26d434d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate</value>
      <webElementGuid>cd934236-3e26-4703-aff6-8b2da434a9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c93289e-a239-4803-a431-978d5b34eb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ae227447-3d25-4bf6-a53c-09d6052de999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>073f1686-477f-4d75-ae1f-279957564580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate&quot;)</value>
      <webElementGuid>cc46dfee-c895-47ea-946a-9b9b0a299ee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate']</value>
      <webElementGuid>64ac6e09-c57d-4a05-9c41-75449f22d5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysPopup']/input</value>
      <webElementGuid>feca2ec6-4dbd-452e-b94d-8d58d9051111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/div[11]/span/input</value>
      <webElementGuid>cd01cff0-c240-41d9-a1a8-9904ca20ad47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate' and @name = 'gerantPersPhysPopUpForm:dateNaissanceInGerantPersPhysInputDate' and @type = 'text']</value>
      <webElementGuid>9f0c2af5-064c-4ee4-a5da-6341f880fae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
