<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Veuillez cliquer sur cette icne pour _e4bfad</name>
   <tag></tag>
   <elementGuidId>9ab7e18f-3519-4c25-a720-b552584cf5bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:initialiserAjoutAssociePersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0753d628-54ba-4328-8b43-acadc0b046c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addPersonne</value>
      <webElementGuid>eb914a37-baa6-4dd7-b625-58d01b73298f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:initialiserAjoutAssociePersPhys</value>
      <webElementGuid>6707f0c0-1fab-4240-abfb-30ecd1d0c7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:initialiserAjoutAssociePersPhys</value>
      <webElementGuid>b98f9420-80e6-4fcc-a8d7-fadaa0ee4b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:initialiserAjoutAssociePersPhys','oncomplete':function(request,event,data){jQuery('*').attr('autocomplete','off');document.getElementById('panelAssocie').component.show()},'parameters':{'dossierForm:initialiserAjoutAssociePersPhys':'dossierForm:initialiserAjoutAssociePersPhys','ajaxSingle':'dossierForm:initialiserAjoutAssociePersPhys'} } );return false;</value>
      <webElementGuid>c62f5112-4ca1-4249-96ea-b22ca860439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ajouter</value>
      <webElementGuid>9a38daf9-5f85-429b-a57b-806a80dfe3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3c048c28-7c66-48ff-aff8-4a236fdf73b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Guichet/images-new/svg/add.svg</value>
      <webElementGuid>777c33f5-5709-4e7e-ab7c-8c41e50cd5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a8b2c4a4-7d42-43fe-8fd9-e02655ba0544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:initialiserAjoutAssociePersPhys&quot;)</value>
      <webElementGuid>92704a1e-b1be-4fcf-aa5b-05582be3f188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:initialiserAjoutAssociePersPhys']</value>
      <webElementGuid>bb6669f7-27e4-4800-9555-4bd40a2801dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:panelAssociePersPhys']/div/input</value>
      <webElementGuid>5c27538c-a96d-4175-ac47-3a6d79a482a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0a313e26-5909-4ed4-8812-c52a7ba7986d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:initialiserAjoutAssociePersPhys' and @name = 'dossierForm:initialiserAjoutAssociePersPhys' and @title = 'Ajouter' and @type = 'image' and @src = '/Guichet/images-new/svg/add.svg']</value>
      <webElementGuid>26a3ecaf-4551-4834-ade7-d216ab69d105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
