<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gerantPersPhysPopUpFormvilleNaissInG_58aca0</name>
   <tag></tag>
   <elementGuidId>f83efb01-185f-405c-8da9-277c60c96e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:villeNaissInGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d024fb9-bdbd-4424-9050-c979e78d3ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:villeNaissInGerantPersPhys</value>
      <webElementGuid>2f3788b1-70eb-497d-9763-38fa20201c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c09936e6-c30d-44d1-930f-d1fb79bb6fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:villeNaissInGerantPersPhys</value>
      <webElementGuid>5c29ad27-e134-48f6-b052-d288f7a5b266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control frenchLettersTxt</value>
      <webElementGuid>d841a444-19ed-4c76-aede-deaa17f739b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>60e1657a-daa0-46e1-a8bc-8d242d2691a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d6645c95-3acc-4a8a-8b24-ca6e2daeba36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:villeNaissInGerantPersPhys&quot;)</value>
      <webElementGuid>41f2a993-51a2-4eb7-abab-4aab9169ed24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:villeNaissInGerantPersPhys']</value>
      <webElementGuid>efc5ca95-385b-42ac-bd11-772c12b77766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[6]/input</value>
      <webElementGuid>6486fa45-f232-4ff4-bbf3-d754375fd081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/table/tbody/tr[2]/td/form/div[6]/input</value>
      <webElementGuid>1fb1b56b-6239-4c1b-b461-4a4ce2eed360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:villeNaissInGerantPersPhys' and @type = 'text' and @name = 'gerantPersPhysPopUpForm:villeNaissInGerantPersPhys']</value>
      <webElementGuid>8a2cac70-a7c0-477c-940e-7afb35f2b984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
