<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oui_ou_Non_Selected_Non</name>
   <tag></tag>
   <elementGuidId>8fa4525b-bfd2-4a06-88d5-2e2fad79bf80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;gerantPersPhysPopUpForm:isCloneAssocie:0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43354ace-68d0-4a66-97a1-29ae702b779c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ef43b0e7-49ba-4ad4-aef1-091d58d81e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>d334ac65-2768-4570-8a84-2ba46d1dc4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:isCloneAssocie</value>
      <webElementGuid>695155f2-88d9-4326-807b-e7ba5b2c338f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:isCloneAssocie:1</value>
      <webElementGuid>e9a42ecf-5a34-44c5-a3bc-6a9862ab5f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>e5db89d0-2c0a-44c9-9468-b487aa66e591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:isCloneAssocie:1&quot;)</value>
      <webElementGuid>6995d71d-1cc6-4ad7-a4fc-e5f6332ecd39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:isCloneAssocie:1']</value>
      <webElementGuid>440fae68-18da-43d4-8d90-d8851cfafa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gerantPersPhysPopUpForm:isCloneAssocie']/tbody/tr/td[2]/input</value>
      <webElementGuid>341c07a7-6190-43b4-8f91-ff918340edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8f493564-e71c-47bf-a8fe-cfe88efeea04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @checked = 'checked' and @name = 'gerantPersPhysPopUpForm:isCloneAssocie' and @id = 'gerantPersPhysPopUpForm:isCloneAssocie:1']</value>
      <webElementGuid>77fbbf26-7d03-44ff-a188-2c64b50b8845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
