<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mandataire_dossierFormmandataire</name>
   <tag></tag>
   <elementGuidId>f80539f3-7fa6-4388-98ad-bdb156e4c810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dossierForm:mandataire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccc5a3da-ad63-4b9a-ad0e-a583fa6a3dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:mandataire</value>
      <webElementGuid>1588b4c6-55e3-4bca-80d3-a7ad5af4e9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d0cee842-4b20-43a8-871e-acf0f9c50fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:mandataire</value>
      <webElementGuid>706c520e-05f0-45bd-91cd-dee839f9b13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id62','parameters':{'dossierForm:j_id62':'dossierForm:j_id62'} } )</value>
      <webElementGuid>ddd9fe61-8474-42cc-842d-aa784e6ae69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c19ac17a-790a-4cca-8b01-299392b2775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:mandataire&quot;)</value>
      <webElementGuid>f64a5101-7b0f-45ad-83dc-0bd65a72f74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dossierForm:mandataire']</value>
      <webElementGuid>0ba77b66-48ce-43b4-be2f-90a09cfae8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dossierForm:gerantAdministrateur']/div/div/label[2]/input</value>
      <webElementGuid>228d865e-11d5-49d5-8763-1dfe3548add7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>ace4c4b9-f813-4c82-b2fc-7efd489e40db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dossierForm:mandataire' and @type = 'checkbox' and @name = 'dossierForm:mandataire']</value>
      <webElementGuid>59989e24-be89-46a1-b187-509de2b18af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
