<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_x</name>
   <tag></tag>
   <elementGuidId>9755892d-e185-4946-acb3-d47430946757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='creerViewActivitePrimaire:hidelink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2a3e7fe2-8ae0-4bc7-a3f9-1123bb8d4433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creerViewActivitePrimaire:hidelink</value>
      <webElementGuid>dbe8f7d7-0011-4469-945b-da1d67dde5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidelink</value>
      <webElementGuid>2a9d9aaf-bfeb-4c71-8a26-76872942d8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>002110dd-cf4a-4345-a395-b11c68c86236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creerViewActivitePrimaire:hidelink&quot;)</value>
      <webElementGuid>08d5191d-9548-498e-b1af-07b736b2897f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='creerViewActivitePrimaire:hidelink']</value>
      <webElementGuid>4742f03f-fc4e-4c02-bbd3-8c708b237bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creerViewActivitePrimaire:panelAjouterActivitePrimaireContentDiv']/div/label</value>
      <webElementGuid>a95d64e0-40f8-4f25-b84b-9749da94781d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'creerViewActivitePrimaire:hidelink', '&quot;', ')')])[1]/following::label[1]</value>
      <webElementGuid>a22a8d73-7f68-44b7-b017-15f86bbc5386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/following::label[1]</value>
      <webElementGuid>51d881c8-93f6-4c64-a07b-07705bb94fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter votre activité principale'])[1]/preceding::label[1]</value>
      <webElementGuid>adeec1c7-4ec8-4924-a380-523787e201be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recherche par mot clé'])[6]/preceding::label[1]</value>
      <webElementGuid>e9296349-ac7a-41a6-add0-be5e7141884b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/label</value>
      <webElementGuid>9bfa7f0b-ca58-49a5-b431-f0d76782f1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'creerViewActivitePrimaire:hidelink' and (text() = 'x' or . = 'x')]</value>
      <webElementGuid>28ccad68-a2ba-4804-b4f5-2741d5029ba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
