<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_x_1</name>
   <tag></tag>
   <elementGuidId>cff6ee82-c2c5-4bc1-8cf4-df98ff3a0ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hidelinkAssocie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='hidelinkAssocie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ee796ad0-57e6-4fa1-9fcd-fbc0446cd915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hidelinkAssocie</value>
      <webElementGuid>57a89f85-2a24-4a48-95d5-68e5ea71b4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidelink</value>
      <webElementGuid>8a5395f7-5109-4edf-a0d3-717f6e12e412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>33c59321-fd04-4f25-a4f3-97d40854a7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>a3c7f40d-2081-4271-a3e8-9f15f6d03ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hidelinkAssocie&quot;)</value>
      <webElementGuid>3336ae55-aac9-434f-aa84-aa2965d4bf3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='hidelinkAssocie']</value>
      <webElementGuid>978e77d5-b729-4393-a723-a91c78432338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panelAssocieContentDiv']/div/label</value>
      <webElementGuid>b90b08c5-4227-4104-a9dd-7e4bcc02b9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'hidelinkAssocie', '&quot;', ')')])[1]/following::label[1]</value>
      <webElementGuid>6b7c7c61-57d2-4fe9-a43b-bd70f86b1a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/following::label[1]</value>
      <webElementGuid>98e79b9a-dec1-46ec-978a-9919874c16c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Associés'])[5]/preceding::label[1]</value>
      <webElementGuid>e6f186f4-eaa5-4dec-a337-39351926b2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/label</value>
      <webElementGuid>8cf57ebf-998a-4057-b2e5-7a9083e0ed98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'hidelinkAssocie' and (text() = 'x' or . = 'x')]</value>
      <webElementGuid>aa0bf2a6-d1c2-4720-a57c-c16a805fa191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
