<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Contrat de bailContrat de domiciliat_e39592</name>
   <tag></tag>
   <elementGuidId>dcbab505-a3fe-4dc8-8a37-74cf7f4ec4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierForm:refTypeDomiciliation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9997933-ed1d-4f07-8419-5baeebbb5a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:refTypeDomiciliation</value>
      <webElementGuid>a72a836e-e276-4a8a-bca9-6001da7bd171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:refTypeDomiciliation</value>
      <webElementGuid>f8996820-24a0-42c4-8b5c-1902cac0d449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>14dd7bab-00bb-4456-9d90-55625a406c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>77b4eb5d-0b0a-4448-a1d5-a182d7786db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id196','parameters':{'dossierForm:j_id196':'dossierForm:j_id196'} } )</value>
      <webElementGuid>d6d34c2a-0b13-49ae-90eb-db15f6652326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eac91378-dd1a-476e-b756-a09e4f1db2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contrat de bailContrat de domiciliationAutres</value>
      <webElementGuid>54f827ba-f481-472f-b81e-1213c1918940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:refTypeDomiciliation&quot;)</value>
      <webElementGuid>c8b79eec-1974-48aa-a5ea-086ed75f8725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierForm:refTypeDomiciliation']</value>
      <webElementGuid>830ec520-824a-4579-a7bb-36f8b182d4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id158_body']/div[7]/div/select</value>
      <webElementGuid>016b602e-c8c2-4229-901a-f4a1b76514f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>926cc722-fc42-4965-8280-5c1d9d7ce9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domiciliataire personne physique'])[1]/preceding::select[1]</value>
      <webElementGuid>2bef99cf-6015-4006-b3d5-0d4bab8cde0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domiciliataire personne morale'])[1]/preceding::select[1]</value>
      <webElementGuid>782b1923-4829-4543-a7ea-75f009e2cfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>a8c6dd4e-3ea7-4267-8033-adf9f56b4aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierForm:refTypeDomiciliation' and @name = 'dossierForm:refTypeDomiciliation' and (text() = 'Contrat de bailContrat de domiciliationAutres' or . = 'Contrat de bailContrat de domiciliationAutres')]</value>
      <webElementGuid>091bbc0a-d4e3-492e-b8c1-bc4ad368a192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
