<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agadir Ida Ou TananeAl HaouzAl Hocei_033512</name>
   <tag></tag>
   <elementGuidId>54169ef2-956c-4d77-8861-d0547f3d4ef8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gerantPersPhysPopUpForm:refProvince']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad77064c-90c6-43c4-b09b-ec8ad26c7d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:refProvince</value>
      <webElementGuid>4929e4cc-afd5-4099-bdd0-9eda5461938a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:refProvince</value>
      <webElementGuid>4b367d5d-f3d6-42fc-870a-f83cedb0ecaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06004a26-3718-45ad-a585-b14a2d2011f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5e1894e3-333d-4717-ab8f-6daafbd7b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('gerantPersPhysPopUpForm',event,{'similarityGroupingId':'gerantPersPhysPopUpForm:j_id3426','parameters':{'gerantPersPhysPopUpForm:j_id3426':'gerantPersPhysPopUpForm:j_id3426'} } )</value>
      <webElementGuid>b8a29ba1-ea83-429d-9792-83f4a8054d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5bec8e3c-7677-4df7-a834-63cb63d2b8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agadir Ida Ou TananeAl HaouzAl HoceimaAousserdAssa-ZagAzilalBenslimaneBerkaneBerrechidBoujdourBoulemaneBéni MellalCasablancaChefchaouenChichaouaChtouka- Ait BahaDriouchEl HajebEl JadidaEl Kelâa des  SraghnaEL YoussoufiaErrachidiaEs-SemaraEssaouiraFahs-AnjraFiguigFquih Ben SalahFèsGuelmimGuercifIfraneInezgane Ait MelloulJeradaKhouribgaKhémissetKhénifraKénitraLaayouneLaracheMarrakechMdiq - FnidqMediounaMeknèsMideltMohammadiaMoulay YacoubNadorNouaceurOuarzazateOued-Ed-DahabOuezzaneOujda-AngadRabatRehamnaSafiSaléSefrouSettatSidi BennourSidi IfniSidi KacemSidi SlimaneSkhirate- TémaraTan-TanTanger -AssilahTaounateTaourirtTarfayaTaroudanntTataTazaTinghirTiznitTétouanZagora</value>
      <webElementGuid>bd654358-eec2-4f73-9193-840e5a466a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:refProvince&quot;)</value>
      <webElementGuid>672fb943-a245-410a-acdb-5c63a8a4b750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gerantPersPhysPopUpForm:refProvince']</value>
      <webElementGuid>09bf274e-bae4-4f85-999d-b6089a1f0f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='gerantPersPhysPopUpForm:villeList']/div/select</value>
      <webElementGuid>3420a969-f5f2-45f1-a588-96ea7aa5b431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[119]/following::select[1]</value>
      <webElementGuid>7a4afc40-7476-4f9d-aa71-69c97ff66928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[120]/preceding::select[1]</value>
      <webElementGuid>798615ec-3184-4924-bc1c-0d6584d20694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/span[2]/div/select</value>
      <webElementGuid>8f41c004-8963-45f4-8637-5e85bd87104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gerantPersPhysPopUpForm:refProvince' and @name = 'gerantPersPhysPopUpForm:refProvince' and (text() = 'Agadir Ida Ou TananeAl HaouzAl HoceimaAousserdAssa-ZagAzilalBenslimaneBerkaneBerrechidBoujdourBoulemaneBéni MellalCasablancaChefchaouenChichaouaChtouka- Ait BahaDriouchEl HajebEl JadidaEl Kelâa des  SraghnaEL YoussoufiaErrachidiaEs-SemaraEssaouiraFahs-AnjraFiguigFquih Ben SalahFèsGuelmimGuercifIfraneInezgane Ait MelloulJeradaKhouribgaKhémissetKhénifraKénitraLaayouneLaracheMarrakechMdiq - FnidqMediounaMeknèsMideltMohammadiaMoulay YacoubNadorNouaceurOuarzazateOued-Ed-DahabOuezzaneOujda-AngadRabatRehamnaSafiSaléSefrouSettatSidi BennourSidi IfniSidi KacemSidi SlimaneSkhirate- TémaraTan-TanTanger -AssilahTaounateTaourirtTarfayaTaroudanntTataTazaTinghirTiznitTétouanZagora' or . = 'Agadir Ida Ou TananeAl HaouzAl HoceimaAousserdAssa-ZagAzilalBenslimaneBerkaneBerrechidBoujdourBoulemaneBéni MellalCasablancaChefchaouenChichaouaChtouka- Ait BahaDriouchEl HajebEl JadidaEl Kelâa des  SraghnaEL YoussoufiaErrachidiaEs-SemaraEssaouiraFahs-AnjraFiguigFquih Ben SalahFèsGuelmimGuercifIfraneInezgane Ait MelloulJeradaKhouribgaKhémissetKhénifraKénitraLaayouneLaracheMarrakechMdiq - FnidqMediounaMeknèsMideltMohammadiaMoulay YacoubNadorNouaceurOuarzazateOued-Ed-DahabOuezzaneOujda-AngadRabatRehamnaSafiSaléSefrouSettatSidi BennourSidi IfniSidi KacemSidi SlimaneSkhirate- TémaraTan-TanTanger -AssilahTaounateTaourirtTarfayaTaroudanntTataTazaTinghirTiznitTétouanZagora')]</value>
      <webElementGuid>c5d9643f-5cc8-4e31-b366-c02983452ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
