<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Acte authentiqueActe authentique tab_54770f</name>
   <tag></tag>
   <elementGuidId>f8820f03-1ffe-4856-aec0-1fe32d8114ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierForm:refTypeActe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d777df08-bd8f-4d48-9afb-dcd0af0b05f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:refTypeActe</value>
      <webElementGuid>c87429d5-dcb7-470d-a1bf-e6613036c5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:refTypeActe</value>
      <webElementGuid>077dcd0d-00e4-4e40-8c24-69154c8beade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>46c4c183-6c9d-4b4a-9d97-596b7053bac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fab18a8b-3818-47b2-baaf-0d19555eb4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>60466270-77fc-40fa-9a25-c2a3d41642ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acte authentiqueActe authentique établi par un notaireActe sous seing privé</value>
      <webElementGuid>6a7c22bf-1f03-4008-ab1e-daaa28fbaf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:refTypeActe&quot;)</value>
      <webElementGuid>0dff3240-2c17-41cb-9067-8558b17163c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierForm:refTypeActe']</value>
      <webElementGuid>14f74820-6fd5-4bf9-b1a0-3addc6847245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id327_body']/div/div/select</value>
      <webElementGuid>c6c8351a-a453-453e-af6f-1db5ba335f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[21]/following::select[1]</value>
      <webElementGuid>bbad3cd5-3c00-4b00-adfe-1e747d63d141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[22]/preceding::select[1]</value>
      <webElementGuid>c24d41f9-5e5a-4ff5-a830-b4cb115df9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div/select</value>
      <webElementGuid>96f05f0f-5d89-444f-a6ee-f96d86e62ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierForm:refTypeActe' and @name = 'dossierForm:refTypeActe' and (text() = 'Acte authentiqueActe authentique établi par un notaireActe sous seing privé' or . = 'Acte authentiqueActe authentique établi par un notaireActe sous seing privé')]</value>
      <webElementGuid>3b57f309-e76a-4892-b91d-e28ad3b54f34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
