<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agdal RiyadHassanSouissiTouargaYacou_2c619b</name>
   <tag></tag>
   <elementGuidId>06080ba9-f060-4f0d-97d2-64dbaa069e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dossierForm:refCommune']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9876106a-f620-4c43-a4d2-cf36bf1458e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
      <webElementGuid>1fa7e5d9-fabb-4f07-b618-7a4e27d3b8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dossierForm:refCommune</value>
      <webElementGuid>a6470242-4266-4dc5-a65a-6257069c376a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dossierForm:refCommune</value>
      <webElementGuid>2c5be71d-e471-4fab-a02b-de2eab77bfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>756e857c-c4e4-4b15-a4cb-7617e0866af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>392e5d12-c2a0-4390-ada9-bacb0ac24da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('dossierForm',event,{'similarityGroupingId':'dossierForm:j_id183','parameters':{'dossierForm:j_id183':'dossierForm:j_id183'} } )</value>
      <webElementGuid>0640165d-3c2f-4575-9080-3734b7b4a1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agdal RiyadHassanSouissiTouargaYacoub El Mansour</value>
      <webElementGuid>1b08148b-d993-499c-988b-b5c3d5351a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dossierForm:refCommune&quot;)</value>
      <webElementGuid>2d1c8abf-c02d-42ad-96ce-9224a7290644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dossierForm:refCommune']</value>
      <webElementGuid>96916689-67c6-4218-9049-4e8fa82e1bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dossierForm:j_id158_body']/div[4]/div/select</value>
      <webElementGuid>31059853-d0cb-49c4-bf85-3f2d1dae808d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>4aa3d9bd-35d9-430f-99c0-03190eb6c455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tribunal'])[1]/preceding::select[1]</value>
      <webElementGuid>ce37d0da-689d-487e-9a67-713e0f6b936d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code postal'])[1]/preceding::select[1]</value>
      <webElementGuid>c8e7a210-5512-47f4-b99d-df16a8790ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>437dbcad-9585-4070-9017-e0fe4b0517d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dossierForm:refCommune' and @name = 'dossierForm:refCommune' and (text() = 'Agdal RiyadHassanSouissiTouargaYacoub El Mansour' or . = 'Agdal RiyadHassanSouissiTouargaYacoub El Mansour')]</value>
      <webElementGuid>a7e5bc0a-3025-4ba0-84a9-05d2691ce869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
