<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Co-GrantGrant</name>
   <tag></tag>
   <elementGuidId>5b61a1cd-03d2-4a19-a57d-8aba606bec57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gerantPersPhysPopUpForm:refQualiteDirigeant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5e74b061-c9ec-4e52-81ee-fa500b247581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:refQualiteDirigeant</value>
      <webElementGuid>14c6aecd-2765-4cbd-bf36-913ac84890d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:refQualiteDirigeant</value>
      <webElementGuid>48efd7a2-b0ba-4b8c-8423-a66b1b8dc87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd3f0303-05a7-420e-8af1-a125ca3b8f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d74cdcf6-b0ac-4876-b537-a3bbe44c9345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6b69afb2-7607-4d79-b291-083ef1c87551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Co-GérantGérant</value>
      <webElementGuid>c0d2f855-5aa3-4241-9031-3883dbac5e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:refQualiteDirigeant&quot;)</value>
      <webElementGuid>47da8cda-4b20-475a-b369-034934099761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gerantPersPhysPopUpForm:refQualiteDirigeant']</value>
      <webElementGuid>c7b60538-20cf-4d0b-ad4a-21d98f75a62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[2]/select</value>
      <webElementGuid>818f8514-01bf-4626-b025-0a89cb020cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[105]/following::select[1]</value>
      <webElementGuid>39f9dc57-6241-4c72-940c-24d01f47f3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[106]/preceding::select[1]</value>
      <webElementGuid>924b6133-78c6-4b25-ab53-ba38b0d28883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/select</value>
      <webElementGuid>20713f79-3698-4f71-9463-6dd2f57ad937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gerantPersPhysPopUpForm:refQualiteDirigeant' and @name = 'gerantPersPhysPopUpForm:refQualiteDirigeant' and (text() = 'Co-GérantGérant' or . = 'Co-GérantGérant')]</value>
      <webElementGuid>b1c6e077-a959-49c2-b6f5-4a45b3f7175d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
