<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Al-FidaAnfaAssoukhour AssawdaAn-Choc_d721e0</name>
   <tag></tag>
   <elementGuidId>0e6d55ad-c4df-4261-bafd-3fc8641cb436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gerantPersPhysPopUpForm:refCommune']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b2de39df-ad2a-4992-b8a5-190f018ec2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:refCommune</value>
      <webElementGuid>46e18b04-9068-4b53-927b-0d251562ad99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:refCommune</value>
      <webElementGuid>7350f80e-1867-44fd-8875-aa993b95febb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3fb5d78-5c9e-408e-a6e5-1ca5b164150f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1f1f4e4-2652-49c8-9830-cfbe51bf377c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane</value>
      <webElementGuid>16ecb2cd-2289-47e5-adc3-e63be2bd621e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:refCommune&quot;)</value>
      <webElementGuid>e46dbe1a-a89d-48db-a119-ae773dcf39f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gerantPersPhysPopUpForm:refCommune']</value>
      <webElementGuid>dde09cee-96c5-4369-89e6-4c8dd4f0fe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gerantPersPhysPopUpForm:refCommuneEtablissementPanel']/tbody/tr/td/select</value>
      <webElementGuid>dd0c4b91-66a2-414f-94ca-e53130cca5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[120]/following::select[1]</value>
      <webElementGuid>9b2332a3-1311-4f08-ac63-f24f354a5852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[121]/preceding::select[1]</value>
      <webElementGuid>d90fd116-81c0-435c-88eb-6062f2eb4d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/span[2]/div[2]/div/table/tbody/tr/td/select</value>
      <webElementGuid>b3532806-9139-43cc-856f-65b69608737f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gerantPersPhysPopUpForm:refCommune' and @name = 'gerantPersPhysPopUpForm:refCommune' and (text() = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane' or . = 'Al-FidaAnfaAssoukhour AssawdaAîn-ChockAîn-SebaâBen M’SickEl MaarifHay MohammadiHay-HassaniMechouar de CasablancaMers-SultanMoulay RachidSbataSidi BelyoutSidi BernoussiSidi MoumenSidi Othmane')]</value>
      <webElementGuid>1c3142c6-9c04-4dca-9ce0-8d90ef894637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
