<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>039d03a0-99ec-457c-a178-73e4ad3b20b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-keyboard-button.ui-keyboard-1593.ui-state-default.ui-corner-all.ui-state-hover > span.ui-keyboard-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gerantPersPhysPopUpForm:adresse1ArInGerantPersPhys_keyboard']/div/button[22]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88ea14ab-667a-4953-9357-4e6eb73f1392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-keyboard-text</value>
      <webElementGuid>4e407a88-cb34-444a-81e0-9844b96e8af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ع</value>
      <webElementGuid>20aaedf7-c53c-4365-8990-26f7e211d61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:adresse1ArInGerantPersPhys_keyboard&quot;)/div[@class=&quot;ui-keyboard-keyset ui-keyboard-keyset-normal&quot;]/button[@class=&quot;ui-keyboard-button ui-keyboard-1593 ui-state-default ui-corner-all ui-state-hover&quot;]/span[@class=&quot;ui-keyboard-text&quot;]</value>
      <webElementGuid>3bb65c54-84df-4eb3-a963-b387a1d513e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gerantPersPhysPopUpForm:adresse1ArInGerantPersPhys_keyboard']/div/button[22]/span</value>
      <webElementGuid>4ea602d3-58b4-4a4c-b07d-155db92c437e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='غ'])[1]/following::span[1]</value>
      <webElementGuid>df379389-0f64-4ccc-a95c-6e2474878cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ف'])[1]/following::span[2]</value>
      <webElementGuid>1a954963-421c-4bd1-995b-1db4e6867856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ه'])[1]/preceding::span[1]</value>
      <webElementGuid>7ef046d4-bafd-4e94-8a16-143577753fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خ'])[1]/preceding::span[2]</value>
      <webElementGuid>c73f25da-e11b-4e15-9608-220ad1421616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ع']/parent::*</value>
      <webElementGuid>312677a4-19cc-417a-8e21-84b7d5bde529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[22]/span</value>
      <webElementGuid>cff8e08b-10fb-45d8-8f1b-6129470cd16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ع' or . = 'ع')]</value>
      <webElementGuid>4fa1fc0d-6adf-43e3-927f-9ee2d7797d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
