<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_30</name>
   <tag></tag>
   <elementGuidId>157f1f14-4668-4471-b161-db0d6f8545ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysDayCell30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b67a93a9-652a-4922-a126-291a91172de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-cell-size rich-calendar-cell rich-calendar-btn rich-calendar-hover</value>
      <webElementGuid>41b92397-56dd-4cee-84ef-01ddf5587ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysDayCell30</value>
      <webElementGuid>13ed8253-029e-44b3-ba82-cdc38c0167a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhys').component.eventCellOnClick(event, this);</value>
      <webElementGuid>9c7cefd2-38ca-4ef3-ab7d-21da3bbbcf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>$('gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhys').component.eventCellOnMouseOver(event, this);</value>
      <webElementGuid>136b0899-300a-4f35-b95b-723e4d239d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>$('gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhys').component.eventCellOnMouseOut(event, this);</value>
      <webElementGuid>e852cef6-63dc-4237-bf3a-a329af036c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc307a11-3b33-4f37-ac0e-4a8ab6021f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9d455225-4bc5-4427-a1ad-126a6a5f45f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysDayCell30&quot;)</value>
      <webElementGuid>74504649-5309-4243-83f6-77cec8003df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysDayCell30']</value>
      <webElementGuid>f0ef7f40-1727-4b99-b411-98307b3333ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysWeekNum5']/td[4]</value>
      <webElementGuid>04a76434-be9b-49d7-827c-465c00008f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dim.'])[22]/following::td[36]</value>
      <webElementGuid>a0f3b620-86cf-4c9f-8c82-1086bdd8eb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sam.'])[22]/following::td[37]</value>
      <webElementGuid>7dd1f44b-e761-465c-8e2b-27f178f181f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[3]/preceding::td[17]</value>
      <webElementGuid>2972415e-2368-4307-b66e-728f7d007edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/table/tbody/tr[7]/td[4]</value>
      <webElementGuid>df70cba7-2eed-4a1f-baa1-d7dd6ef34e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'gerantPersPhysPopUpForm:dateValPieceIdInGerantPersPhysDayCell30' and (text() = '30' or . = '30')]</value>
      <webElementGuid>9ad8cb64-f48f-4ce4-a5a9-f6221775dd2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
