<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Adress</name>
   <tag></tag>
   <elementGuidId>dfcc4590-b029-4559-8b71-f29a1dba413f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='gerantPersPhysPopUpForm:adresse1InGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>be8e5c46-8e88-4b86-ab5e-e1f239b3120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:adresse1InGerantPersPhys</value>
      <webElementGuid>9ac32af4-f7ae-4f3a-8813-9301f27c041d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:adresse1InGerantPersPhys</value>
      <webElementGuid>62246f0b-6722-4e2f-87bc-e169999c0668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control frenchTxt</value>
      <webElementGuid>49e9fb9b-923a-435e-80b5-ed780a58cc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>1d39c6e6-e970-491a-ac03-a75938e6dc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>c7f163b2-56fe-4611-8ed9-430f3abc9c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>621f1cc4-dd70-419a-bea2-4b33e0f7c43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:adresse1InGerantPersPhys&quot;)</value>
      <webElementGuid>c2ada8b8-f6fb-403e-a941-4300f5aca124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='gerantPersPhysPopUpForm:adresse1InGerantPersPhys']</value>
      <webElementGuid>effc5683-1592-4c88-a157-3c1d2658555d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/div[12]/textarea</value>
      <webElementGuid>dc102c40-2ad1-4fe6-949e-423db342555e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[12]/textarea</value>
      <webElementGuid>82154c7a-21bd-4b44-9548-9f389f498deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'gerantPersPhysPopUpForm:adresse1InGerantPersPhys' and @name = 'gerantPersPhysPopUpForm:adresse1InGerantPersPhys']</value>
      <webElementGuid>0974ed33-ad26-42df-ad0d-5d28fed2d5f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
