<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_Slectionner</name>
   <tag></tag>
   <elementGuidId>7ccceb24-b077-4cec-ab15-ca2be1c6b098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#up1 > u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='up1']/u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>f95858fc-93a2-4849-90ef-2bae4027d31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a0e3516e-be75-4d55-867b-8cd2cb306cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sélectionner</value>
      <webElementGuid>7e19d767-0f18-4e39-817a-82bbe96a628c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;up1&quot;)/u[1]</value>
      <webElementGuid>090d8ab6-a719-41bd-8380-2ce4db7406ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='up1']/u</value>
      <webElementGuid>b692864b-1b8f-40cf-aa1c-49101a486cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::u[1]</value>
      <webElementGuid>4c8d5690-c945-4cbd-b6c8-e6ad1faf7393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(5 Mo)'])[1]/following::u[1]</value>
      <webElementGuid>88ad9bcb-11df-415e-a33a-a31534ae4b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 Mo)'])[2]/preceding::u[1]</value>
      <webElementGuid>3090c7b4-34d0-4405-8157-8be6314f3236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/u</value>
      <webElementGuid>cdfe242c-14a4-43d9-a5fc-eff3a098a925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Sélectionner' or . = 'Sélectionner')]</value>
      <webElementGuid>b332b460-0fcb-4eee-9a72-2297a45cb71a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
