<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ValiderFormulaireDirigeants</name>
   <tag></tag>
   <elementGuidId>4b867cfc-1815-4a3f-84b9-74716f8ca373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a172fad-cf7e-4393-8329-19a0b00411b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-connexion pull-right</value>
      <webElementGuid>1b35e62c-282a-48bf-b568-d9561e0c15cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys</value>
      <webElementGuid>e562c7a1-6511-448c-b70b-d575c48b3579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys</value>
      <webElementGuid>bdfbc73b-d30a-4fd5-97f7-d4eceedbba4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setTimeout('document.getElementById(\'' + this.id + '\').disabled=true;', 50);;A4J.AJAX.Submit('gerantPersPhysPopUpForm',event,{'similarityGroupingId':'gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys','oncomplete':function(request,event,data){if('false'=='true'){document.getElementById('panel').component.hide();}},'parameters':{'gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys':'gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys'} } );return false;</value>
      <webElementGuid>8dee2832-199c-409f-9606-cd986e5734ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Valider</value>
      <webElementGuid>ec22af12-5642-45e5-b778-362fb36e2179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>514e480d-84a0-44b3-837c-447ff4df4f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bb89928d-0491-4151-bd49-2a42a66598f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b9fca6d-0efa-43bf-a826-87b8c4aa8db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys&quot;)</value>
      <webElementGuid>8d19aa6b-b44a-4b8c-9e1f-09f87467ba55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys']</value>
      <webElementGuid>4d25ced0-ce19-4558-a47d-4cecd0850c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gerantPersPhysPopUpForm']/input[6]</value>
      <webElementGuid>c0d6a325-97c0-48d5-b3a3-86c649a870f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>6191f083-abfc-440b-bc65-c2aa431ffcbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys' and @name = 'gerantPersPhysPopUpForm:ajouterDossierGerantPersPhys' and @type = 'button']</value>
      <webElementGuid>26ae31ea-6f2f-4391-b1c7-199c09c1a1f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
